import { Question } from './types';

export const GK_13_PLUS_QUESTIONS: Question[] = [
  {
    id: 'gk-13-1',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the capital city of Australia?',
    questionHe: 'מָהִי עִיר הַבִּירָה שֶׁל אוֹסְטְרַלְיָה?',
    optionsEn: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    optionsHe: ['סידני', 'מלבורן', 'קַנְבֵּרָה', 'בריסבן'],
    answerIndex: 2,
    explanationEn: 'While Sydney and Melbourne are larger, Canberra was selected as the capital in 1908 as a compromise.',
    explanationHe: 'קנברה נבחרה כפשרה בין סידני למלבורן כבירת אוסטרליה בשנת 1908.'
  },
  {
    id: 'gk-13-2',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the approximate speed of light in a vacuum?',
    questionHe: 'מָהִי מְהִירוּת הָאוֹר הַמְּקֹרֶבֶת בְּרֵיק?',
    optionsEn: ['3,000 km/s', '300,000 km/s', '3,000,000 km/s', '30,000 km/s'],
    optionsHe: ['3,000 קמ"ש', '300,000 קמ"ש (קילומטר לשנייה)', '3,000,000 קמ"ש', '30,000 קמ"ש'],
    answerIndex: 1,
    explanationEn: 'Light travels at approximately 299,792 kilometers per second (commonly rounded to 300,000 km/s).',
    explanationHe: 'האור נע במהירות של כ-300,000 קילומטרים בשנייה אחת.'
  },
  {
    id: 'gk-13-3',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which chemical element is represented by the symbol "O" in the periodic table?',
    questionHe: 'אֵיזֶה יְסוֹד כִּימִי מְיֻצָּג עַל יְדֵי הָאוֹת "O" בַּטַּבְלָה הַמַּחְזוֹרִית?',
    optionsEn: ['Gold', 'Oxygen', 'Osmium', 'Carbon'],
    optionsHe: ['זהב', 'חַמְצָן', 'אוסמיום', 'פחמן'],
    answerIndex: 1,
    explanationEn: 'Oxygen is highly reactive and essential for cellular respiration in most living organisms.',
    explanationHe: 'האות O מייצגת חמצן (Oxygen), יסוד חיוני לנשימה של יצורים חיים רבים.'
  },
  {
    id: 'gk-13-4',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Who wrote the famous dystopian political novel titled "1984"?',
    questionHe: 'מִי כָּתַב אֶת הָרוֹמָן הַדִּיסְטוֹפִּי הַמְּפֻרְסָם "1984"?',
    optionsEn: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'],
    optionsHe: ['אלדוס האקסלי', 'ג׳וֹרְג׳ אוֹרְוֶול', 'ריי ברדבורי', 'הרברט ג׳ורג׳ ולס'],
    answerIndex: 1,
    explanationEn: 'George Orwell published the novel in 1949, introducing terms like "Big Brother" and "Doublethink".',
    explanationHe: 'ג׳ורג׳ אורוול כתב את הספר 1984, המציג חברה טוטליטרית תחת פיקוחו של "האח הגדול".'
  },
  {
    id: 'gk-13-5',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which is the largest country in the world by total land area?',
    questionHe: 'מָהִי הַמְּדִינָה הַגְּדוֹלָה בָּעוֹלָם בְּשִׁטְחָהּ?',
    optionsEn: ['Canada', 'China', 'United States', 'Russia'],
    optionsHe: ['קנדה', 'סין', 'ארצות הברית', 'רוּסְיָה'],
    answerIndex: 3,
    explanationEn: 'Russia spans over 17 million square kilometers, covering more than one-eighth of Earth’s inhabited land.',
    explanationHe: 'רוסיה היא המדינה הגדולה ביותר ושטחה עולה על 17 מיליון קילומטרים רבועים.'
  },
  {
    id: 'gk-13-6',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the official currency of the United Kingdom?',
    questionHe: 'מַהוּ הַמַּטְבֵּעַ הָרִשְׁמִי שֶׁל הַמַּמְלָכָה הַמְּאֻחֶדֶת (בְּרִיטַנְיָה)?',
    optionsEn: ['Euro', 'Pound Sterling', 'Dollar', 'Franc'],
    optionsHe: ['אירו', 'לִירָה שְׁטֶרְלִינְג (פָּאוּנְד)', 'דולר', 'פרנק'],
    answerIndex: 1,
    explanationEn: 'The Pound Sterling (£) is the oldest currency still in active use in the world.',
    explanationHe: 'לירה שטרלינג היא המטבע הרשמי של בריטניה והיא מסומנת בסמל £.'
  },
  {
    id: 'gk-13-7',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which theoretical physicist formulated the Theory of General Relativity?',
    questionHe: 'אֵיזֶה פִיזִיקַאי תֵּאוֹרֵטִי נִסַּח אֶת תּוֹרַת הַיַּחֲסוּת הַכְּלָלִית?',
    optionsEn: ['Isaac Newton', 'Albert Einstein', 'Stephen Hawking', 'Niels Bohr'],
    optionsHe: ['אייזק ניוטון', 'אַלְבֶּרְט אַיְינְשְׁטַיְין', 'סטיבן הוקינג', 'נילס בוהר'],
    answerIndex: 1,
    explanationEn: 'Albert Einstein published General Relativity in 1915, revolutionizing our understanding of gravity and space-time.',
    explanationHe: 'אלברט איינשטיין הגה את תורת היחסות ושינה לחלוטין את הדרך שבה אנו מבינים את כוח הכבידה.'
  },
  {
    id: 'gk-13-8',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the capital city of Canada?',
    questionHe: 'מָהִי עִיר הַבִּירָה שֶׁל קָנָדָה?',
    optionsEn: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
    optionsHe: ['טורונטו', 'וונקובר', 'אוֹטָאוָה', 'מונטריאול'],
    answerIndex: 2,
    explanationEn: 'Ottawa was chosen as the capital in 1857 by Queen Victoria due to its defensible inland location.',
    explanationHe: 'אוטאווה נבחרה לבירה על ידי המלכה ויקטוריה בזכות מיקומה האסטרטגי הרחק מהגבול.'
  },
  {
    id: 'gk-13-9',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which gas is the most abundant in Earth’s atmosphere?',
    questionHe: 'אֵיזֶה גַּז הוּא הַנָּפוֹץ בְּיוֹתֵר בָּאַטְמוֹסְפֵירָה שֶׁל כַּדּוּר הָאָרֶץ?',
    optionsEn: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'],
    optionsHe: ['חמצן', 'חַנְקָן', 'דו-פחמן חמצני', 'ארגון'],
    answerIndex: 1,
    explanationEn: 'Nitrogen makes up approximately 78% of Earth’s atmosphere, followed by Oxygen at 21%.',
    explanationHe: 'חנקן (Nitrogen) מהווה כ-78% מהאוויר שאנו נושמים, בעוד שחמצן מהווה רק כ-21%.'
  },
  {
    id: 'gk-13-10',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which is the longest river located entirely within the continent of Europe?',
    questionHe: 'מַהוּ הַנָּהָר הָאָרֹךְ בְּיוֹתֵר בְּיַבָּשֶׁת אֵירוֹפָּה?',
    optionsEn: ['Danube', 'Rhine', 'Volga', 'Seine'],
    optionsHe: ['דנובה', 'ריין', 'ווֹלְגָה', 'סן'],
    answerIndex: 2,
    explanationEn: 'The Volga River flows through Central Russia into the Caspian Sea, spanning 3,530 kilometers.',
    explanationHe: 'נהר הוולגה הוא הארוך ביותר באירופה, והוא זורם ברוסיה לאורך של כ-3,530 קילומטרים.'
  },
  {
    id: 'gk-13-11',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Who was the first woman to win a prestigious Nobel Prize?',
    questionHe: 'מִי הָיְתָה הָאִשָּׁה הָרִאשׁוֹנָה שֶׁזָּכְתָה בִּפְרָס נוֹבֶּל?',
    optionsEn: ['Marie Curie', 'Mother Teresa', 'Jane Addams', 'Rosalind Franklin'],
    optionsHe: ['מָארִי קִירִי', 'אמא תרזה', 'ג׳יין אדמס', 'רוזלינד פרנקלין'],
    answerIndex: 0,
    explanationEn: 'Marie Curie won the Nobel Prize in Physics in 1903 and later a second in Chemistry in 1911.',
    explanationHe: 'מארי קירי הייתה האישה הראשונה לזכות בפרס נובל והאדם היחיד שזכה בשני תחומים מדעיים שונים.'
  },
  {
    id: 'gk-13-12',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the deepest known oceanic trench on Earth?',
    questionHe: 'מַהוּ הַשֶּׁקַע הָאוֹקְיָנוּסִי הֶעָמֹק בְּיוֹתֵר בָּעוֹלָם?',
    optionsEn: ['Puerto Rico Trench', 'Java Trench', 'Mariana Trench', 'Tonga Trench'],
    optionsHe: ['שקע פורטו ריקו', 'שקע ג׳אווה', 'שֶׁקַע מַרְיָאנָה', 'שקע טונגה'],
    answerIndex: 2,
    explanationEn: 'The Mariana Trench in the western Pacific Ocean reaches a maximum depth of nearly 11,000 meters.',
    explanationHe: 'שקע מריאנה באוקיינוס השקט מגיע לעומק מדהים של כמעט 11 קילומטרים מתחת לפני הים.'
  },
  {
    id: 'gk-13-13',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which chemical element forms the basis of all known organic molecules?',
    questionHe: 'אֵיזֶה יְסוֹד כִּימִי מְהַוֶּה אֶת הַבָּסִיס לְכָל הַתַּרְכּוֹבוֹת הָאוֹרְגָּנִיּוֹת הַיְּדוּעוֹת?',
    optionsEn: ['Hydrogen', 'Oxygen', 'Carbon', 'Nitrogen'],
    optionsHe: ['מימן', 'חמצן', 'פֶּחְמָן (קַרְבּוֹן)', 'חנקן'],
    answerIndex: 2,
    explanationEn: 'Carbon atoms can form up to four strong covalent bonds, making complex biological structures possible.',
    explanationHe: 'הפחמן הוא יסוד ייחודי המסוגל ליצור שרשראות מורכבות המהוות בסיס לחיים עצמם.'
  },
  {
    id: 'gk-13-14',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the name of the official currency used in South Africa?',
    questionHe: 'מַהוּ שְׁמוֹ שֶׁל הַמַּטְבֵּעַ הָרִשְׁמִי הַנָּהוּג בִּדְרוֹם אַפְרִיקָה?',
    optionsEn: ['Rand', 'Shilling', 'Krona', 'Rupee'],
    optionsHe: ['רַאנְד', 'שילינג', 'קרונה', 'רופי'],
    answerIndex: 0,
    explanationEn: 'The South African Rand (ZAR) is divided into 100 cents and is named after the Witwatersrand ridge.',
    explanationHe: 'המטבע של דרום אפריקה נקרא ראנד (Rand) והוא מסומן באות R.'
  },
  {
    id: 'gk-13-15',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which ancient Mediterranean city-state was home to the philosopher Socrates?',
    questionHe: 'אֵיזוֹ עִיר-מְדִינָה עַתִּיקָה הָיְתָה בֵּיתוֹ שֶׁל הַפִּילוֹסוֹף סוֹקְרָטֶס?',
    optionsEn: ['Sparta', 'Athens', 'Rome', 'Alexandria'],
    optionsHe: ['ספרטה', 'אַתּוּנָה', 'רומא', 'אלכסנדריה'],
    answerIndex: 1,
    explanationEn: 'Socrates lived in Athens during the Golden Age and is considered a founder of Western philosophy.',
    explanationHe: 'סוקרטס פעל באתונה העתיקה שם לימד את תלמידיו, כולל אפלטון המפורסם.'
  },
  {
    id: 'gk-13-16',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'In computer science and hardware, what does "CPU" stand for?',
    questionHe: 'בְּמַדְּעֵי הַמַּחְשֵׁב, מָה רָאשֵׁי הַתֵּבוֹת שֶׁל הַ-CPU?',
    optionsEn: ['Computer Processing Unit', 'Central Processing Unit', 'Central Path User', 'Control Power Utility'],
    optionsHe: ['Computer Processing Unit', 'Central Processing Unit (יְחִידַת עִבּוּד מֶרְכָּזִית)', 'Central Path User', 'Control Power Utility'],
    answerIndex: 1,
    explanationEn: 'The CPU performs basic arithmetic, logic, and control operations, acting as the brain of the computer.',
    explanationHe: 'ה-CPU הוא המעבד המרכזי של המחשב שמבצע את רוב החישובים וניהול המשימות.'
  },
  {
    id: 'gk-13-17',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the de facto capital city of Switzerland?',
    questionHe: 'מָהִי עִיר הַבִּירָה (הַבִּירָה הַמִּנְהָלִית בְּפֹעַל) שֶׁל שְׁוַיְץ?',
    optionsEn: ['Zurich', 'Geneva', 'Bern', 'Basel'],
    optionsHe: ['ציריך', 'ז׳נבה', 'בֶּרְן', 'באזל'],
    answerIndex: 2,
    explanationEn: 'Switzerland does not have an official constitutional capital, but Bern is the federal city housing the government.',
    explanationHe: 'לשוויץ אין בירה רשמית בחוק, אך ברן היא מושב הממשלה ומשמשת כבירה בפועל.'
  },
  {
    id: 'gk-13-18',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which nation has the longest total coastline in the world?',
    questionHe: 'לְאֵיזוֹ מְדִינָה יֵשׁ אֶת קַו הַחוֹף הָאָרֹךְ בָּעוֹלָם?',
    optionsEn: ['United States', 'Russia', 'Australia', 'Canada'],
    optionsHe: ['ארצות הברית', 'רוסיה', 'אוסטרליה', 'קָנָדָה'],
    answerIndex: 3,
    explanationEn: 'Canada’s coastline stretches for over 202,080 kilometers, bordered by three oceans.',
    explanationHe: 'קו החוף של קנדה הוא הארוך ביותר בעולם ועולה על 200 אלף קילומטרים.'
  },
  {
    id: 'gk-13-19',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which brilliant post-impressionist Dutch painter created "The Starry Night"?',
    questionHe: 'אֵיזֶה צַיָּר הוֹלַנְדִּי מְפֻרְסָם צִיֵּר אֶת יְצִירַת הַמּוֹפֵת "לֵיל כּוֹכָבִים" (Starry Night)?',
    optionsEn: ['Claude Monet', 'Vincent van Gogh', 'Rembrandt', 'Salvador Dali'],
    optionsHe: ['קלוד מונה', 'וִינְסֶנְט וַאן גּוֹךְ', 'רמברנדט', 'סלבדור דאלי'],
    answerIndex: 1,
    explanationEn: 'Vincent van Gogh painted The Starry Night in 1889 from his room at an asylum in France.',
    explanationHe: 'וינסנט ואן גוך צייר את ליל כוכבים המפורסם תוך כדי שהות במרכז טיפול בצרפת.'
  },
  {
    id: 'gk-13-20',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the standard unit of electrical resistance in physics?',
    questionHe: 'מָהִי יְחִידַת הַמִּדָּה הַפִּיזִיקָלִית שֶׁל הִתְנַגְּדוּת חַשְׁמַלִּית?',
    optionsEn: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    optionsHe: ['וולט', 'אמפר', 'אוֹהֶם (Ohm)', 'וואט'],
    answerIndex: 2,
    explanationEn: 'Ohm is named after Georg Simon Ohm and is represented by the Greek letter Omega (Ω).',
    explanationHe: 'יחידת המידה להתנגדות היא אוהם, הקרויה על שם הפיזיקאי הגרמני גאורג אוהם.'
  },
  {
    id: 'gk-13-21',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which massive historical empire was ruled by Julius Caesar?',
    questionHe: 'אֵיזוֹ אִימְפֶּרְיָה הִיסְטוֹרִית עֲנָקִית נִשְׂרְרָה עַל יְדֵי יוּלְיוּס קֵיְסָר?',
    optionsEn: ['Greek Empire', 'Roman Empire', 'Ottoman Empire', 'Mongol Empire'],
    optionsHe: ['האימפריה היוונית', 'הָאִימְפֶּרְיָה הָרוֹמִית', 'האימפריה העות׳מאנית', 'האימפריה המונגולית'],
    answerIndex: 1,
    explanationEn: 'Julius Caesar was a Roman general and statesman who led to the rise of the Roman Empire.',
    explanationHe: 'יוליוס קיסר היה מצביא ומדינאי רומי שהוביל לשינוי הרפובליקה לאימפריה רומית.'
  },
  {
    id: 'gk-13-22',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which planet in our Solar System possesses the most prominent, bright ring system?',
    questionHe: 'לְאֵיזֶה כּוֹכַב לֶכֶת בְּמַעֲרֶכֶת הַשֶּׁמֶשׁ יֵשׁ אֶת מַעֲרֶכֶת הַטַּבְּעוֹת הַבּוֹלֶטֶת בְּיוֹתֵר?',
    optionsEn: ['Jupiter', 'Uranus', 'Neptune', 'Saturn'],
    optionsHe: ['צדק', 'אורנוס', 'נפטון', 'שַׁבְּתַאי (סָאטוּרְן)'],
    answerIndex: 3,
    explanationEn: 'Saturn’s rings are made mostly of water ice particles, ranging in size from dust grains to mountains.',
    explanationHe: 'שבתאי ידוע בטבעות המרשימות והמרהיבות שלו העשויות בעיקר מחלקיקי קרח ואבק.'
  },
  {
    id: 'gk-13-23',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the main structural protein found in human hair, skin, and nails?',
    questionHe: 'מַהוּ הַחֶלְבּוֹן הַמִּבְנֶה הָעִקָּרִי הַמַּרְכִּיב אֶת הַשֵּׂעָר, הָעוֹר וְהַצִּפָּרְנַיִם שֶׁלָּנוּ?',
    optionsEn: ['Collagen', 'Keratin', 'Elastin', 'Hemoglobin'],
    optionsHe: ['קולגן', 'קֶרָטִין (Keratin)', 'אלסטין', 'המוגלובין'],
    answerIndex: 1,
    explanationEn: 'Keratin is a tough, protective fibrous protein that forms structural tissues.',
    explanationHe: 'קרטין הוא חלבון סיבי קשה המגן על השיער, הציפורניים והשכבה החיצונית של העור.'
  },
  {
    id: 'gk-13-24',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which island nation is poetically referred to as "The Land of the Rising Sun"?',
    questionHe: 'אֵיזוֹ מְדִינַת אִיִּים מְכֻנָּה בְּאֹפֶן פִּיּוּטִי "אֶרֶץ הַשֶּׁמֶשׁ הָעוֹלָה"?',
    optionsEn: ['Japan', 'Iceland', 'Madagascar', 'New Zealand'],
    optionsHe: ['יַפָּן', 'איסלנד', 'מדגסקר', 'ניו זילנד'],
    answerIndex: 0,
    explanationEn: 'The name Japan (Nihon) literally translates to "sun origin," which is why it has this nickname.',
    explanationHe: 'פירוש השם יפן בשפת המקור הוא מקור השמש, ולכן היא מכונה ארץ השמש העולה.'
  },
  {
    id: 'gk-13-25',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Who is the author of the internationally bestselling "Harry Potter" book series?',
    questionHe: 'מִי הַסּוֹפֶרֶת שֶׁכָּתְבָה אֶת סִדְרַת סִפְרֵי הַפַנְטַזְיָה הַמַּצְלִיחָה "הָארִי פּוֹטֶר"?',
    optionsEn: ['J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'Stephen King'],
    optionsHe: ['טולקין', 'ק.ס. לואיס', 'ג׳יי קיי רוֹלִינְג (J.K. Rowling)', 'סטיבן קינג'],
    answerIndex: 2,
    explanationEn: 'J.K. Rowling conceived the idea on a delayed train journey in 1990 and went on to write seven books.',
    explanationHe: 'ג׳יי קיי רולינג הבריטית הגתה את הרעיון לרכבת להוגוורטס וכתבה שבעה ספרים.'
  },
  {
    id: 'gk-13-26',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the name of the tallest uninterrupted waterfall in the world?',
    questionHe: 'מַהוּ שְׁמוֹ שֶׁל מַפַּל הַמַּיִם הַגָּבוֹהַּ בָּעוֹלָם?',
    optionsEn: ['Niagara Falls', 'Victoria Falls', 'Angel Falls', 'Iguazu Falls'],
    optionsHe: ['מפלי ניאגרה', 'מפלי ויקטוריה', 'מַפְּלֵי אֶנְגֶ׳ל (מפלי המלאך)', 'מפלי איגואסו'],
    answerIndex: 2,
    explanationEn: 'Angel Falls in Venezuela has a height of 979 meters, dropping from a tabletop mountain.',
    explanationHe: 'מפלי אנג׳ל בוונצואלה הם הגבוהים בעולם, בגובה מדהים של 979 מטרים.'
  },
  {
    id: 'gk-13-27',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which subatomic particle orbits the atomic nucleus and has a negative charge?',
    questionHe: 'אֵיזֶה חֶלְקִיק תַּת-אָטוֹמִי מַקִּיף אֶת גַּרְעִין הָאָטוֹם וּמַחֲזִיק בְּמִטְעָן חַשְׁמַלִּי שְׁלִילִי?',
    optionsEn: ['Proton', 'Neutron', 'Electron', 'Quark'],
    optionsHe: ['פרוטון', 'ניוטרון', 'אֶלֶקְטְרוֹן', 'קווארק'],
    answerIndex: 2,
    explanationEn: 'Electrons orbit the nucleus in specific energy clouds, balancing the positive charge of protons.',
    explanationHe: 'אלקטרון הוא חלקיק זעיר בעל מטען שלילי המקיף את גרעין האטום.'
  },
  {
    id: 'gk-13-28',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the capital city of Brazil?',
    questionHe: 'מָהִי עִיר הַבִּירָה שֶׁל בְּרָזִיל?',
    optionsEn: ['Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador'],
    optionsHe: ['ריו דה ז׳נרו', 'סאו פאולו', 'בְּרָזִילְיָה', 'סלבדור'],
    answerIndex: 2,
    explanationEn: 'Brasilia is a planned city, inaugurated in 1960 to move the capital inland from Rio de Janeiro.',
    explanationHe: 'ברזיליה היא עיר מתוכננת שהוקמה ב-1960 כדי להעביר את הבירה מריו דה ז׳נרו לפנים המדינה.'
  },
  {
    id: 'gk-13-29',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which peace treaty officially ended World War I in the year 1919?',
    questionHe: 'אֵיזֶה חוֹזֶה שָׁלוֹם סִיֵּם רִשְׁמִית אֶת מִלְחֶמֶת הָעוֹלָם הָרִאשׁוֹנָה בִּשְׁנַת 1919?',
    optionsEn: ['Treaty of Versailles', 'Treaty of Ghent', 'Treaty of Utrecht', 'Treaty of Westphalia'],
    optionsHe: ['חוֹזֶה וֶרְסַאי', 'הסכם גנט', 'הסכם אוטרכט', 'שלום וסטפאליה'],
    answerIndex: 0,
    explanationEn: 'The Treaty of Versailles was signed in Paris exactly five years after the assassination of Archduke Franz Ferdinand.',
    explanationHe: 'חוזה ורסאי נחתם בפריז ב-1919 וקבע את תנאי השלום והסנקציות על גרמניה.'
  },
  {
    id: 'gk-13-30',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'In geometry, how many degrees are contained within a perfectly straight line?',
    questionHe: 'בְּגֵאוֹמֶטְרִיָּה, כַּמָּה מַעֲלוֹת יֵשׁ בְּקַו יָשָׁר אָרֹךְ וּשְׁטוּחַ?',
    optionsEn: ['90 degrees', '180 degrees', '360 degrees', '270 degrees'],
    optionsHe: ['90 מעלות', '180 מַעֲלוֹת', '360 מעלות', '270 מעלות'],
    answerIndex: 1,
    explanationEn: 'A straight line represents a straight angle of exactly 180 degrees, which is half of a full circle.',
    explanationHe: 'קו ישר מהווה זווית שטוחה של בדיוק 180 מעלות (חצי סיבוב של מעגל).'
  },
  {
    id: 'gk-13-31',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the name of the largest moon of Saturn, known for its dense atmosphere?',
    questionHe: 'מַהוּ שְׁמוֹ שֶׁל הַיָּרֵחַ הַגָּדוֹל בְּיוֹתֵר שֶׁל שַׁבְּתַאי, הַיָּדוּעַ בָּאַטְמוֹסְפֵירָה הַסְּמִיכָה שֶׁלּוֹ?',
    optionsEn: ['Europa', 'Titan', 'Ganymede', 'Callisto'],
    optionsHe: ['אירופה', 'טִיטָאן (Titan)', 'גנימד', 'קליסטו'],
    answerIndex: 1,
    explanationEn: 'Titan is the second-largest natural satellite in the Solar System and the only moon known to have clouds and liquid lakes.',
    explanationHe: 'טיטאן הוא הירח הגדול ביותר של שבתאי והיחיד במערכת השמש שיש לו אטמוספירה סמיכה ואגמים נוזליים.'
  },
  {
    id: 'gk-13-32',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which scientific instrument is used by geologists to measure and record earthquakes?',
    questionHe: 'בְּאֵיזֶה מַכְשִׁיר מַדָּעִי מִשְׁתַּמְּשִׁים כְּדֵי לִמְדֹּד וּלְתַעֵד רְעִידוֹת אֲדָמָה?',
    optionsEn: ['Barometer', 'Thermometer', 'Seismograph', 'Altimeter'],
    optionsHe: ['ברומטר', 'מדחום', 'סֵיְסְמוֹגְרָף', 'אלטימטר'],
    answerIndex: 2,
    explanationEn: 'A seismograph detects and plots seismic waves produced by earthquakes or volcanic eruptions.',
    explanationHe: 'סיסמוגרף הוא מכשיר רגיש הרושם את גלי הרטט העוברים באדמה בעת רעש אדמה.'
  },
  {
    id: 'gk-13-33',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which famous 18th-century philosopher is widely regarded as the "Father of Modern Economics"?',
    questionHe: 'אֵיזֶה פִילוֹסוֹף סְקוֹטִי בֶּן הַמֵּאָה הַ-18 מְכֻנֶּה "אֲבִי הַכַּלְכָּלָה הַמּוֹדֶרְנִית"?',
    optionsEn: ['Karl Marx', 'John Maynard Keynes', 'Adam Smith', 'David Ricardo'],
    optionsHe: ['קרל מרקס', 'ג׳ון מיינרד קיינס', 'אָדָם סְמִית׳', 'דוד ריקארדו'],
    answerIndex: 2,
    explanationEn: 'Adam Smith wrote "The Wealth of Nations" in 1776, outlining the principles of free-market capitalism.',
    explanationHe: 'אדם סמית׳ כתב את עושר העמים, ספר יסוד המתאר את מנגנון "היד הנעלמה" בכלכלת שוק חופשי.'
  },
  {
    id: 'gk-13-34',
    category: 'Science',
    ageGroup: '13+',
    questionEn: 'Which organelle is known as the powerhouse of the cell?',
    questionHe: 'אֵיזוֹ אַבְרִית בַּתָּא מְכֻנָּה ׳תַּחֲנַת הַכֹּחַ׳ שֶׁל הַתָּא?',
    optionsEn: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi Apparatus'],
    optionsHe: ['גרעין התא', 'מִיטוֹכוֹנְדְּרִיָּה', 'ריבוזום', 'מערכת גולג׳י'],
    answerIndex: 1,
    explanationEn: 'Mitochondria generate most of the cell’s supply of adenosine triphosphate (ATP), used as a source of chemical energy.',
    explanationHe: 'המיטוכונדריה אחראית על הפקת האנרגיה בתא בתהליך של נשימה תאית.'
  },
  {
    id: 'gk-13-35',
    category: 'Math',
    ageGroup: '13+',
    questionEn: 'What is the mathematical derivative of x^2 with respect to x?',
    questionHe: 'מַהוּ הַנִּגְזֶרֶת שֶׁל x^2 לְפִי x?',
    optionsEn: ['x', '2', '2x', 'x^3'],
    optionsHe: ['x', '2', '2x', 'x^3'],
    answerIndex: 2,
    explanationEn: 'According to the Power Rule of calculus, the derivative of x^n is n * x^(n-1). Therefore, the derivative of x^2 is 2x.',
    explanationHe: 'לפי חוקי הגזירה בחשבון דיפרנציאלי, הנגזרת של x בחזקת n היא n כפול x בחזקת (n-1), ולכן הנגזרת של x^2 היא 2x.'
  },
  {
    id: 'gk-13-36',
    category: 'History',
    ageGroup: '13+',
    questionEn: 'Who was the leader of the Soviet Union during World War II?',
    questionHe: 'מִי הָיָה מַנְהִיג בְּרִית הַמּוֹעָצוֹת בִּמְהַלַּךְ מִלְחֶמֶת הָעוֹלָם הַשְּׁנִיָּה?',
    optionsEn: ['Vladimir Lenin', 'Joseph Stalin', 'Nikita Khrushchev', 'Leon Trotsky'],
    optionsHe: ['ולדימיר לנין', 'יוֹסִיף סְטָלִין', 'ניקיטה חרושצ׳וב', 'לאון טרוצקי'],
    answerIndex: 1,
    explanationEn: 'Joseph Stalin led the Soviet Union through the brutal Eastern Front of World War II, playing a key role in defeating Nazi Germany.',
    explanationHe: 'יוסיף סטלין הנהיג את ברית המועצות בשנות מלחמת העולם השנייה והוביל אותה לניצחון על גרמניה הנאצית.'
  },
  {
    id: 'gk-13-37',
    category: 'Geography',
    ageGroup: '13+',
    questionEn: 'What is the deepest known point in the world\'s oceans?',
    questionHe: 'מָהִי הַנְּקֻדָּה הָעֲמֻקָּה בְּיוֹתֵר בְּאוֹקְיָנוּסֵי הָעוֹלָם?',
    optionsEn: ['Puerto Rico Trench', 'Java Trench', 'Mariana Trench', 'Sunda Trench'],
    optionsHe: ['שקע פורטו ריקו', 'שקע ג׳אווה', 'שֶׁקַע מַרְיָאנָה (הצ׳לנג׳ר דיפ)', 'שקע סונדה'],
    answerIndex: 2,
    explanationEn: 'The Challenger Deep in the Mariana Trench is the deepest point on Earth, reaching nearly 11,000 meters below sea level.',
    explanationHe: 'שקע מריאנה באוקיינוס השקט מכיל את הנקודה העמוקה ביותר בכדור הארץ, המגיעה לעומק של כמעט 11 קילומטרים.'
  },
  {
    id: 'gk-13-38',
    category: 'Animals',
    ageGroup: '13+',
    questionEn: 'Which marine animal has three hearts and blue copper-based blood?',
    questionHe: 'לְאֵיזֶה בַּעַל חַיִּים יַמִּי יֵשׁ שְׁלוֹשָׁה לְבָבוֹת וְדָם כָּחֹל מבוסס נחושת?',
    optionsEn: ['Great White Shark', 'Octopus', 'Dolphin', 'Blue Whale'],
    optionsHe: ['כריש לבן', 'תְּמָנוּן', 'דולפין', 'לווייתן כחול'],
    answerIndex: 1,
    explanationEn: 'Octopuses have three hearts (two to pump blood to the gills, one for the body) and use hemocyanin, making their blood blue!',
    explanationHe: 'לתמנונים יש שלושה לבבות ודמם כחול כיוון שהחמצן מובל אצלם על ידי חלבון המכיל נחושת (המוציאנין) במקום ברזל.'
  },
  {
    id: 'gk-13-39',
    category: 'Space',
    ageGroup: '13+',
    questionEn: 'What is the name of the boundary surrounding a black hole beyond which nothing can escape?',
    questionHe: 'אֵיךְ נִקְרָא הַגְּבוּל הַמַּקִּיף חֹר שָׁחֹר שֶׁמִּמֶּנּוּ דָּבָר אֵינוֹ יָכוֹל לְהִמָּלֵט?',
    optionsEn: ['Singularity', 'Event Horizon', 'Ergosphere', 'Accretion Disk'],
    optionsHe: ['סינגולריות', 'אֹפֶק הָאֵרוּעִים (Event Horizon)', 'ארגוספירה', 'דיסקת ספיחה'],
    answerIndex: 1,
    explanationEn: 'The event horizon is the physical threshold where the escape velocity of the black hole exceeds the speed of light.',
    explanationHe: 'אופק האירועים הוא "נקודת האל-חזור" מסביב לחור שחור. חציית גבול זה דורשת מהירות מילוט הגבוהה ממהירות האור.'
  },
  {
    id: 'gk-13-40',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which classic Greek epic poem describes the journey of Odysseus home from the Trojan War?',
    questionHe: 'אֵיזוֹ שִׁירָה אֵפִּית יוּוָנִית עַתִּיקָה מְתָאֶרֶת אֶת מַסָּעוֹ שֶׁל אוֹדִיסֵאוּס הַבַּיְתָה מִמִּלְחֶמֶת טְרוֹיָה?',
    optionsEn: ['The Iliad', 'The Odyssey', 'The Aeneid', 'The Metamorphoses'],
    optionsHe: ['האיליאדה', 'הָאוֹדִיסֵאָה', 'האיניאדה', 'מטמורפוזות'],
    answerIndex: 1,
    explanationEn: 'The Odyssey, attributed to Homer, tells the story of Odysseus’ ten-year journey home filled with sirens, monsters, and gods.',
    explanationHe: 'האודיסאה, המיוחסת למשורר הומרוס, מגוללת את הרפתקאותיו של אודיסאוס בדרכו הביתה שנמשכה עשר שנים.'
  },
  {
    id: 'gk-13-41',
    category: 'Science',
    ageGroup: '13+',
    questionEn: 'What is the most abundant gas in Earth\'s atmosphere?',
    questionHe: 'מַהוּ הַגָּז הַשָּׁכִיחַ וְהַנָּפוֹץ בְּיוֹתֵר בָּאַטְמוֹסְפֵירָה שֶׁל כַּדּוּר הָאָרֶץ?',
    optionsEn: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
    optionsHe: ['חמצן', 'פחמן דו-חמצני', 'חַנְקָן', 'ארגון'],
    answerIndex: 2,
    explanationEn: 'Nitrogen makes up approximately 78% of Earth’s atmosphere, while oxygen accounts for about 21%.',
    explanationHe: 'החנקן מהווה כ-78% מהאטמוספירה של כדור הארץ, בעוד החמצן מהווה כ-21% בלבד.'
  },
  {
    id: 'gk-13-42',
    category: 'Math',
    ageGroup: '13+',
    questionEn: 'What is the sum of internal angles in a regular hexagon?',
    questionHe: 'מַהוּ סְכוּם הַזָּוִיּוֹת הַפְּנִימִיּוֹת בְּמִשֻׁשֶּׁה תַּקִּין?',
    optionsEn: ['360 degrees', '540 degrees', '720 degrees', '900 degrees'],
    optionsHe: ['360 מעלות', '540 מעלות', '720 מַעֲלוֹת', '900 מעלות'],
    answerIndex: 2,
    explanationEn: 'The sum of angles is calculated as (n-2) * 180. For a hexagon (6 sides): (6-2) * 180 = 4 * 180 = 720 degrees.',
    explanationHe: 'נוסחת סכום הזוויות היא (n-2) כפול 180 מעלות. עבור משושה (6 צלעות): 4 כפול 180 שווה ל-720 מעלות.'
  },
  {
    id: 'gk-13-43',
    category: 'History',
    ageGroup: '13+',
    questionEn: 'In which year did the Berlin Wall fall, leading to the reunification of Germany?',
    questionHe: 'בְּאֵיזוֹ שָׁנָה נָפְלָה חוֹמַת בֶּרְלִין, מַה שֶּׁהוֹבִיל לְאִחוּד גֶּרְמַנְיָה מֵחָדָשׁ?',
    optionsEn: ['1985', '1989', '1991', '1993'],
    optionsHe: ['1985', '1989', '1991', '1993'],
    answerIndex: 1,
    explanationEn: 'The Berlin Wall fell on November 9, 1989, symbolizing the collapse of iron curtain division across Europe.',
    explanationHe: 'חומת ברלין נפלה ב-9 בנובמבר 1989, מה שסימן את קץ המלחמה הקרה וסלל את הדרך לאיחוד גרמניה.'
  },
  {
    id: 'gk-13-44',
    category: 'Geography',
    ageGroup: '13+',
    questionEn: 'Which landlocked country is entirely surrounded by South Africa?',
    questionHe: 'אֵיזוֹ מְדִינָה לְלֹא מוֹצָא לַיָּם מֻקֶּפֶת כֻּלָּהּ עַל יְדֵי דְּרוֹם אָפְרִיקָה?',
    optionsEn: ['Swaziland (Eswatini)', 'Lesotho', 'Botswana', 'Namibia'],
    optionsHe: ['סוואזילנד', 'לֶסוֹטוֹ (Lesotho)', 'בוטסואנה', 'נמיביה'],
    answerIndex: 1,
    explanationEn: 'Lesotho is an independent enclaved nation high in the mountains, completely surrounded by South Africa.',
    explanationHe: 'לסוטו היא מדינה עצמאית שהיא מובלעת הררית בתוך שטחה של דרום אפריקה.'
  },
  {
    id: 'gk-13-45',
    category: 'Animals',
    ageGroup: '13+',
    questionEn: 'Which snake is the longest venomous snake in the world?',
    questionHe: 'אֵיזֶה נָחָשׁ הוּא הַנָּחָשׁ הָאַרְסִי הָאָרֹךְ בְּיוֹתֵר בָּעוֹלָם?',
    optionsEn: ['Black Mamba', 'Inland Taipan', 'King Cobra', 'Reticulated Python'],
    optionsHe: ['ממבה שחורה', 'טאיפן פנים-יבשתי', 'רַב-פֶּתֶן מַלְכוּתִי (קִינְג קוֹבְרָה)', 'פיתון מרושת'],
    answerIndex: 2,
    explanationEn: 'The King Cobra can reach lengths of up to 5.5 meters, preying primarily on other snakes.',
    explanationHe: 'רב-פתן מלכותי הוא הנחש הארסי הארוך ביותר בעולם, ויכול להגיע לאורך של מעל 5 מטרים.'
  },
  {
    id: 'gk-13-46',
    category: 'Space',
    ageGroup: '13+',
    questionEn: 'Which planet has the shortest day in our solar system, rotating once in about 10 hours?',
    questionHe: 'לְאֵיזֶה כּוֹכַב לֶכֶת יֵשׁ אֶת הַיּוֹם הַקָּצָר בְּיוֹתֵר בְּמַעֲרֶכֶת הַשֶּׁמֶשׁ?',
    optionsEn: ['Jupiter', 'Saturn', 'Uranus', 'Mars'],
    optionsHe: ['צֶדֶק (יופיטר)', 'שבתאי', 'אורנוס', 'מאדים'],
    answerIndex: 0,
    explanationEn: 'Jupiter spins extremely fast on its axis, completing one rotation (a Jovian day) in just 9 hours and 56 minutes.',
    explanationHe: 'צדק הוא כוכב הלכת המסתובב המהיר ביותר במערכת השמש, ויומו נמשך פחות מ-10 שעות.'
  },
  {
    id: 'gk-13-47',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Who painted the famous masterpiece "The Starry Night"?',
    questionHe: 'מִי צִיֵּר אֶת יְצִירַת הַמּוֹפֵת הַמְּפֻרְסֶמֶת ׳לֵיל כּוֹכָבִים׳?',
    optionsEn: ['Pablo Picasso', 'Leonardo da Vinci', 'Vincent van Gogh', 'Claude Monet'],
    optionsHe: ['פבלו פיקאסו', 'לאונרדו דה וינצ׳י', 'וִינְסֶנְט וַאן גּוֹךְ', 'קלוד מונה'],
    answerIndex: 2,
    explanationEn: 'Vincent van Gogh painted "The Starry Night" in 1889 from his room in the asylum of Saint-Rémy-de-Provence.',
    explanationHe: 'וינסנט ואן גוך צייר את ליל כוכבים בצרפת בשנת 1889, והוא אחד הציורים המוכרים ביותר בעולם.'
  },
  {
    id: 'gk-13-48',
    category: 'Science',
    ageGroup: '13+',
    questionEn: 'What is the chemical formula for table salt?',
    questionHe: 'מַהוּ הַנֻּסְחָה הַכִּימִית שֶׁל מֶלַח שֻׁלְחָן?',
    optionsEn: ['H2O', 'CO2', 'NaCl', 'NaHCO3'],
    optionsHe: ['H2O', 'CO2', 'NaCl', 'NaHCO3'],
    answerIndex: 2,
    explanationEn: 'Table salt is composed of sodium and chlorine ions, scientifically named Sodium Chloride (NaCl).',
    explanationHe: 'מלח שולחן הוא תרכובת יונית המורכבת מנתרן וכלור ונוסחתה NaCl.'
  },
  {
    id: 'gk-13-49',
    category: 'Math',
    ageGroup: '13+',
    questionEn: 'What is the value of log10(1000)?',
    questionHe: 'מַהוּ הָעֵרֶךְ שֶׁל הַלּוֹגָרִיתְם בִּבְסִיס 10 שֶׁל 1000?',
    optionsEn: ['2', '3', '4', '10'],
    optionsHe: ['2', '3', '4', '10'],
    answerIndex: 1,
    explanationEn: 'Since 10 raised to the power of 3 equals 1000, log10(1000) is exactly 3.',
    explanationHe: 'הלוגריתם בבסיס 10 מייצג את החזקה שבה יש להעלות את 10 כדי לקבל את המספר. מאחר ש-10 בחזקת 3 שווה ל-1000, התשובה היא 3.'
  },
  {
    id: 'gk-13-50',
    category: 'History',
    ageGroup: '13+',
    questionEn: 'Who was the first female Prime Minister of the United Kingdom?',
    questionHe: 'מִי הָיְתָה רֹאשׁ הַמֶּמְשָׁלָה הָאִשָּׁה הָרִאשׁוֹנָה שֶׁל הַמַּמְלָכָה הַמְּאֻחֶדֶת?',
    optionsEn: ['Theresa May', 'Margaret Thatcher', 'Queen Victoria', 'Angela Merkel'],
    optionsHe: ['תרזה מיי', 'מַרְגָּרֶט תָּאצֵ׳ר', 'המלכה ויקטוריה', 'אנגלה מרקל'],
    answerIndex: 1,
    explanationEn: 'Margaret Thatcher, known as the "Iron Lady", served as UK Prime Minister from 1797 until her resignation in 1990.',
    explanationHe: 'מרגרט תאצ׳ר המכונה "אשת הברזל" כיהנה כראש ממשלת בריטניה בין השנים 1979 ל-1990.'
  },
  {
    id: 'gk-13-51',
    category: 'Geography',
    ageGroup: '13+',
    questionEn: 'Which is the smallest country in the world by land area?',
    questionHe: 'מָהִי הַמְּדִינָה הַקְּטַנָּה בְּיוֹתֵר בָּעוֹלָם בְּשִׁטְחָהּ?',
    optionsEn: ['Monaco', 'Malta', 'Vatican City', 'San Marino'],
    optionsHe: ['מונאקו', 'מלטה', 'קִרְיַת הַוָּתִיקָן', 'סן מרינו'],
    answerIndex: 2,
    explanationEn: 'Vatican City is an independent city-state enclaved within Rome, Italy, covering just 0.49 square kilometers.',
    explanationHe: 'קריית הוותיקן היא המדינה העצמאית הקטנה בתבל, השוכנת בלב רומא ושטחה פחות מחצי קילומטר רבוע.'
  },
  {
    id: 'gk-13-52',
    category: 'Animals',
    ageGroup: '13+',
    questionEn: 'What is the species of monotreme mammal famous for laying eggs instead of giving birth?',
    questionHe: 'אֵיזֶה סוּג יוֹנֵק מִסִּדְרַת בַּעֲלֵי בִּיב מְטִיל בֵּיצִים בִּמְקוֹם לָלֶדֶת וָלָדוֹת חַיִּים?',
    optionsEn: ['Kangaroo', 'Platypus', 'Koala', 'Armadillo'],
    optionsHe: ['קנגורו', 'בַּרְוָזָן (פְּלָטִיפּוּס)', 'קואלה', 'ארמדיל'],
    answerIndex: 1,
    explanationEn: 'The platypus and echidna are the only egg-laying mammals (monotremes) left on Earth, native to Australia.',
    explanationHe: 'הברווזן (פלטיפוס) הוא יונק ייחודי המטיל ביצים ומזין את צאצאיו בחלב, הנפוץ במזרח אוסטרליה.'
  },
  {
    id: 'gk-13-53',
    category: 'Space',
    ageGroup: '13+',
    questionEn: 'What is the name of the closest spiral galaxy to our Milky Way?',
    questionHe: 'מַהוּ שְׁמָהּ שֶׁל הַגָּלַקְסִיָּה הַסְּפִּירָלִית הַקְּרוֹבָה בְּיוֹתֵר לִשְׁבִיל הַחָלָב שֶׁלָּנוּ?',
    optionsEn: ['Andromeda', 'Triangulum', 'Large Magellanic Cloud', 'Whirlpool Galaxy'],
    optionsHe: ['אַנְדְרוֹמֶדָה (Andromeda)', 'משולש', 'ענן מגלן הגדול', 'גלקסיית המערבולת'],
    answerIndex: 0,
    explanationEn: 'The Andromeda Galaxy is about 2.5 million light-years from Earth and is on a collision course with the Milky Way in 4.5 billion years.',
    explanationHe: 'גלקסיית אנדרומדה היא הגלקסיה הספירלית הגדולה הקרובה ביותר אלינו, במרחק של כ-2.5 מיליון שנות אור.'
  },
  {
    id: 'gk-13-54',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which standard musical instrument has 88 keys?',
    questionHe: 'לְאֵיזֶה כְּלִי נְגִינָה מַקִּישׁ יֵשׁ בְּדֶרֶךְ כְּלָל 88 קְלִידִים?',
    optionsEn: ['Accordion', 'Harpsichord', 'Piano', 'Organ'],
    optionsHe: ['אקורדיון', 'צ׳מבלו', 'פְּסַנְתֵּר', 'עוגב'],
    answerIndex: 2,
    explanationEn: 'A standard piano has 88 keys: 52 white keys (naturals) and 36 black keys (accidentals).',
    explanationHe: 'פסנתר כנף סטנדרטי כולל 88 קלידים (52 לבנים ו-36 שחורים) המכסים שבע אוקטבות פלוס קטע קטן.'
  },
  {
    id: 'gk-13-55',
    category: 'Science',
    ageGroup: '13+',
    questionEn: 'Which fundamental force keeps atomic nuclei held together?',
    questionHe: 'אֵיזֶה כֹּחַ יְסוֹדִי מַחֲזִיק אֶת גַּלְעִין הָאָטוֹם מְלֻכָּד יַחְדָּו?',
    optionsEn: ['Electromagnetic Force', 'Weak Nuclear Force', 'Strong Nuclear Force', 'Gravitational Force'],
    optionsHe: ['הכוח האלקטרומגנטי', 'הכוח הגרעיני החלש', 'הַכֹּחַ הַגַּרְעִינִי הֶחָזָק', 'כוח הכבידה'],
    answerIndex: 2,
    explanationEn: 'The strong nuclear force overcomes electromagnetic repulsion to bind protons and neutrons together inside the nucleus.',
    explanationHe: 'הכוח הגרעיני החזק הוא הכוח העוצמתי ביותר בטבע המלכד פרוטונים ונייטרונים בגרעין האטום.'
  },
  {
    id: 'gk-13-56',
    category: 'Math',
    ageGroup: '13+',
    questionEn: 'In trigonometry, what is the sine of 90 degrees?',
    questionHe: 'בִּטְרִיגוֹנוֹמֶטְרִיָּה, מַהוּ הַסִּינוּס שֶׁל 90 מַעֲלוֹת?',
    optionsEn: ['0', '0.5', '1', '-1'],
    optionsHe: ['0', '0.5', '1', '-1'],
    answerIndex: 2,
    explanationEn: 'The sine of 90 degrees (or pi/2 radians) represents the maximum vertical value on a unit circle, which is exactly 1.',
    explanationHe: 'במעגל היחידה, ערך ה-y בזווית של 90 מעלות הוא בנקודה הגבוהה ביותר ולכן סינוס 90 שווה ל-1.'
  },
  {
    id: 'gk-13-57',
    category: 'History',
    ageGroup: '13+',
    questionEn: 'In which city was the Archduke Franz Ferdinand assassinated, sparking World War I?',
    questionHe: 'בְּאֵיזוֹ עִיר נִרְצַח הָאַרְכִידוּכָס פְרַנְץ פֶרְדִּינַנְד, מַה שֶּׁהִצִּית אֶת מִלְחֶמֶת הָעוֹלָם הָרִאשׁוֹנָה?',
    optionsEn: ['Vienna', 'Sarajevo', 'Budapest', 'Belgrade'],
    optionsHe: ['וינה', 'סָרָיֶבִוֹ (Sarajevo)', 'בודפשט', 'בלגרד'],
    answerIndex: 1,
    explanationEn: 'Franz Ferdinand was assassinated in Sarajevo on June 28, 1914, by Gavrilo Princip, leading to diplomatic escalation.',
    explanationHe: 'התנקשות בארכידוכס האוסטרי בסרייבו ביוני 1914 הציתה שרשרת בריתות שהובילה למלחמת העולם הראשונה.'
  },
  {
    id: 'gk-13-58',
    category: 'Geography',
    ageGroup: '13+',
    questionEn: 'Which mountain range separates Europe and Asia?',
    questionHe: 'אֵיזֶה רֶכֶס הָרִים מַפְרִיד בֵּין אֵירוֹפָּה לְאַסְיָה?',
    optionsEn: ['Alps', 'Ural Mountains', 'Himalayas', 'Pyrenees'],
    optionsHe: ['האלפים', 'הָרֵי אוּרָל', 'הימלאיה', 'הפירנאים'],
    answerIndex: 1,
    explanationEn: 'The Ural Mountains run from north to south through western Russia, acting as a traditional continental boundary.',
    explanationHe: 'הרי אוראל ברוסיה מהווים את הגבול הגאוגרפי והגאולוגי המקובל בין יבשות אירופה ואסיה.'
  },
  {
    id: 'gk-13-59',
    category: 'Animals',
    ageGroup: '13+',
    questionEn: 'Which animal is the largest living species of bird?',
    questionHe: 'מַהוּ מִין הַצִּפּוֹר הַגָּדוֹל בְּיוֹתֵר שֶׁחַי כַּיּוֹם בָּעוֹלָם?',
    optionsEn: ['Emperor Penguin', 'Ostrich', 'Andean Condor', 'Wandering Albatross'],
    optionsHe: ['פינגווין קיסרי', 'יַעֲנָה (בת יענה)', 'קונדור האנדים', 'אלבטרוס נודד'],
    answerIndex: 1,
    explanationEn: 'The Ostrich is the largest and heaviest living bird, native to Africa; it cannot fly but can run up to 70 km/h.',
    explanationHe: 'היענה היא הציפור הגדולה והכבד ביותר כיום, והיא מסוגלת לרוץ במהירויות של עד 70 קמ״ש.'
  },
  {
    id: 'gk-13-60',
    category: 'Space',
    ageGroup: '13+',
    questionEn: 'What is the primary element that makes up the Sun?',
    questionHe: 'מַהוּ הַיְּסוֹד הָרָאשִׁי מִמֶּנּוּ עָשׂוּי כּוֹכָב הַשֶּׁמֶשׁ?',
    optionsEn: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'],
    optionsHe: ['הליום', 'חמצן', 'מֵימָן (Hydrogen)', 'פחמן'],
    answerIndex: 2,
    explanationEn: 'The Sun consists of about 74% hydrogen, 24% helium, and trace amounts of heavier elements like oxygen and iron.',
    explanationHe: 'השמש מורכבת בעיקר ממימן (כ-74%) המעניק לה חומר דלק לתהליך ההיתוך הגרעיני שמפיק את קרינתה.'
  },
  {
    id: 'gk-13-61',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which playwright wrote the tragedy "Hamlet"?',
    questionHe: 'אֵיזֶה מַחֲזַאי כָּתַב אֶת הַטְּרָגֶדְיָה הַמְּפֻרְסֶמֶת ׳הַמְלֶט׳?',
    optionsEn: ['Christopher Marlowe', 'William Shakespeare', 'John Milton', 'Oscar Wilde'],
    optionsHe: ['כריסטופר מרלו', 'וִילְיָאם שֵׁקְסְפִּיר', 'ג׳ון מילטון', 'אוסקר ויילד'],
    answerIndex: 1,
    explanationEn: 'William Shakespeare wrote Hamlet between 1599 and 1601, featuring the famous soliloquy "To be, or not to be".',
    explanationHe: 'ויליאם שקספיר כתב את מחזה הטרגדיה המפורסם המלט בלונדון בסביבות שנת 1600.'
  },
  {
    id: 'gk-13-62',
    category: 'Science',
    ageGroup: '13+',
    questionEn: 'What is the pH level of pure distilled water at room temperature?',
    questionHe: 'מַהוּ רָמַת הַ-pH שֶׁל מַיִם מְזֻקָּקִים בְּטֶמְפֶּרָטוּרַת הַחֶדֶר?',
    optionsEn: ['5', '6', '7', '8'],
    optionsHe: ['5', '6', '7', '8'],
    answerIndex: 2,
    explanationEn: 'Pure water is completely neutral on the pH scale, having a value of exactly 7.0.',
    explanationHe: 'מדד pH של מים מזוקקים הוא ניטרלי לחלוטין ועומד על בדיוק 7.0.'
  },
  {
    id: 'gk-13-63',
    category: 'Math',
    ageGroup: '13+',
    questionEn: 'What is the volume formula of a cylinder with radius r and height h?',
    questionHe: 'מַהוּ נֶפַח גְּלִיל שֶׁרַדְיוּסוֹ r וְגוֹבְהוֹ h?',
    optionsEn: ['pi * r * h', '2 * pi * r * h', 'pi * r^2 * h', '1/3 * pi * r^2 * h'],
    optionsHe: ['pi * r * h', '2 * pi * r * h', 'pi * r^2 * h', '1/3 * pi * r^2 * h'],
    answerIndex: 2,
    explanationEn: 'The volume is the cross-sectional area of the circle (pi * r^2) multiplied by the height (h).',
    explanationHe: 'נפח גליל מחושב על ידי הכפלת שטח מעגל הבסיס (פאי כפול רדיוס בריבוע) בגובה הגליל.'
  },
  {
    id: 'gk-13-64',
    category: 'History',
    ageGroup: '13+',
    questionEn: 'Who was the first human to travel into outer space in 1961?',
    questionHe: 'מִי הָיָה בֶּן הָאָדָם הָרִאשׁוֹן שֶׁטָּס לֶחָלָל הַחִיצוֹנִי בִּשְׁנַת 1961?',
    optionsEn: ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'John Glenn'],
    optionsHe: ['ניל ארמסטרונג', 'יוּרִי גָאגָארִין', 'באז אולדרין', 'ג׳ון גלן'],
    answerIndex: 1,
    explanationEn: 'Soviet cosmonaut Yuri Gagarin orbited the Earth in the Vostok 1 spacecraft on April 12, 1961.',
    explanationHe: 'יורי גגארין הקוסמונאוט הסובייטי היה האדם הראשון בחלל, והשלים הקפה של כדור הארץ ב-1961.'
  },
  {
    id: 'gk-13-65',
    category: 'Geography',
    ageGroup: '13+',
    questionEn: 'What is the capital city of Turkey?',
    questionHe: 'מָהִי עִיר הַבִּירָה שֶׁל תּוּרְכִּיָּה?',
    optionsEn: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
    optionsHe: ['איסטנבול', 'אַנְקָרָה (Ankara)', 'איזמיר', 'אנטליה'],
    answerIndex: 1,
    explanationEn: 'While Istanbul is Turkey\'s largest city and historical hub, Ankara was selected as the capital in 1923 by Ataturk.',
    explanationHe: 'אנקרה היא בירת טורקיה הרשמית מאז הקמת הרפובליקה ב-1923, למרות שאיסטנבול היא העיר הגדולה ביותר.'
  },
  {
    id: 'gk-13-66',
    category: 'Animals',
    ageGroup: '13+',
    questionEn: 'What is the correct term for a social group of lions?',
    questionHe: 'אֵיךְ נִקְרָאת קְבוּצָה חֶבְרָתִית שֶׁל אֲרָיוֹת?',
    optionsEn: ['Pack', 'Herd', 'Pride', 'Flock'],
    optionsHe: ['להקה (Pack)', 'עדר', 'לַהֲקַת אֲרָיוֹת (Pride)', 'להקה (Flock)'],
    answerIndex: 2,
    explanationEn: 'A pride of lions typically consists of related females, their offspring, and a small coalition of breeding males.',
    explanationHe: 'קבוצה של אריות נקראת באנגלית "Pride" (להקת אריות), והיא מבוססת לרוב על קשרי משפחה בין לביאות.'
  },
  {
    id: 'gk-13-67',
    category: 'Space',
    ageGroup: '13+',
    questionEn: 'What planet is closest in size and mass to Earth, often called its sister planet?',
    questionHe: 'אֵיזֶה כּוֹכַב לֶכֶת הוּא הַקָּרוֹב בְּיוֹתֵר בְּגָדְלוֹ וּמַסָּתוֹ לְכַדּוּר הָאָרֶץ?',
    optionsEn: ['Mars', 'Venus', 'Mercury', 'Uranus'],
    optionsHe: ['מאדים', 'נוֹגַהּ (Venus)', 'מרקורי', 'אורנוס'],
    answerIndex: 1,
    explanationEn: 'Venus shares a very similar size, density, and mass to Earth, although its runaway greenhouse effect makes it extremely hostile.',
    explanationHe: 'כוכב הלכת נוגה קרוב מאוד בממדיו לכדור הארץ, אך האטמוספירה הסמיכה שלו יוצרת אפקט חממה קיצוני.'
  },
  {
    id: 'gk-13-68',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Which scientist formulated the laws of motion and universal gravitation in the 17th century?',
    questionHe: 'אֵיזֶה מַדָּעָן נִסַּח אֶת חֻקֵּי הַתְּנוּעָה וְכֹחַ הַכְּבִידָה הָעוֹלָמִי בַּמֵּאָה הַ-17?',
    optionsEn: ['Galileo Galilei', 'Isaac Newton', 'Albert Einstein', 'Johannes Kepler'],
    optionsHe: ['גלילאו גליליי', 'אַיְיזֶק נְיוּטוֹן (Isaac Newton)', 'אלברט איינשטיין', 'יוהאנס קפלר'],
    answerIndex: 1,
    explanationEn: 'Sir Isaac Newton published his "Principia" in 1687, laying the foundation for classical mechanics and calculus.',
    explanationHe: 'אייזק ניוטון תיאר את חוקי התנועה וכוח המשיכה בספרו המפורסם פרינציפיה ב-1687.'
  },
  {
    id: 'gk-13-visual-traffic',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Look at the triangular warning sign! What is this sign alerting drivers about?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הַמְשֻׁלָּשׁ! עַל מָה מַזְהִיר תַּמְרוּר זֶה אֶת הַנְּהָגִים?',
    optionsEn: ['Traffic light ahead', 'Stop sign ahead', 'No vehicles allowed', 'Construction zone ahead'],
    optionsHe: ['רַמְזוֹר לְפָנֶיךָ', 'תַּמְרוּר עֲצֹר לְפָנֶיךָ', 'אֵין כְּנִיסָה לִכְלִי רֶכֶב', 'עֲבוֹדוֹת בַּכְּבִישׁ לְפָנֶיךָ'],
    answerIndex: 0,
    explanationEn: 'The warning triangle containing a miniature traffic light alerts drivers to prepare for a signalized intersection ahead.',
    explanationHe: 'תמרור משולש לבן עם שוליים אדומים ובו סמל רמזור מזהיר את הנהגים מפני רמזור הממוקם בהמשך הדרך.',
    visualType: 'traffic-light-sign'
  },
  {
    id: 'gk-13-visual-yield',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What action is required when encountering this inverted red and white triangle?',
    questionHe: 'אֵיזוֹ פְּעֻלָּה נִדְרֶשֶׁת מִנָּהָג בְּעֵת הִתְקָרְבוּת לְתַמְרוּר מְשֻׁלָּשׁ הָפוּךְ זֶה?',
    optionsEn: ['Give way (Yield) to other vehicles', 'Stop completely regardless of traffic', 'Increase speed to merge safely', 'Only bicycles must stop'],
    optionsHe: ['תֵּן זְכוּת קָדִימָה לִכְלִי רֶכֶב אֲחֵרִים', 'עֲצֹר עֲצִירָה מֻחְלֶטֶת בְּכָל מִקְרֶה', 'הָגְבֵּר מְהִירוּת כְּדֵי לְהִשְׁתַּלֵּב בְּבִטְחָה', 'רק רוֹכְבֵי אוֹפַנַּיִם חַיָּבִים לַעֲצֹר'],
    answerIndex: 0,
    explanationEn: 'The inverted triangle is the Give Way / Yield sign. You must yield the right of way to vehicles in the intersecting road.',
    explanationHe: 'תמרור משולש הפוך הוא תמרור "תן זכות קדימה". הוא דורש מהנהג לתת זכות קדימה לתנועה החוצה בדרך שלפניו.',
    visualType: 'yield-sign'
  },
  {
    id: 'gk-13-visual-entry',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What is the name and rule of this red circle sign with a horizontal white bar?',
    questionHe: 'מָה שְׁמוֹ וְחֻקּוֹ שֶׁל תַּמְרוּר עָגֹל אָדֹם זֶה עִם הַפַּס הַלָּבָן בַּמֶּרְכָּז?',
    optionsEn: ['No Entry (Entry Forbidden)', 'Stop and turn around', 'One-way street ahead', 'Yield to pedestrians'],
    optionsHe: ['אֵין כְּנִיסָה (הַכְּנִיסָה אֲסוּרָה)', 'עֲצֹר וּפְנֵה לְאָחוֹר', 'רְחוֹב חַד-סִטְרִי לְפָנֶיךָ', 'תֵּן זְכוּת קָדִימָה לְהוֹלְכֵי רֶגֶל'],
    answerIndex: 0,
    explanationEn: 'The red circle with a horizontal white bar is the "No Entry" sign. It forbids entry for all vehicles from that direction.',
    explanationHe: 'עיגול אדום ובו פס לבן אופקי הוא תמרור "אין כניסה". הוא אוסר על כניסת כלי רכב מכל סוג מאותו כיוון.',
    visualType: 'no-entry-sign'
  },
  {
    id: 'gk-13-visual-bike',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'What does this warning sign with a bicycle alert drivers about?',
    questionHe: 'עַל מָה מַזְהִיר תַּמְרוּר מְשֻׁלָּשׁ זֶה הַמֵּכִיל סֵמֶל שֶׁל אוֹפַנַּיִם?',
    optionsEn: ['Bicycle crossing or riders ahead', 'Bicycles are strictly forbidden', 'Bicycle parking only', 'Rental bicycles nearby'],
    optionsHe: ['רוֹכְבֵי אוֹפַנַּיִם חוֹצִים אוֹ נִמְצָאִים בַּדֶּרֶךְ', 'רְכִיבָה עַל אוֹפַנַּיִם אֲסוּרָה בְּהֶחְלֵט', 'חֲנִיַּת אוֹפַנַּיִם בִּלְבַד', 'אוֹפַנַּיִם לְהַשְׂכָּרָה בְּקִרְבַת מָקוֹם'],
    answerIndex: 0,
    explanationEn: 'The warning triangle with a bicycle alerts drivers that bicycle riders are likely crossing or riding on the road ahead.',
    explanationHe: 'תמרור אזהרה משולש ובו אופניים מזהיר את הנהגים כי רוכבי אופניים עשויים לחצות או לנוע בדרך שלפניהם.',
    visualType: 'bicycle-sign'
  },
  {
    id: 'gk-13-story-odyssey',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'In Greek mythology, what clever wooden creation did the Greeks use to enter the city of Troy?',
    questionHe: 'בַּמִּיתוֹלוֹגְיָה הַיְּוָנִית, בְּאֵיזֶה מִבְנֶה עֵץ חָכָם הִשְׁתַּמְּשׁוּ הַיְּוָנִים כְּדֵי לְהִכָּנֵס לָעִיר טְרוֹיָה?',
    optionsEn: ['The Trojan Horse', 'The Trojan Eagle', 'The Wooden Fortress', 'The Giant Labyrinth'],
    optionsHe: ['הַסּוּס הַטְּרוֹיָאנִי', 'הַנֶּשֶׁר הַטְּרוֹיָאנִי', 'מִבְצַר הָעֵץ', 'הַלָּבִירִינְתּ הָעֲנָקִי'],
    answerIndex: 0,
    explanationEn: "The Greeks built a giant wooden horse, hid soldiers inside, and left it as a gift. The Trojans pulled it into the city, leading to Troy's capture!",
    explanationHe: 'היוונים בנו סוס עץ ענקי, החביאו לוחמים בתוכו והשאירו אותו כמתנה. הטרויאנים הכניסו אותו לעיר, מה שהוביל לכיבושה!'
  },
  {
    id: 'gk-13-story-hobbit',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: "In J.R.R. Tolkien's 'The Hobbit', what game do Bilbo Baggins and Gollum play in the dark cave?",
    questionHe: "בְּ'הַהוֹבִּיט' שֶׁל ג'.ר.ר. טוֹלְקִין, בְּאֵיזֶה מִשְׂחָק מְשַׂחֲקִים בִּילְבּוֹ בֶּגִינְס וְגוֹלוּם בַּמְּעָרָה הַחֲשׁוּכָה?",
    optionsEn: ['Riddles in the Dark', 'Chess', 'Hide and Seek', 'Tic-Tac-Toe'],
    optionsHe: ['חִידוֹת בַּאֲפֵלָה', 'שַׁחְמָט', 'מַחְבּוֹאִים', 'איקס עיגול'],
    answerIndex: 0,
    explanationEn: "Bilbo and Gollum engage in a game of riddles. Bilbo wins by asking, 'What have I got in my pocket?'",
    explanationHe: 'בילבו וגולום עורכים תחרות חידות באפלה. בילבו מנצח כשהוא שואל "מה יש לי בכיס?"'
  },
  {
    id: 'gk-13-visual-no-u-turn',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Look at the visual sign with a curved arrow and a red slash! What does it prohibit?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר עִם הַחֵץ הַמְעֻקָּל וְהַקַּו הָאָדֹם הָאלַכְסוֹנִי! מָה הוּא אוֹסֵר?',
    optionsEn: ['U-turns', 'Left turns', 'Right turns', 'Overtaking other cars'],
    optionsHe: ['פְּנִיַּת פַּרְסָה', 'פְּנִיָּה שְׂמֹאלָה', 'פְּנִיָּה יָמִינָה', 'עֲקִיפַת כְּלִי רֶכֶב אֲחֵרִים'],
    answerIndex: 0,
    explanationEn: 'This sign indicates that U-turns are strictly prohibited at this location.',
    explanationHe: 'תמרור זה אוסר על ביצוע פניית פרסה במקום זה.',
    visualType: 'no-u-turn-sign'
  },
  {
    id: 'gk-13-visual-train',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Look at the warning triangle containing a picture of a steam train! What is it alerting you to?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הַמְשֻׁלָּשׁ וּבוֹ סֵמֶל שֶׁל רַכֶּבֶת קִיטוֹר! מִפְּנֵי מָה הוּא מַזְהִיר?',
    optionsEn: ['Railway crossing ahead without barriers', 'Train station nearby', 'Toy train track', 'High-speed rail line'],
    optionsHe: ['מִפְגַּש מְסִילַּת בַּרְזֶל לְפָנֶיךָ לְלֹא מַחְסוֹם', 'תַּחֲנַת רַכֶּבֶת בְּקִרְבַת מָקוֹם', 'מְסִילַּת רַכֶּבֶת צַעֲצוּעַ', 'קַו רַכֶּבֶת מְהִירָה לְפָנֶיךָ'],
    answerIndex: 0,
    explanationEn: 'This sign warns drivers that there is an uncontrolled railway crossing ahead without automatic barriers.',
    explanationHe: 'תמרור זה מזהיר מפני מפגש מסילת ברזל (פסי רכבת) ללא מחסום, ומורה לנהגים להאט ולהסתכל היטב.',
    visualType: 'train-crossing-sign'
  },
  {
    id: 'gk-13-visual-one-way',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Look at the blue rectangular sign with a white arrow pointing up. What does it mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הַכָּחֹל הַמַּלְבְּנִי עִם הַחֵץ הַלָּבָן הַפּוֹנֶה כְּלַפֵי מַעְלָה. מָה מַשְׁמָעוּתוֹ?',
    optionsEn: ['One-way traffic direction', 'No entry allowed', 'Pedestrian zone only', 'Go straight only at intersection'],
    optionsHe: ['כִּוּוּן הַתְּנוּעָה חַד-סִטְרִי', 'אֵין כְּנִיסָה לִכְלִי רֶכֶב', 'מִדְרָחוֹב לְהוֹלְכֵי רֶגֶל בִּלְבַד', 'יָשָׁר בִּלְבַד בַּצֹּמֶת הַקָּרוֹב'],
    answerIndex: 0,
    explanationEn: 'The One-Way traffic sign indicates that vehicles are only allowed to drive in the direction indicated by the arrow.',
    explanationHe: 'תמרור כביש חד-סטרי מסמן לנהגים שכל כלי הרכב רשאים לנסוע אך ורק בכיוון אליו מורה החץ.',
    visualType: 'one-way-sign'
  },
  {
    id: 'gk-13-visual-speed',
    category: 'GeneralKnowledge',
    ageGroup: '13+',
    questionEn: 'Look at the white circular sign with a red border containing the number 50. What is it?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הָעָגֹל הַלָּבָן עִם הַמִּסְגֶּרֶת הָאֲדֻמָּה וְהַמִּסְפָּר 50. מַהוּ?',
    optionsEn: ['Maximum speed limit is 50 km/h', 'Minimum speed limit is 50 km/h', 'Distance to next town is 50 km', 'Maximum weight limit is 50 tons'],
    optionsHe: ['מְהִירוּת מַרְבִּית מֻתֶּרֶת 50 קמ"ש', 'מְהִירוּת מִזְעָרִית מֻתֶּרֶת 50 קמ"ש', 'מֶרְחָק לָעִיר הַקְּרוֹבָה 50 ק"מ', 'הַגְבָּלַת מִשְׁקָל מַרְבִּי 50 טוֹנָה'],
    answerIndex: 0,
    explanationEn: 'The speed limit sign regulates that vehicles must not drive faster than 50 kilometers per hour.',
    explanationHe: 'תמרור הגבלת מהירות מורה לנהגים שאסור לעבור את המהירות המצוינת, במקרה זה - 50 קמ"ש.',
    visualType: 'speed-limit-50-sign'
  }
];
