import { Question } from './types';

export const GK_5_7_QUESTIONS: Question[] = [
  {
    id: 'gk-5-1',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which animal says "Meow"?',
    questionHe: 'אֵיזוֹ חַיָּה אוֹמֶרֶת "מְיָאוּ"?',
    optionsEn: ['Dog', 'Cat', 'Cow', 'Bird'],
    optionsHe: ['כֶּלֶב', 'חָתוּל', 'פָּרָה', 'צִפּוֹר'],
    answerIndex: 1,
    explanationEn: 'Cats meow to communicate with humans!',
    explanationHe: 'חתולים אומרים מיאו כדי לתקשר עם בני אדם!'
  },
  {
    id: 'gk-5-2',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What color are ripe bananas?',
    questionHe: 'בְּאֵיזֶה צֶבֶע בָּנָנוֹת בְּשֵׁלוֹת?',
    optionsEn: ['Red', 'Blue', 'Yellow', 'Green'],
    optionsHe: ['אָדֹם', 'כָּחֹל', 'צָהֹב', 'יָרֹק'],
    answerIndex: 2,
    explanationEn: 'Bananas turn bright yellow when they are ready to eat.',
    explanationHe: 'בננות הופכות לצהובות כשהן מוכנות לאכילה.'
  },
  {
    id: 'gk-5-3',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'How many legs does a spider have?',
    questionHe: 'כַּמָּה רַגְלַיִם יֵשׁ לָעַכָּבִישׁ?',
    optionsEn: ['6', '8', '10', '4'],
    optionsHe: ['6', '8', '10', '4'],
    answerIndex: 1,
    explanationEn: 'All spiders are arachnids and have exactly 8 legs.',
    explanationHe: 'לכל העכבישים יש בדיוק 8 רגליים.'
  },
  {
    id: 'gk-5-4',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do teachers use to write on a green blackboard?',
    questionHe: 'בְּמָה מִשְׁתַּמְּשִׁים כְּדֵי לִכְתֹּב עַל לוּחַ יָרֹק?',
    optionsEn: ['Chalk', 'Pencil', 'Paint', 'Crayon'],
    optionsHe: ['גִּיר', 'עִפָּרוֹן', 'צֶבַע', 'צֶבַע פַּחְם'],
    answerIndex: 0,
    explanationEn: 'Chalk is made of soft limestone and is easy to erase from blackboards.',
    explanationHe: 'גיר עשוי מאבן גיר רכה וקל למחוק אותו מהלוח.'
  },
  {
    id: 'gk-5-5',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which fruit is red, sweet, and has seeds on the outside?',
    questionHe: 'אֵיזֶה פְּרִי הוּא אָדֹם, מָתוֹק וְיֵשׁ לוֹ זְרָעִים מִבַּחוּץ?',
    optionsEn: ['Apple', 'Banana', 'Strawberry', 'Grape'],
    optionsHe: ['תַּפּוּחַ', 'בָּנָנָה', 'תּוּת שָׂדֶה', 'עֵנָב'],
    answerIndex: 2,
    explanationEn: 'Strawberries are the only fruit that wear their seeds on the outside!',
    explanationHe: 'תות שדה הוא הפרי היחיד שהזרעים שלו נמצאים מבחוץ!'
  },
  {
    id: 'gk-5-6',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the opposite of day?',
    questionHe: 'מַהוּ הַהֵפֶךְ מִיוֹם?',
    optionsEn: ['Morning', 'Night', 'Noon', 'Evening'],
    optionsHe: ['בֹּקֶר', 'לַיְלָה', 'צָהֳרַיִם', 'עֶרֶב'],
    answerIndex: 1,
    explanationEn: 'When the sun goes down, it becomes night!',
    explanationHe: 'כשהשמש שוקעת, מגיע הלילה!'
  },
  {
    id: 'gk-5-7',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is ice made of?',
    questionHe: 'מִמָּה עָשׂוּי קֶרַח?',
    optionsEn: ['Milk', 'Water', 'Sugar', 'Juice'],
    optionsHe: ['חָלָב', 'מַיִם', 'סֻכָּר', 'מִיץ'],
    answerIndex: 1,
    explanationEn: 'Ice is just frozen water!',
    explanationHe: 'קרח הוא פשוט מים קפואים!'
  },
  {
    id: 'gk-5-8',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Where do we go to learn and play with friends and teachers?',
    questionHe: 'לְאָן אֲנַחְנוּ הוֹלְכִים כְּדֵי לִלְמֹד וּלְשַׂחֵק עִם חֲבֵרִים וּמוֹרִים?',
    optionsEn: ['Supermarket', 'School', 'Zoo', 'Beach'],
    optionsHe: ['סוּפֶּרְמַרְקֶט', 'בֵּית סֵפֶר', 'גַּן חַיּוֹת', 'חוֹף הַיָּם'],
    answerIndex: 1,
    explanationEn: 'School is a wonderful place to learn new things every day.',
    explanationHe: 'בית ספר הוא מקום נהדר ללמוד דברים חדשים בכל יום.'
  },
  {
    id: 'gk-5-9',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which animal is known as the "King of the Jungle"?',
    questionHe: 'אֵיזוֹ חַיָּה יְדוּעָה כְּ-"מֶלֶךְ הַגּ׳וּנְגֶּל"?',
    optionsEn: ['Tiger', 'Lion', 'Elephant', 'Monkey'],
    optionsHe: ['טִיגְרִיס', 'אַרְיֵה', 'פִּיל', 'קוֹף'],
    answerIndex: 1,
    explanationEn: 'Lions are called the King of the Jungle because of their strength and majestic mane!',
    explanationHe: 'האריה מכונה מלך החיות בגלל כוחו ורעמתו המרשימה!'
  },
  {
    id: 'gk-5-10',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What shape is a traditional slice of pizza?',
    questionHe: 'אֵיזֶה צוּרָה יֵשׁ לִפְרוּסַת פִּיצָה רְגִילָה?',
    optionsEn: ['Square', 'Circle', 'Triangle', 'Star'],
    optionsHe: ['רִיבּוּעַ', 'עִגּוּל', 'מְשֻׁלָּשׁ', 'כּוֹכָב'],
    answerIndex: 2,
    explanationEn: 'A round pizza is usually cut into triangle slices.',
    explanationHe: 'פיצה עגולה נחתכת בדרך כלל לפרוסות משולשות.'
  },
  {
    id: 'gk-5-11',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the color of most tree leaves in the summer?',
    questionHe: 'מַהוּ הַצֶּבֶע שֶׁל רוֹב עֲלֵי הָעֵצִים בַּקַּיִץ?',
    optionsEn: ['Green', 'Blue', 'Pink', 'Red'],
    optionsHe: ['יָרֹק', 'כָּחֹל', 'וָרֹד', 'אָדֹם'],
    answerIndex: 0,
    explanationEn: 'Leaves look green because they contain chlorophyll, which helps make food from sunlight.',
    explanationHe: 'עלים נראים ירוקים בגלל הכלורופיל שעוזר להם להכין מזון מאור השמש.'
  },
  {
    id: 'gk-5-12',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do you use to clean your teeth?',
    questionHe: 'בְּמָה מִשְׁתַּמְּשִׁים כְּדֵי לְנַקּוֹת אֶת הַשִּׁנַּיִם?',
    optionsEn: ['Hairbrush', 'Toothbrush', 'Spoon', 'Soap'],
    optionsHe: ['מִבְרֶשֶׁת שֵׂעָר', 'מִבְרֶשֶׁת שִׁנַּיִם', 'כַּפִּית', 'סַבּוֹן'],
    answerIndex: 1,
    explanationEn: 'Brushing your teeth twice a day keeps them healthy and shiny!',
    explanationHe: 'צחצוח שיניים פעמיים ביום שומר עליהן בריאות ומבריקות!'
  },
  {
    id: 'gk-5-13',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which animal has a very, very long neck?',
    questionHe: 'אֵיזוֹ חַיָּה מְצוּיֶדֶת בְּצַוָּאר אָרֹךְ מְאֹד-מְאֹד?',
    optionsEn: ['Elephant', 'Giraffe', 'Dog', 'Zebra'],
    optionsHe: ['פִּיל', 'גִ׳ירָפָה', 'כֶּלֶב', 'זֶבְרָה'],
    answerIndex: 1,
    explanationEn: 'The giraffe is the tallest mammal on Earth!',
    explanationHe: 'הג׳ירפה היא החיה הגבוהה ביותר על פני כדור הארץ!'
  },
  {
    id: 'gk-5-14',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do you use to carry books to school?',
    questionHe: 'בְּמָה מִשְׁתַּמְּשִׁים כְּדֵי לָשֵׂאת סְפָרִים לְבֵית הַסֵּפֶר?',
    optionsEn: ['Hat', 'Backpack', 'Box', 'Pocket'],
    optionsHe: ['כּוֹבַע', 'תִּיק גַּב', 'קֻפְסָה', 'כִּיס'],
    answerIndex: 1,
    explanationEn: 'A backpack fits on your shoulders to help you carry books comfortably.',
    explanationHe: 'תיק גב מתאים לכתפיים ועוזר לשאת את הציוד בנוחות.'
  },
  {
    id: 'gk-5-15',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What color is a fire engine truck?',
    questionHe: 'בְּאֵיזֶה צֶבֶע כַּבָּאִית אֵשׁ?',
    optionsEn: ['Red', 'Purple', 'Brown', 'Blue'],
    optionsHe: ['אָדֹם', 'סָגֹל', 'חוּם', 'כָּחֹל'],
    answerIndex: 0,
    explanationEn: 'Fire engines are painted red so they are highly visible in traffic.',
    explanationHe: 'כבאית אש צבועה באדום בולט כדי שכולם יבחינו בה בכביש.'
  },
  {
    id: 'gk-5-16',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'How many wheels does a standard bicycle have?',
    questionHe: 'כַּמָּה גַּלְגַּלִּים יֵשׁ לְאוֹפַנַּיִם רְגִילִים?',
    optionsEn: ['3', '4', '2', '1'],
    optionsHe: ['3', '4', '2', '1'],
    answerIndex: 2,
    explanationEn: 'A bicycle has exactly two wheels, while a tricycle has three!',
    explanationHe: 'לאופניים יש שני גלגלים, בעוד שלתלת-אופן יש שלושה!'
  },
  {
    id: 'gk-5-17',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do you wear on your hands when it is freezing cold?',
    questionHe: 'מָה לוֹבְשִׁים עַל הַיָּדַיִם כְּשֶׁקַּר מְאֹד בַּחוּץ?',
    optionsEn: ['Socks', 'Gloves', 'Shoes', 'Scarf'],
    optionsHe: ['גַּרְבַּיִם', 'כְּפָפוֹת', 'נַעֲלַיִם', 'צָעִיף'],
    answerIndex: 1,
    explanationEn: 'Gloves keep your fingers warm and cozy in winter!',
    explanationHe: 'כפפות שומרות על האצבעות שלכם חמימות ונעימות בחורף!'
  },
  {
    id: 'gk-5-18',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do birds use to fly high in the sky?',
    questionHe: 'בְּמָה מִשְׁתַּמְּשׁוֹת הַצִּפֳּרִים כְּדֵי לָעוּף בַּשָּׁמַיִם?',
    optionsEn: ['Paws', 'Wings', 'Noses', 'Fins'],
    optionsHe: ['כַּפּוֹת רַגְלַיִם', 'כְּנָפַיִם', 'אַף', 'סְנַפִּירִים'],
    answerIndex: 1,
    explanationEn: 'Birds flap their wings to generate lift and glide through the air.',
    explanationHe: 'ציפורים מניעות את כנפיהן כדי ליצור כוח עילוי ולעוף.'
  },
  {
    id: 'gk-5-19',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do you use to open a locked door?',
    questionHe: 'בְּמָה מִשְׁתַּמְּשִׁים כְּדֵי לִפְתֹּחַ דֶּלֶת נְעוּלָה?',
    optionsEn: ['Hammer', 'Key', 'Pencil', 'Spoon'],
    optionsHe: ['פַּטִּישׁ', 'מַפְתֵּחַ', 'עִפָּרוֹן', 'כַּף'],
    answerIndex: 1,
    explanationEn: 'A key fits perfectly into the lock to turn the mechanism.',
    explanationHe: 'מפתח מתאים בדיוק למנעול ומאפשר לסובב את המנגנון ולפתוח.'
  },
  {
    id: 'gk-5-20',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which season is the coldest, with snow and heavy rain?',
    questionHe: 'אֵיזוֹ עוֹנָה הִיא הַקָּרָה בְּיוֹתֵר, עִם גֶּשֶׁם וּלְעִתִּים שֶׁלֶג?',
    optionsEn: ['Summer', 'Spring', 'Winter', 'Autumn'],
    optionsHe: ['קַיִץ', 'אָבִיב', 'חֹרֶף', 'סְתָיו'],
    answerIndex: 2,
    explanationEn: 'Winter is the coldest season of the year, bringing rain, wind, and cold weather.',
    explanationHe: 'החורף הוא העונה הקרה ביותר בשנה, ומביא עמו גשמים ורוחות.'
  },
  {
    id: 'gk-5-21',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the name of the huge star that shines bright during the day?',
    questionHe: 'אֵיךְ קוֹרְאִים לַכּוֹכָב הָעֲנָק שֶׁמֵּאִיר לָנוּ בְּמַהֲלַךְ הַיּוֹם?',
    optionsEn: ['The Moon', 'The Sun', 'Mars', 'Polaris'],
    optionsHe: ['הַיָּרֵחַ', 'הַשֶּׁמֶשׁ', 'מַאֲדִים', 'כּוֹכַב הַצָּפוֹן'],
    answerIndex: 1,
    explanationEn: 'The Sun is actually a giant star closest to the Earth.',
    explanationHe: 'השמש היא למעשה כוכב ענק והיא הכי קרובה אלינו.'
  },
  {
    id: 'gk-5-22',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which shape has four equal sides and four square corners?',
    questionHe: 'אֵיזוֹ צוּרָה מְצוּיֶדֶת בְּאַרְבָּעָה צְדָדִים שָׁוִים?',
    optionsEn: ['Triangle', 'Circle', 'Square', 'Oval'],
    optionsHe: ['מְשֻׁלָּשׁ', 'עִגּוּל', 'רִיבּוּעַ', 'אֶלִיפְּסָה'],
    answerIndex: 2,
    explanationEn: 'A square has 4 sides that are all exactly the same length!',
    explanationHe: 'לריבוע יש ארבעה צדדים שכולם באותו האורך בדיוק!'
  },
  {
    id: 'gk-5-23',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What sweet golden treat do busy honeybees make?',
    questionHe: 'אֵיזֶה מַאֲכָל מָתוֹק וְזָהֹב מְכִינוֹת הַדְּבוֹרִים?',
    optionsEn: ['Sugar', 'Honey', 'Chocolate', 'Milk'],
    optionsHe: ['סֻכָּר', 'דְּבַשׁ', 'שׁוֹקוֹלָד', 'חָלָב'],
    answerIndex: 1,
    explanationEn: 'Bees collect nectar from flowers to make healthy, sweet honey.',
    explanationHe: 'דבורים אוספות צוף מפרחים כדי להכין דבש מתוק ובריא.'
  },
  {
    id: 'gk-5-24',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Where does a fish live and swim?',
    questionHe: 'אֵיפֹה חַיִּים וְשׂוֹחִים הַדָּגִים?',
    optionsEn: ['In the sky', 'On land', 'In the water', 'In trees'],
    optionsHe: ['בַּשָּׁמַיִם', 'עַל הַקַּרְקַע', 'בַּמַּיִם', 'עַל עֵצִים'],
    answerIndex: 2,
    explanationEn: 'Fish live in water because they breathe through their gills!',
    explanationHe: 'דגים חיים במים כיוון שהם נושמים בעזרת הזימים שלהם!'
  },
  {
    id: 'gk-5-25',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do we call a baby dog?',
    questionHe: 'אֵיךְ קוֹרְאִים לְגוּר כְּלָבִים?',
    optionsEn: ['Kitten', 'Puppy', 'Cub', 'Calf'],
    optionsHe: ['חתלתול', 'גּוּר כְּלָבִים (פַּפִּי)', 'גּוּר אֲרָיוֹת', 'עֵגֶל'],
    answerIndex: 1,
    explanationEn: 'A baby dog is called a puppy. They love to play and cuddle!',
    explanationHe: 'גור כלבים נקרא puppy באנגלית. הם אוהבים לשחק ולהתכרבל!'
  },
  {
    id: 'gk-5-26',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which juicy round fruit has the same name as its color?',
    questionHe: 'אֵיזֶה פְּרִי עָגֹל וְעָסִיסִי נוֹשֵׂא אֶת שֵׁם הַצֶּבֶע שֶׁלּוֹ?',
    optionsEn: ['Apple', 'Orange', 'Lemon', 'Banana'],
    optionsHe: ['תַּפּוּחַ', 'תָּפוּז', 'לִימוֹן', 'בָּנָנָה'],
    answerIndex: 1,
    explanationEn: 'An orange is a fruit named orange, and its color is orange too!',
    explanationHe: 'התפוז (הנקרא Orange באנגלית) הוא בצבע כתום (Orange)!'
  },
  {
    id: 'gk-5-27',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What tool do we use safely to cut paper?',
    questionHe: 'בְּאֵיזֶה כְּלִי מִשְׁתַּמְּשִׁים בִּבְטִיחוּת כְּדֵי לִגְזֹר נְיָר?',
    optionsEn: ['Pencil', 'Scissors', 'Glue', 'Ruler'],
    optionsHe: ['עִפָּרוֹן', 'מִסְפָּרַיִם', 'דֶּבֶק', 'סַרְגֵּל'],
    answerIndex: 1,
    explanationEn: 'Safety scissors are used by children to make fun paper crafts.',
    explanationHe: 'מספריים בטיחותיים מיועדים לילדים לעבודות יצירה עם נייר.'
  },
  {
    id: 'gk-5-28',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What do you hold above your head to stay dry in the rain?',
    questionHe: 'מָה מַחְזִיקִים מֵעַל הָרֹאשׁ כְּדֵי לְהִשָּׁאֵר יְבֵשִׁים בַּגֶּשֶׁם?',
    optionsEn: ['Hat', 'Spoon', 'Umbrella', 'Book'],
    optionsHe: ['כּוֹבַע', 'כַּף', 'מִטְרִיָּה', 'סֵפֶר'],
    answerIndex: 2,
    explanationEn: 'An umbrella keeps the raindrops from hitting you!',
    explanationHe: 'מטריה מונעת מטיפות הגשם להרטיב אתכם!'
  },
  {
    id: 'gk-5-29',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'How many fingers do you have on one hand?',
    questionHe: 'כַּמָּה אֶצְבָּעוֹת יֵשׁ לְךָ בְּיָד אַחַת?',
    optionsEn: ['4', '5', '10', '6'],
    optionsHe: ['4', '5', '10', '6'],
    answerIndex: 1,
    explanationEn: 'Most people have exactly 5 fingers on each hand, making 10 in total.',
    explanationHe: 'ביד אחת יש לנו חמש אצבעות, ובשתי הידיים יחד עשר אצבעות.'
  },
  {
    id: 'gk-5-30',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What color is fresh milk?',
    questionHe: 'בְּאֵיזֶה צֶבֶע חָלָב טָרִי?',
    optionsEn: ['White', 'Yellow', 'Blue', 'Pink'],
    optionsHe: ['לָבָן', 'צָהֹב', 'כָּחֹל', 'וָרֹד'],
    answerIndex: 0,
    explanationEn: 'Milk is white because of a protein called casein!',
    explanationHe: 'החלב בצבע לבן בזכות חלבון שנמצא בתוכו.'
  },
  {
    id: 'gk-5-31',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the opposite of hot?',
    questionHe: 'מַהוּ הַהֵפֶךְ מֵחַם?',
    optionsEn: ['Warm', 'Dry', 'Cold', 'Spicy'],
    optionsHe: ['חָמִים', 'יָבֵשׁ', 'קַר', 'חָרִיף'],
    answerIndex: 2,
    explanationEn: 'Cold is the opposite of hot. Snow is cold and fire is hot!',
    explanationHe: 'ההפך מחם הוא קר. שלג הוא קר ואש היא חמה!'
  },
  {
    id: 'gk-5-32',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which animal moves very slowly and carries a hard shell?',
    questionHe: 'אֵיזוֹ חַיָּה זָזָה לְאַט-לְאַט וְנוֹשֵׂאת שִׁרְיוֹן קָשֶׁה?',
    optionsEn: ['Rabbit', 'Cheetah', 'Turtle', 'Frog'],
    optionsHe: ['אַרְנָב', 'בַּרְדְּלָס', 'צָב', 'צְפַרְדֵּעַ'],
    answerIndex: 2,
    explanationEn: 'Turtles carry their homes (shells) on their backs and walk slowly.',
    explanationHe: 'צבים נושאים את שריונם המגן עליהם והולכים בקצב איטי.'
  },
  {
    id: 'gk-5-33',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What machine do we watch our favorite animated cartoons on?',
    questionHe: 'בְּאֵיזֶה מַכְשִׁיר אֲנַחְנוּ צוֹפִים בַּסִּרְטוֹנִים הַמְּצֻיָּרִים הָאֲהוּבִים עָלֵינוּ?',
    optionsEn: ['Toaster', 'Television', 'Fridge', 'Washing Machine'],
    optionsHe: ['טוֹסְטֶר', 'טֶלֶוִיזְיָה', 'מְקָרֵר', 'מְכוֹנַת כְּבִיסָה'],
    answerIndex: 1,
    explanationEn: 'We use TVs or tablets to watch exciting movies and shows.',
    explanationHe: 'אנו משתמשים בטלוויזיה או בטאבלט כדי לצפות בסדרות אהובות.'
  },
  {
    id: 'gk-5-34',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What grows on tree branches that are usually green and flat?',
    questionHe: 'מָה גָּדֵל עַל עַנְפֵי הָעֵצִים שֶׁהֵם בְּדֶרֶךְ כְּלָל יְרֻקִּים וּשְׁטוּחִים?',
    optionsEn: ['Apples', 'Leaves', 'Flowers', 'Roots'],
    optionsHe: ['תַּפּוּחִים', 'עָלִים', 'פְּרָחִים', 'שׁוֹרָשִׁים'],
    answerIndex: 1,
    explanationEn: 'Leaves grow on trees and gather light to feed the plant.',
    explanationHe: 'העלים גדלים על הענפים וקולטים אור שמש המזין את העץ.'
  },
  {
    id: 'gk-5-35',
    category: 'Animals',
    ageGroup: '5-7',
    questionEn: 'Which animal is known as the king of the jungle?',
    questionHe: 'אֵיזוֹ חַיָּה מְכֻנָּה מֶלֶךְ הַגּ׳וּנְגֶּל?',
    optionsEn: ['Tiger', 'Lion', 'Bear', 'Elephant'],
    optionsHe: ['נָמֵר', 'אַרְיֵה', 'דֹּב', 'פִיל'],
    answerIndex: 1,
    explanationEn: 'The lion is called the king of the jungle because of its power, pride, and beautiful mane!',
    explanationHe: 'האריה מכונה מלך החיות או מלך הג׳ונגל בזכות כוחו, מראהו המרשים והרעמה היפה שלו.'
  },
  {
    id: 'gk-5-36',
    category: 'Math',
    ageGroup: '5-7',
    questionEn: 'If you have 2 apples and get 2 more, how many do you have in total?',
    questionHe: 'אִם יֵשׁ לְךָ 2 תַּפּוּחִים וְקִבַּלְתָּ עוֹד 2, כַּמָּה יֵשׁ לְךָ בַּסַּךְ הַכֹּל?',
    optionsEn: ['3', '4', '5', '6'],
    optionsHe: ['3', '4', '5', '6'],
    answerIndex: 1,
    explanationEn: '2 plus 2 equals 4. You can count them on your fingers!',
    explanationHe: '2 ועוד 2 הם 4. אפשר לספור אותם בקלות על האצבעות!'
  },
  {
    id: 'gk-5-37',
    category: 'Space',
    ageGroup: '5-7',
    questionEn: 'Which planet do we live on?',
    questionHe: 'עַל אֵיזֶה כּוֹכָב לֶכֶת אֲנַחְנוּ חַיִּים?',
    optionsEn: ['Mars', 'Jupiter', 'Earth', 'Venus'],
    optionsHe: ['מַאֲדִים', 'צֶדֶק', 'כַּדּוּר הָאָרֶץ', 'נוֹגַהּ'],
    answerIndex: 2,
    explanationEn: 'We live on Earth, the only planet known to support life, covered in beautiful oceans!',
    explanationHe: 'אנחנו חיים על כדור הארץ, כוכב הלכת היחיד שידוע שיש עליו חיים ומים זורמים.'
  },
  {
    id: 'gk-5-38',
    category: 'Science',
    ageGroup: '5-7',
    questionEn: 'What turns into ice when it gets very, very cold?',
    questionHe: 'מָה הוֹפֵךְ לְקֶרַח כְּשֶׁקַּר מְאֹד מְאֹד?',
    optionsEn: ['Milk', 'Water', 'Juice', 'Oil'],
    optionsHe: ['חָלָב', 'מַיִם', 'מִיץ', 'שֶׁמֶן'],
    answerIndex: 1,
    explanationEn: 'When liquid water freezes at 0 degrees, it turns solid and becomes ice!',
    explanationHe: 'כאשר מים מתקררים מאוד, הם קופאים והופכים לקרח מוצק.'
  },
  {
    id: 'gk-5-39',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'How many days are in a single week?',
    questionHe: 'כַּמָּה יָמִים יֵשׁ בְּשָׁבוּעַ אֶחָד?',
    optionsEn: ['5', '6', '7', '8'],
    optionsHe: ['5', '6', '7', '8'],
    answerIndex: 2,
    explanationEn: 'A week has 7 days, starting from Sunday and ending with Saturday.',
    explanationHe: 'בשבוע יש בדיוק שבעה ימים, מיום ראשון ועד יום שבת.'
  },
  {
    id: 'gk-5-40',
    category: 'Geography',
    ageGroup: '5-7',
    questionEn: 'What is a very high mountain of rock and snow called?',
    questionHe: 'אֵיךְ קוֹרְאִים לְחֵלֶק אֲדָמָה גָּבֹהַּ מְאֹד שֶׁעָשׂוּי מִסֶּלַע וְלִפְעָמִים שֶׁלֶג?',
    optionsEn: ['Valley', 'Mountain', 'Hill', 'Island'],
    optionsHe: ['עֵמֶק', 'הַר', 'גִּבְעָה', 'אִי'],
    answerIndex: 1,
    explanationEn: 'Mountains are massive landforms that rise high above their surroundings.',
    explanationHe: 'הר הוא שטח אדמה המתנשא לגובה רב מעל סביבתו.'
  },
  {
    id: 'gk-5-41',
    category: 'Animals',
    ageGroup: '5-7',
    questionEn: 'What insect makes sweet honey?',
    questionHe: 'אֵיזֶה חֶרֶק מְיַצֵּר דְּבַשׁ מָתוֹק?',
    optionsEn: ['Ant', 'Bee', 'Butterfly', 'Ladybug'],
    optionsHe: ['נְמָלָה', 'דְּבוֹרָה', 'פרפר', 'מושית השבע'],
    answerIndex: 1,
    explanationEn: 'Bees collect nectar from flowers and turn it into delicious honey inside their hive.',
    explanationHe: 'הדבורים אוספות צוף מפרחים ומכינות ממנו דבש מתוק בכוורת.'
  },
  {
    id: 'gk-5-42',
    category: 'Math',
    ageGroup: '5-7',
    questionEn: 'What number comes right after 9?',
    questionHe: 'אֵיזֶה מִסְפָּר מַגִּיעַ מִיָּד אַחֲרֵי הַמִּסְפָּר 9?',
    optionsEn: ['8', '10', '11', '12'],
    optionsHe: ['8', '10', '11', '12'],
    answerIndex: 1,
    explanationEn: 'Ten (10) is the first two-digit number and comes right after nine.',
    explanationHe: 'המספר 10 מגיע מיד אחרי 9 והוא המספר הדו-ספרתי הראשון.'
  },
  {
    id: 'gk-5-43',
    category: 'Space',
    ageGroup: '5-7',
    questionEn: 'What lights up the night sky and changes shape?',
    questionHe: 'מָה מֵאִיר אֶת שְׁמֵי הַלַּיְלָה וּמְשַׁנֶּה צּוּרָה?',
    optionsEn: ['The Moon', 'The Sun', 'A Cloud', 'An Airplane'],
    optionsHe: ['הַיָּרֵחַ', 'הַשֶּׁמֶשׁ', 'עָנָן', 'מָטוֹס'],
    answerIndex: 0,
    explanationEn: 'The Moon shines because it reflects sunlight. As it orbits Earth, we see different amounts of its lit side.',
    explanationHe: 'הירח מחזיר את אור השמש וכשהוא מסתובב סביבנו הוא נראה בצורות שונות.'
  },
  {
    id: 'gk-5-44',
    category: 'Science',
    ageGroup: '5-7',
    questionEn: 'Which sense do we use to hear music?',
    questionHe: 'בְּאֵיזֶה חוּשׁ אֲנַחְנוּ מִשְׁתַּמְּשִׁים כְּדֵי לִשְׁמֹעַ מוּזִיקָה?',
    optionsEn: ['Sight', 'Smell', 'Hearing', 'Taste'],
    optionsHe: ['רְאִיָּה', 'רֵיחַ', 'שְׁמִיעָה', 'טַעַם'],
    answerIndex: 2,
    explanationEn: 'We use our ears and the sense of hearing to listen to beautiful sounds and songs.',
    explanationHe: 'אנחנו משתמשים באוזניים ובחוש השמיעה כדי ליהנות מצלילים ומוזיקה.'
  },
  {
    id: 'gk-5-45',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the opposite of the word "hot"?',
    questionHe: 'מָהִי הַמִּלָּה הַהֲפוּכָה מֵהַמִּלָּה ׳חַם׳?',
    optionsEn: ['Warm', 'Cold', 'Wet', 'Dry'],
    optionsHe: ['חַמִּים', 'קַר', 'רָטוֹב', 'יָבֵשׁ'],
    answerIndex: 1,
    explanationEn: 'The opposite of hot is cold, just like ice and hot cocoa!',
    explanationHe: 'ההפך מחם הוא קר, כמו קרחון לעומת מרק חם!'
  },
  {
    id: 'gk-5-46',
    category: 'Geography',
    ageGroup: '5-7',
    questionEn: 'Where can you build a sandcastle?',
    questionHe: 'אֵיפֹה אֶפְשָׁר לִבְנוֹת אַרְמוֹן מֵחוֹל?',
    optionsEn: ['The Forest', 'The Beach', 'The Kitchen', 'The Bedroom'],
    optionsHe: ['בַּיַּעַר', 'בְּחוֹף הַיָּם', 'בַּמִּטְבָּח', 'בַּחֲדַר הַשֵּׁנָה'],
    answerIndex: 1,
    explanationEn: 'The beach has lots of sand and water, perfect for molding creative sandcastles.',
    explanationHe: 'חוף הים מלא בחול רטוב ומים, שזה השילוב המושלם לבניית ארמונות.'
  },
  {
    id: 'gk-5-47',
    category: 'Animals',
    ageGroup: '5-7',
    questionEn: 'Which bird can mimic human words and has colorful feathers?',
    questionHe: 'אֵיזוֹ צִפּוֹר צִבְעוֹנִית יְכוֹלָה לְחַקּוֹת מִלִּים שֶׁל בְּנֵי אָדָם?',
    optionsEn: ['Crow', 'Parrot', 'Eagle', 'Pigeon'],
    optionsHe: ['עוֹרֵב', 'תֻּכִּי', 'עַיִט', 'יוֹנָה'],
    answerIndex: 1,
    explanationEn: 'Parrots are super smart birds that can mimic sounds and words they hear!',
    explanationHe: 'תוכים הם ציפורים חכמות מאוד שמסוגלות לחזור על קולות ומילים שהם שומעים.'
  },
  {
    id: 'gk-5-48',
    category: 'Math',
    ageGroup: '5-7',
    questionEn: 'How many fingers do you have on one hand?',
    questionHe: 'כַּמָּה אֶצְבָּעוֹת יֵשׁ לְךָ בְּיָד אַחַת?',
    optionsEn: ['4', '5', '6', '10'],
    optionsHe: ['4', '5', '6', '10'],
    answerIndex: 1,
    explanationEn: 'Most people have 5 fingers on each hand, making 10 fingers in total!',
    explanationHe: 'ביד אחת יש לנו חמש אצבעות, וביחד בשתי הידיים יש עשר!'
  },
  {
    id: 'gk-5-49',
    category: 'Science',
    ageGroup: '5-7',
    questionEn: 'What do plant roots drink from the soil?',
    questionHe: 'מָה שׁוֹתִים שָׁרָשָׁיו שֶׁל הַצֶּמַח מִתּוךְ הָאֲדָמָה?',
    optionsEn: ['Juice', 'Water', 'Milk', 'Soda'],
    optionsHe: ['מִיץ', 'מַיִם', 'חָלָב', 'סוֹדָה'],
    answerIndex: 1,
    explanationEn: 'Plants absorb water and nutrients from the soil using their roots to grow strong.',
    explanationHe: 'שורשי הצמח יונקים מים מהאדמה שעוזרים לו לגדול ולפרוח.'
  },
  {
    id: 'gk-5-50',
    category: 'Space',
    ageGroup: '5-7',
    questionEn: 'How many suns do we have in our solar system?',
    questionHe: 'כַּמָּה שְׁמָשׁוֹת יֵשׁ בְּמַעֲרֶכֶת הַשֶּׁמֶשׁ שֶׁלָּנוּ?',
    optionsEn: ['One', 'Two', 'Three', 'Zero'],
    optionsHe: ['אַחַת', 'שְׁתַּיִם', 'שָׁלוֹשׁ', 'אֶפֶס'],
    answerIndex: 0,
    explanationEn: 'We have only one star at the center of our solar system: the Sun!',
    explanationHe: 'במרכז מערכת השמש שלנו יש שמש אחת בלבד שהיא כוכב חם וענק.'
  },
  {
    id: 'gk-5-51',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What color do you get when you mix red and white?',
    questionHe: 'אֵיזֶה צֶבֶע מְקַבְּלִים כְּשֶׁמְּעַרְבְּבִים אָדֹם וְלָבָן?',
    optionsEn: ['Blue', 'Pink', 'Orange', 'Green'],
    optionsHe: ['כָּחֹל', 'וָרֹד', 'כָּתֹם', 'יָרֹק'],
    answerIndex: 1,
    explanationEn: 'Mixing red and white lightens the red, creating a lovely pink color!',
    explanationHe: 'ערבוב של אדום ולבן מבהיר את האדום ויוצר צבע ורוד שמח!'
  },
  {
    id: 'gk-5-52',
    category: 'Geography',
    ageGroup: '5-7',
    questionEn: 'What do we call a giant body of salty water?',
    questionHe: 'אֵיךְ קוֹרְאִים לְגוּף עָנָק שֶׁל מַיִם מְלוּחִים?',
    optionsEn: ['Lake', 'River', 'Pond', 'Ocean'],
    optionsHe: ['אֲגַם', 'נָהָר', 'שְׁלוּלִית', 'אוֹקְיָנוּס'],
    answerIndex: 3,
    explanationEn: 'Oceans cover most of our planet and are filled with salty water and sea creatures.',
    explanationHe: 'אוקיינוס הוא גוף עצום של מים מלוחים המכסה את רוב כדור הארץ.'
  },
  {
    id: 'gk-5-53',
    category: 'Animals',
    ageGroup: '5-7',
    questionEn: 'Which animal is very tall and has a super long neck?',
    questionHe: 'אֵיזוֹ חַיָּה גְּבוֹהָה מְאֹד וְיֵשׁ לָהּ צַוָּאר אָרֹךְ מְאֹד?',
    optionsEn: ['Elephant', 'Giraffe', 'Horse', 'Hippo'],
    optionsHe: ['פִיל', 'גִּ׳ירָפָה', 'סוּס', 'הִיפּוֹפּוֹטָם'],
    answerIndex: 1,
    explanationEn: 'The giraffe uses its extremely long neck to reach fresh leaves high up in acacia trees.',
    explanationHe: 'הג׳ירפה היא החיה הגבוהה ביבשה, וצווארה הארוך עוזר לה לאכול עלים מצמרות העצים.'
  },
  {
    id: 'gk-5-54',
    category: 'Math',
    ageGroup: '5-7',
    questionEn: 'If you have 5 candies and eat 1, how many are left?',
    questionHe: 'אִם יֵשׁ לְךָ 5 סֻכָּרִיּוֹת וְאָכַלְתָּ 1, כַּמָּה נִשְׁאֲרוּ?',
    optionsEn: ['3', '4', '5', '6'],
    optionsHe: ['3', '4', '5', '6'],
    answerIndex: 1,
    explanationEn: '5 minus 1 equals 4. Counting backward by one!',
    explanationHe: '5 פחות 1 זה 4. נשארו לך ארבע סוכריות מתוקות!'
  },
  {
    id: 'gk-5-55',
    category: 'Science',
    ageGroup: '5-7',
    questionEn: 'What season is famous for falling leaves and cooler weather?',
    questionHe: 'אֵיזוֹ עוֹנָה מְפֻרְסֶמֶת בִּנְשִׁירַת עָלִים וּמֶזֶג אֲוִיר קַר יוֹתֵר?',
    optionsEn: ['Summer', 'Spring', 'Autumn', 'Winter'],
    optionsHe: ['קַיִץ', 'אָבִיב', 'סְתָיו', 'חֹרֶף'],
    answerIndex: 2,
    explanationEn: 'Autumn (or fall) is when trees shed their leaves and prepare for the winter cold.',
    explanationHe: 'בסתיו העלים הופכים לצהובים ואדומים ונושרים מהעצים בשלכת.'
  },
  {
    id: 'gk-5-56',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Which vehicle flies in the sky and has wings?',
    questionHe: 'אֵיזֶה כְּלִי תַּחְבּוּרָה טָס בַּשָּׁמַיִם וְיֵשׁ לוֹ כְּנָפַיִם?',
    optionsEn: ['Car', 'Train', 'Airplane', 'Boat'],
    optionsHe: ['מְכוֹנִית', 'רַכֶּבֶת', 'מָטוֹס', 'סִירָה'],
    answerIndex: 2,
    explanationEn: 'Airplanes use wings and powerful engines to lift off and fly high above the clouds.',
    explanationHe: 'מטוס הוא כלי תחבורה כבד המשתמש בכנפיים ומנועים כדי לטוס בשמיים.'
  },
  {
    id: 'gk-5-57',
    category: 'Geography',
    ageGroup: '5-7',
    questionEn: 'What do we use to find our way on a trip that shows roads and paths?',
    questionHe: 'בְּמָה אֲנַחְנוּ מִשְׁתַּמְּשִׁים כְּדֵי לִמְצֹא אֶת הַדֶּרֶךְ בְּטִיּוּל?',
    optionsEn: ['Book', 'Map', 'Mirror', 'Clock'],
    optionsHe: ['סֵפֶר', 'מַפָּה', 'מַרְאָה', 'שָׁעוֹן'],
    answerIndex: 1,
    explanationEn: 'A map is a drawing of an area that helps us navigate and find where we are.',
    explanationHe: 'מפה היא ציור שמראה לנו את הדרכים, הרחובות והיעדים בטיול.'
  },
  {
    id: 'gk-5-58',
    category: 'Animals',
    ageGroup: '5-7',
    questionEn: 'Which animal croaks and leaps high near ponds?',
    questionHe: 'אֵיזוֹ חַיָּה מְקַרְקֶרֶת וּמְנַתֶּרֶת לְגֹבַהּ לְיַד שְׁלוּלִיּוֹת?',
    optionsEn: ['Rabbit', 'Frog', 'Monkey', 'Fish'],
    optionsHe: ['אַרְנָב', 'צְפַרְדֵּעַ', 'קוֹף', 'דָּג'],
    answerIndex: 1,
    explanationEn: 'Frogs are amphibians that start as tadpoles, love water, and make a croaking sound.',
    explanationHe: 'הצפרדע אוהבת מים, מנתרת בעזרת רגליה החזקות ומשמיעה קול קירקור.'
  },
  {
    id: 'gk-5-59',
    category: 'Math',
    ageGroup: '5-7',
    questionEn: 'A triangle has how many corners?',
    questionHe: 'כַּמָּה פִּנּוֹת יֵשׁ לִמְשֻׁלָּשׁ?',
    optionsEn: ['3', '4', '5', '6'],
    optionsHe: ['3', '4', '5', '6'],
    answerIndex: 0,
    explanationEn: 'A triangle has exactly 3 sides and 3 corners (or vertices).',
    explanationHe: 'למשולש יש שלוש צלעות ושלוש פינות, בדיוק כמו השם שלו!'
  },
  {
    id: 'gk-5-60',
    category: 'Science',
    ageGroup: '5-7',
    questionEn: 'Which part of our body pumps blood like an engine?',
    questionHe: 'אֵיזֶה חֵלֶק בַּגּוּף מַזְרִים דָּם כְּמוֹ מָנוֹעַ?',
    optionsEn: ['Lungs', 'Brain', 'Heart', 'Bones'],
    optionsHe: ['רֵאוֹת', 'מוֹחַ', 'לֵב', 'עֲצָמוֹת'],
    answerIndex: 2,
    explanationEn: 'The heart beats all day and night to keep blood flowing and supply oxygen to your body!',
    explanationHe: 'הלב פועם ללא הפסקה ומזרים את הדם לכל חלקי הגוף שלנו.'
  },
  {
    id: 'gk-5-61',
    category: 'Space',
    ageGroup: '5-7',
    questionEn: 'What shape is a full moon?',
    questionHe: 'בְּאֵיזוֹ צוּרָה הַיָּרֵחַ כְּשֶׁהוּא מָלֵא?',
    optionsEn: ['Square', 'Triangle', 'Circle', 'Star'],
    optionsHe: ['רִבּוּעַ', 'מְשֻׁלָּשׁ', 'עִגּוּל', 'כּוֹכָב'],
    answerIndex: 2,
    explanationEn: 'A full moon looks like a beautiful, bright, glowing circle in the sky.',
    explanationHe: 'ירח מלא נראה בשמיים כמו עיגול גדול, מאיר ויפהפה.'
  },
  {
    id: 'gk-5-62',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the color of fresh grass?',
    questionHe: 'מַהוּ הַצֶּבֶע שֶׁל דֶּשֶׁא רַעֲנָן?',
    optionsEn: ['Red', 'Yellow', 'Green', 'Purple'],
    optionsHe: ['אָדֹם', 'צָהֹב', 'יָרֹק', 'סָגֹל'],
    answerIndex: 2,
    explanationEn: 'Grass is green because of a special pigment called chlorophyll that helps it make food from sunlight.',
    explanationHe: 'הדשא ירוק בזכות חומר מיוחד שעוזר לו לקלוט אור שמש ולגדול.'
  },
  {
    id: 'gk-5-63',
    category: 'Geography',
    ageGroup: '5-7',
    questionEn: 'What is a dry, sandy place with very little water called?',
    questionHe: 'אֵיךְ נִקְרָא מָקוֹם יָבֵשׁ וְחוֹלִי עִם מְעַט מְאֹד מַיִם?',
    optionsEn: ['Jungle', 'Forest', 'Desert', 'Swamp'],
    optionsHe: ['גּ׳וּנְגֶּל', 'יַעַר', 'מִדְבָּר', 'בִּיצָּה'],
    answerIndex: 2,
    explanationEn: 'Deserts are dry places that get very little rain, often filled with beautiful sand dunes.',
    explanationHe: 'במדבר כמעט ולא יורד גשם, ולכן הוא יבש מאוד ומלא בחול וסלעים.'
  },
  {
    id: 'gk-5-64',
    category: 'Animals',
    ageGroup: '5-7',
    questionEn: 'What farm animal gives us white fresh milk?',
    questionHe: 'אֵיזוֹ חַיַּת חַוָּה נוֹתֶנֶת לָנוּ חָלָב לָבָן וְטָרִי?',
    optionsEn: ['Hen', 'Cow', 'Sheep', 'Dog'],
    optionsHe: ['תַּרְנְגֹלֶת', 'פָּרָה', 'כִּבְשָׂה', 'כֶּלֶב'],
    answerIndex: 1,
    explanationEn: 'Cows eat grass and produce milk, which is used to make cheese, butter, and yogurt.',
    explanationHe: 'הפרה אוכלת עשב ומייצרת חלב מזין שממנו מכינים גבינות ומעדנים.'
  },
  {
    id: 'gk-5-65',
    category: 'Math',
    ageGroup: '5-7',
    questionEn: 'What number is double of 3?',
    questionHe: 'אֵיזֶה מִסְפָּר הוּא כָּפוּל מִ-3?',
    optionsEn: ['4', '5', '6', '9'],
    optionsHe: ['4', '5', '6', '9'],
    answerIndex: 2,
    explanationEn: 'Double of 3 means 3 plus 3, which equals 6.',
    explanationHe: 'כפול מ-3 זה בעצם 3 ועוד 3, שזה ביחד 6.'
  },
  {
    id: 'gk-5-66',
    category: 'Science',
    ageGroup: '5-7',
    questionEn: 'Which star is closest to the Earth?',
    questionHe: 'אֵיזֶה כּוֹכָב הוּא הַקָּרוֹב בְּיוֹתֵר לְכַדּוּר הָאָרֶץ?',
    optionsEn: ['North Star', 'The Sun', 'Sirius', 'Vega'],
    optionsHe: ['כּוֹכָב הַצָּפוֹן', 'הַשֶּׁמֶשׁ', 'סיריוס', 'וגה'],
    answerIndex: 1,
    explanationEn: 'The Sun is actually a star! It looks so big because it is much closer to us than other stars.',
    explanationHe: 'השמש שלנו היא כוכב לכל דבר, והיא קרובה אלינו בהרבה מכל שאר הכוכבים.'
  },
  {
    id: 'gk-5-67',
    category: 'Space',
    ageGroup: '5-7',
    questionEn: 'What do we wear to explore outer space safely?',
    questionHe: 'מָה אֲנַחְנוּ לוֹבְשִׁים כְּדֵי לַחְקֹר אֶת הֶחָלָל הַחִיצוֹנִי בְּבִטְחָה?',
    optionsEn: ['Coat', 'Raincoat', 'Spacesuit', 'Pajamas'],
    optionsHe: ['מְעִיל', 'מְעִיל גֶּשֶׁם', 'חֲלִיפַת חָלָל', 'פִּיגָ׳מָה'],
    answerIndex: 2,
    explanationEn: 'Spacesuits provide oxygen, keep astronauts warm, and protect them from space hazards.',
    explanationHe: 'חליפת חלל שומרת על האסטרונאוטים, מספקת להם אוויר לנשימה ומגנה עליהם בקור של החלל.'
  },
  {
    id: 'gk-5-68',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What is the name of the white cold stuff that falls from clouds in winter?',
    questionHe: 'אֵיךְ קוֹרְאִים לַחֹמֶר הַלָּבָן וְהַקַּר שֶׁיּוֹרֵד מֵהָעֲנָנִים בַּחֹרֶף?',
    optionsEn: ['Rain', 'Snow', 'Ice cream', 'Cotton candy'],
    optionsHe: ['גֶּשֶׁם', 'שֶׁלֶג', 'גְּלִידָה', 'צֶמֶר גֶּפֶן'],
    answerIndex: 1,
    explanationEn: 'Snow forms when water drops in clouds freeze into beautiful ice crystal shapes.',
    explanationHe: 'שלג נוצר מטיפות מים שקופאות בעננים והופכות לגבישי קרח יפהפיים.'
  },
  {
    id: 'gk-5-69',
    category: 'Geography',
    ageGroup: '5-7',
    questionEn: 'What color represents water on most globes and maps?',
    questionHe: 'אֵיזֶה צֶבֶע מְיַצֵּג מַיִם בְּרֹב הַגְּלוֹבּוּסִים וְהַמַּפּוֹת?',
    optionsEn: ['Green', 'Brown', 'Blue', 'Red'],
    optionsHe: ['יָרֹק', 'חוּם', 'כָּחֹל', 'אָדֹם'],
    answerIndex: 2,
    explanationEn: 'Blue is used on maps and globes to easily point out lakes, rivers, and deep oceans.',
    explanationHe: 'הצבע הכחול משמש לסימון נהרות, ימים ואוקיינוסים על הגלובוס והמפה.'
  },
  {
    id: 'gk-5-visual-stop',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Look at the red sign! What does this octagon road sign mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הָאָדֹם! מָה מַשְׁמָעוּת תַּמְרוּר מְשֻׁשֶּׁה זֶה?',
    optionsEn: ['Stop and give way', 'Go faster', 'Turn left', 'Bicycle path'],
    optionsHe: ['עֲצֹר וְתֵן זְכוּת קָדִימָה', 'סַע מַהֵר יוֹתֵר', 'פְּנֵה שְׂמֹאלָה', 'נְתִיב אוֹפַנַּיִם'],
    answerIndex: 0,
    explanationEn: 'The red octagon is the Stop Sign. It tells drivers to come to a complete stop and check for safety!',
    explanationHe: 'התמרור האדום בעל שמונה הצלעות הוא תמרור עצור. הוא מורה לנהגים לעצור עצירה מלאה ולבדוק שהדרך פנויה ובטוחה!',
    visualType: 'stop-sign'
  },
  {
    id: 'gk-5-visual-count',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Observe the picture! How many green triangles can you count?',
    questionHe: 'הִסְתַּכְּלוּ בַּתְּמוּנָה! כַּמָּה מְשֻׁלָּשִׁים יְרֻקִּים אַתֶּם סוֹפְרִים?',
    optionsEn: ['2', '3', '4', '5'],
    optionsHe: ['2', '3', '4', '5'],
    answerIndex: 1,
    explanationEn: 'Count carefully! There are exactly 3 green triangles hidden among the stars and circles.',
    explanationHe: 'ספרו בזהירות! ישנם בדיוק 3 משולשים ירוקים המפוזרים בין הכוכבים והעיגולים.',
    visualType: 'count-shapes'
  },
  {
    id: 'gk-5-visual-odd',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Look closely at the faces! Which face is different from the others?',
    questionHe: 'הַבִּיטוּ הֵטֵב בַּפַּרְצוּפִים! אֵיזֶה פַּרְצוּף שׁוֹנֶה מִכָּל הָאֲחֵרִים?',
    optionsEn: ['The crying blue face', 'The smiling yellow face', 'They are all identical', 'The happy star face'],
    optionsHe: ['הַפַּרְצוּף הַבּוֹכֶה הַכָּחֹל', 'הַפַּרְצוּף הַמְּחַיֵּךְ הַצָּהֹב', 'כֻּלָּם זֵהִים לַחֲלוּטִין', 'הַפַּרְצוּף הַשָּׂמֵחַ שֶׁל הַכּוֹכָב'],
    answerIndex: 0,
    explanationEn: 'Three faces are happy yellow smiling faces, but one is a sad blue crying face!',
    explanationHe: 'שלושה מהפרצופים הם צהובים ומחייכים בשמחה, אך אחד הוא כחול ועצוב!',
    visualType: 'odd-one-out'
  },
  {
    id: 'gk-5-visual-pattern',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'What color comes next to complete the traffic light pattern: Red, Yellow, Green, Red, Yellow, ...?',
    questionHe: 'אֵיזֶה צֶבֶע מַגִּיעַ הַבָּא בַּתּוֹר כְּדֵי לְהַשְׁלִים אֶת הַסִּדְרָה: אָדֹם, צָהֹב, יָרֹק, אָדֹם, צָהֹב, ...?',
    optionsEn: ['Green', 'Blue', 'Red', 'Pink'],
    optionsHe: ['יָרֹק', 'כָּחֹל', 'אָדֹם', 'וָרֹד'],
    answerIndex: 0,
    explanationEn: 'The pattern repeats the three colors of a traffic light: Red, Yellow, Green!',
    explanationHe: 'הסדרה חוזרת על שלושת צבעי הרמזור לפי הסדר: אדום, צהוב, ירוק!',
    visualType: 'pattern-complete'
  },
  {
    id: 'gk-5-story-pinocchio',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: "In the famous story, what happens to Pinocchio's nose when he tells a lie?",
    questionHe: 'בַּסִּפּוּר הַמְפֻרְסָם, מָה קוֹרֶה לָאַף שֶׁל פִּינוֹקְיוֹ כְּשֶׁהוּא מְשַׁקֵּר?',
    optionsEn: ['It gets longer', 'It turns blue', 'It disappears', 'It starts to wiggle'],
    optionsHe: ['הוּא מִתְאָרֵךְ', 'הוּא הֹפֵךְ לְכָחֹל', 'הוּא נֶעֱלָם', 'הוּא מַתְחִיל לְהִתְנַדְנֵד'],
    answerIndex: 0,
    explanationEn: "Pinocchio's wooden nose grows longer every time he tells a lie!",
    explanationHe: 'אפו של פינוקיו מעץ מתארך בכל פעם שהוא מספר שקר!'
  },
  {
    id: 'gk-5-story-goldilocks',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Whose house does Goldilocks visit in the forest?',
    questionHe: 'בְּבֵיתוֹ שֶׁל מִי מְבַקֶּרֶת זַהֲבָה בַּיַּעַר?',
    optionsEn: ['The Three Bears', 'The Little Red Hen', 'The Seven Dwarfs', 'The Three Little Pigs'],
    optionsHe: ['שְׁלֹשֶׁת הַדֻּבִּים', 'הַתַּרְנְגֹלֶת הָאֲדֻמָּה הַקְּטַנָּה', 'שִׁבְעַת הַגַּמָּדִים', 'הַחֲזִירוֹנִים הַקְּטַנִּים'],
    answerIndex: 0,
    explanationEn: 'Goldilocks enters the cottage of the Three Bears and tastes their porridge!',
    explanationHe: 'זהבה נכנסת לבקתה של שלושת הדובים וטועמת מהדייסה שלהם!'
  },
  {
    id: 'gk-5-visual-school-zone',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Look at the visual warning! What does this sign with two children walking mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר! מָה מַשְׁמָעוּת תַּמְרוּר זֶה שֶׁמַּרְאֶה שְׁנֵי יְלָדִים הוֹלְכִים?',
    optionsEn: ['School zone / children nearby', 'Toy store ahead', 'No children allowed', 'Playground closed'],
    optionsHe: ['אֵזוֹר בֵּית סֵפֶר / יְלָדִים בַּקִּרְבָה', 'חֲנוּת צַעֲצוּעִים לְפָנֶיךָ', 'הַכְּנִיסָה לִילָדִים אֲסוּרָה', 'גַּן הַשַּׂחֲקִים סָגוּר'],
    answerIndex: 0,
    explanationEn: 'The School Zone sign warns drivers to slow down because children are walking nearby!',
    explanationHe: 'תמרור אזור בית ספר מזהיר את הנהגים להאט כי ישנם ילדים שחוצים או הולכים בקרבת מקום!',
    visualType: 'school-zone-sign'
  },
  {
    id: 'gk-5-visual-slippery',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Look at the sign with a car and wiggly lines! What does this mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר עִם הַמְּכוֹנִית וְהַקַּוִּים הַמְפֻתָּלִים! מָה זֶה אוֹמֵר?',
    optionsEn: ['Slippery road ahead', 'Car wash ahead', 'Race track ahead', 'No cars allowed'],
    optionsHe: ['כְּבִישׁ חָלָק לְפָנֶיךָ', 'שְׁטִיפַת מְכוֹנִיּוֹת לְפָנֶיךָ', 'מַסְלוּל מֵרוֹצִים לְפָנֶיךָ', 'אֵין כְּנִיסָה לִמְכוֹנִיּוֹת'],
    answerIndex: 0,
    explanationEn: 'The slippery road sign warns drivers that the road can be very slippery, especially when it rains!',
    explanationHe: 'תמרור כביש חלק מזהיר נהגים שהכביש עלול להיות חלק מאוד, במיוחד כשיורד גשם!',
    visualType: 'slippery-road-sign'
  },
  {
    id: 'gk-5-visual-pedestrian',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Look at the blue square sign with a person walking. What does it mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הַכָּחֹל הַמְרֻבָּע עִם הָאִישׁ הַהוֹלֵךְ. מָה מַשְׁמָעוּתוֹ?',
    optionsEn: ['Pedestrian crossing / crosswalk', 'Running track ahead', 'No walking allowed', 'Airport nearby'],
    optionsHe: ['מַעֲבָר חֲצִיָּה לְהוֹלְכֵי רֶגֶל', 'מַסְלוּל רִיצָה לְפָנֶיךָ', 'אֲסוּרָה הַהֲלִיכָה בָּרֶגֶל', 'נְמַל תְּעוּפָה בַּקִּרְבָה'],
    answerIndex: 0,
    explanationEn: 'The pedestrian sign marks a crosswalk where drivers must stop to let people walk across the street safely.',
    explanationHe: 'תמרור מעבר חצייה מסמן לנהגים שעליהם לעצור כדי לאפשר להולכי רגל לחצות את הכביש בבטחה.',
    visualType: 'pedestrian-sign'
  },
  {
    id: 'gk-5-visual-count',
    category: 'GeneralKnowledge',
    ageGroup: '5-7',
    questionEn: 'Count the stars ⭐ in this colorful picture. How many stars can you find?',
    questionHe: 'סִפְרוּ אֶת הַכּוֹכָבִים ⭐ בַּתְּמוּנָה הַצִּבְעוֹנִית. כַּמָּה כּוֹכָבִים מְצָאתֶם?',
    optionsEn: ['4 stars', '5 stars', '3 stars', '6 stars'],
    optionsHe: ['4 כּוֹכָבִים', '5 כּוֹכָבִים', '3 כּוֹכָבִים', '6 כּוֹכָבִים'],
    answerIndex: 0,
    explanationEn: 'Let\'s count them: one, two, three, four! There are exactly 4 yellow stars in the picture!',
    explanationHe: 'בואו נספור אותם: אחד, שניים, שלושה, ארבעה! יש בדיוק 4 כוכבים צהובים בתמונה!',
    visualType: 'count-shapes'
  }
];
