import { Question } from './types';

export const GK_8_13_QUESTIONS: Question[] = [
  {
    id: 'gk-8-1',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many days are there in a leap year?',
    questionHe: 'כַּמָּה יָמִים יֵשׁ בְּשָׁנָה מְעֻבֶּרֶת (לֹא מַחְזוֹר עִבְרִי)?',
    optionsEn: ['365', '366', '364', '360'],
    optionsHe: ['365', '366', '364', '360'],
    answerIndex: 1,
    explanationEn: 'A leap year has 366 days instead of 365, adding February 29th.',
    explanationHe: 'שנה מעוברת כוללת 366 ימים כדי להתאים את לוח השנה לסיבוב כדור הארץ.'
  },
  {
    id: 'gk-8-2',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many continents are there on planet Earth?',
    questionHe: 'כַּמָּה יַבָּשׁוֹת יֵשׁ בְּכַדּוּר הָאָרֶץ?',
    optionsEn: ['5', '6', '7', '8'],
    optionsHe: ['5', '6', '7', '8'],
    answerIndex: 2,
    explanationEn: 'The seven continents are Asia, Africa, North America, South America, Antarctica, Europe, and Australia.',
    explanationHe: 'שבע היבשות הן אסיה, אפריקה, אמריקה הצפונית, אמריקה הדרומית, אנטארקטיקה, אירופה ואוסטרליה.'
  },
  {
    id: 'gk-8-3',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which planet is the closest to our Sun?',
    questionHe: 'אֵיזֶה כּוֹכַב לֶכֶת הוּא הַקָּרוֹב בְּיוֹתֵר לַשֶּׁמֶשׁ?',
    optionsEn: ['Venus', 'Mercury', 'Mars', 'Earth'],
    optionsHe: ['נוֹגַהּ', 'כּוֹכַב חַמָּה (מֶרְקוּרִי)', 'מַאֲדִים', 'כַּדּוּר הָאָרֶץ'],
    answerIndex: 1,
    explanationEn: 'Mercury is the closest planet to the Sun and has no atmosphere to retain heat.',
    explanationHe: 'כוכב חמה הוא הקרוב ביותר לשמש והוא גם כוכב הלכת הקטן ביותר.'
  },
  {
    id: 'gk-8-4',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the hardest natural substance found on Earth?',
    questionHe: 'מַהוּ הַחֹמֶר הַטִּבְעִי הַקָּשֶׁה בְּיוֹתֵר בָּעוֹלָם?',
    optionsEn: ['Gold', 'Iron', 'Diamond', 'Marble'],
    optionsHe: ['זָהָב', 'בַּרְזֶל', 'יַהֲלֹם', 'שַׁיִשׁ'],
    answerIndex: 2,
    explanationEn: 'Diamonds are made of carbon atoms packed tightly, making them incredibly hard.',
    explanationHe: 'יהלום הוא החומר הטבעי החזק והקשה ביותר בזכות מבנה אטומי הפחמן שלו.'
  },
  {
    id: 'gk-8-5',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which part of the human body pumps blood to all other organs?',
    questionHe: 'אֵיזֶה אֵיבָר בְּגוּף הָאָדָם מַזְרִים דָּם לְכָל שְׁאָר הָאֵיבָרִים?',
    optionsEn: ['Brain', 'Lungs', 'Heart', 'Stomach'],
    optionsHe: ['מוֹחַ', 'רֵאוֹת', 'לֵב', 'קֵבָה'],
    answerIndex: 2,
    explanationEn: 'The heart is a powerful muscle that beats constantly to pump oxygen-rich blood.',
    explanationHe: 'הלב הוא משאבה שרירית חזקה הפועמת ללא הפסקה כדי להזרים חמצן לכל הגוף.'
  },
  {
    id: 'gk-8-6',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Who was the first President of the United States?',
    questionHe: 'מִי הָיָה הַנָּשִׂיא הָרִאשׁוֹן שֶׁל אַרְצוֹת הַבְּרִית?',
    optionsEn: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'],
    optionsHe: ['תּוֹמָאס גֶ׳פֶרְסוֹן', 'אַבְרָהָם לִינְקוֹלְן', 'ג׳וֹרְג׳ וָשִׁינְגְטוֹן', 'ג׳וֹן אָדָמְס'],
    answerIndex: 2,
    explanationEn: 'George Washington served as the first president from 1789 to 1797.',
    explanationHe: 'ג׳ורג׳ וושינגטון היה מפקד הצבא והנשיא הראשון של ארצות הברית.'
  },
  {
    id: 'gk-8-7',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the name of the imaginary line that circles Earth halfway between the poles?',
    questionHe: 'מַהוּ שְׁמוֹ שֶׁל קַו הַדִּמְיוֹן הַמַּקִּיף אֶת כַּדּוּר הָאָרֶץ וּמְחַלֵּק אוֹתוֹ לִשְׁנֵי חֲצָאִים?',
    optionsEn: ['Equator', 'Prime Meridian', 'Tropic of Cancer', 'Antarctic Circle'],
    optionsHe: ['קוֹ מַשְׁוֶה', 'קַו גְּרִינִיץ׳', 'חוּג הַסַּרְטָן', 'הַקֹּטֶב הַדְּרוֹמִי'],
    answerIndex: 0,
    explanationEn: 'The Equator is an imaginary line of latitude that is exceptionally hot year-round.',
    explanationHe: 'קו המשווה מחלק את כדור הארץ לחצי הכדור הצפוני וחצי הכדור הדרומי.'
  },
  {
    id: 'gk-8-8',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which language is natively spoken by the largest number of people in the world?',
    questionHe: 'אֵיזוֹ שָׂפָה מְדֻבֶּרֶת כִּשְׂפַת אֵם בְּפִי מִסְפַּר הָאֲנָשִׁים הַגָּדוֹל בָּעוֹלָם?',
    optionsEn: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'],
    optionsHe: ['אַנְגְּלִית', 'סְפָּרַדִּית', 'סִינִית מַנְדָּרִינִית', 'הִינְדִּי'],
    answerIndex: 2,
    explanationEn: 'Mandarin Chinese is natively spoken by over 900 million people, mostly in China.',
    explanationHe: 'סינית מנדרינית היא שפת האם המדוברת ביותר בעולם בזכות האוכלוסייה הגדולה בסין.'
  },
  {
    id: 'gk-8-9',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which continent is the smallest by total land area?',
    questionHe: 'אֵיזוֹ יַבָּשֶׁת הִיא הַקְּטַנָּה בְּיוֹתֵר בְּשִׁטְחָהּ?',
    optionsEn: ['Europe', 'Antarctica', 'Australia', 'South America'],
    optionsHe: ['אֵירוֹפָּה', 'אַנְטָארְקְטִיקָה', 'אוֹסְטְרַלְיָה', 'אָמֶרִיקָה הַדְּרוֹמִית'],
    answerIndex: 2,
    explanationEn: 'Australia (also known as Oceania) is the smallest continent, but it is very diverse!',
    explanationHe: 'אוסטרליה היא היבשת הקטנה ביותר בעולם, והיא מוקפת כולה באוקיינוסים.'
  },
  {
    id: 'gk-8-10',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What do we call a scientist who specializes in studying space, stars, and planets?',
    questionHe: 'אֵיךְ מְכֻנֶּה מַדְּעָן הַחוֹקֵר אֶת הֶחָלָל, הַכּוֹכָבִים וְכוֹכְבֵי הַלֶּכֶת?',
    optionsEn: ['Biologist', 'Geologist', 'Astronomer', 'Chemist'],
    optionsHe: ['בִּיּוֹלוֹג', 'גֵּאוֹלוֹג', 'אַסְטְרוֹנוֹם', 'כִימַאי'],
    answerIndex: 2,
    explanationEn: 'Astronomers use giant telescopes and satellites to look into outer space.',
    explanationHe: 'אסטרונומים משתמשים בטלסקופים ולוויינים כדי לחקור את מסתורי היקום.'
  },
  {
    id: 'gk-8-11',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many teeth does a fully grown adult human typically have?',
    questionHe: 'כַּמָּה שִׁנַּיִם יֵשׁ לְאָדָם בּוֹגֵר בְּאֹפֶן תַּקִּין?',
    optionsEn: ['24', '28', '32', '36'],
    optionsHe: ['24', '28', '32', '36'],
    answerIndex: 2,
    explanationEn: 'Adults have 32 teeth, which includes 4 wisdom teeth at the back.',
    explanationHe: 'לאדם בוגר יש בדרך כלל 32 שיניים, כולל 4 שיני בינה.'
  },
  {
    id: 'gk-8-12',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What gas do green plants absorb from the atmosphere to perform photosynthesis?',
    questionHe: 'אֵיזֶה גַּז קוֹלְטִים צְמָחִים יְרֻקִּים מֵהָאֲוִיר כְּדֵי לְבַצֵּעַ פוֹטוֹסִינְתֶּזָה?',
    optionsEn: ['Oxygen', 'Hydrogen', 'Carbon Dioxide', 'Helium'],
    optionsHe: ['חַמְצָן', 'מֵימָן', 'דּוּ-פַחְמָן חַמְצָנִי', 'הֶלְיוּם'],
    answerIndex: 2,
    explanationEn: 'Plants take in Carbon Dioxide and release clean Oxygen into the air for us to breathe.',
    explanationHe: 'הצמחים קולטים דו-פחמן חמצני ופולטים חמצן, המסייע לנו לנשום ולחיות.'
  },
  {
    id: 'gk-8-13',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which musical instrument has black and white keys, hammers, and strings inside?',
    questionHe: 'אֵיזֶה כְּלִי נְגִינָה מְצֻיָּד בִּקְלִידִים שְׁחֹרִים וּלְבָנִים, מַקָּשִׁים וּמֵיתָרִים מִבִּפְנִים?',
    optionsEn: ['Violin', 'Guitar', 'Piano', 'Flute'],
    optionsHe: ['כִּנּוֹר', 'גִּיטָרָה', 'פְּסַנְתֵּר', 'חָלִיל'],
    answerIndex: 2,
    explanationEn: 'The piano was invented in Italy by Bartolomeo Cristofori around the year 1700.',
    explanationHe: 'הפסנתר הומצא באיטליה ומפיק צליל באמצעות פטישים קטנים המכים במיתרים.'
  },
  {
    id: 'gk-8-14',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What are the three primary states of matter?',
    questionHe: 'מָה הֵם שְׁלוֹשֶׁת מַצְּבֵי הַצְּבִירָה הָעִקָּרִיִּים שֶׁל הַחֹמֶר?',
    optionsEn: ['Hot, Cold, Warm', 'Solid, Liquid, Gas', 'Fire, Water, Air', 'Heavy, Light, Medium'],
    optionsHe: ['חם, קר, פושר', 'מוּצָק, נוֹזֵל, גַּז', 'אש, מים, אוויר', 'כבד, קל, בינוני'],
    answerIndex: 1,
    explanationEn: 'Everything around us is in solid, liquid, or gas form. Water can easily be all three!',
    explanationHe: 'חומרים קיימים בטבע בצורת מוצק, נוזל או גז (למשל: קרח, מים ואדים).'
  },
  {
    id: 'gk-8-15',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the boiling point of pure water in Celsius at sea level?',
    questionHe: 'מָהִי נְקֻדַּת הָרְתִיחָה שֶׁל מַיִם מְזֻקָּקִים בְּמַעֲלוֹת צֶלְסִיּוּס?',
    optionsEn: ['50 degrees', '100 degrees', '150 degrees', '200 degrees'],
    optionsHe: ['50 מעלות', '100 מַעֲלוֹת', '150 מעלות', '200 מעלות'],
    answerIndex: 1,
    explanationEn: 'Water boils and turns into steam at exactly 100 degrees Celsius (212 degrees Fahrenheit).',
    explanationHe: 'בגובה פני הים, מים רותחים והופכים לאדים בטמפרטורה של 100 מעלות צלזיוס.'
  },
  {
    id: 'gk-8-16',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which European country is famous for the Eiffel Tower in its capital city?',
    questionHe: 'אֵיזוֹ מְדִינָה אֵירוֹפֵּאִית מְפֻרְסֶמֶת בִּבְנִיַּת מִגְדַּל אָיְפֶל בְּעִיר הַבִּירָה שֶׁלָּהּ?',
    optionsEn: ['Germany', 'Italy', 'France', 'Spain'],
    optionsHe: ['גֶּרְמַנְיָה', 'אִיטַלְיָה', 'צָרְפַת', 'סְפָרַד'],
    answerIndex: 2,
    explanationEn: 'The Eiffel Tower is located in Paris, France, and was built for the 1889 World’s Fair.',
    explanationHe: 'מגדל אייפל ממוקם בפריז, בירת צרפת, ונבנה בשנת 1889.'
  },
  {
    id: 'gk-8-17',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What color is the precious gemstone emerald?',
    questionHe: 'בְּאֵיזֶה צֶבֶע אֶבֶן הַחֵן הַיְּקָרָה בָּרֶקֶת (אֵמֶרַלְד)?',
    optionsEn: ['Red', 'Green', 'Blue', 'Yellow'],
    optionsHe: ['אָדֹם', 'יָרֹק', 'כָּחֹל', 'צָהֹב'],
    answerIndex: 1,
    explanationEn: 'Emeralds are famous for their rich, brilliant green color, derived from chromium and vanadium.',
    explanationHe: 'אבני ברקת (אזמרגד) ידועות בגוון הירוק העמוק והמרהיב שלהן.'
  },
  {
    id: 'gk-8-18',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'The famous Sahara Desert is located in which continent?',
    questionHe: 'מִדְבַּר סַהָרָה הַמְּפֻרְסָם שׁוֹכֵן בְּאֵיזוֹ יַבָּשֶׁת?',
    optionsEn: ['Asia', 'Africa', 'South America', 'Australia'],
    optionsHe: ['אַסְיָה', 'אַפְרִיקָה', 'אָמֶרִיקָה הַדְּרוֹמִית', 'אוֹסְטְרַלְיָה'],
    answerIndex: 1,
    explanationEn: 'The Sahara Desert covers a massive portion of Northern Africa, stretching across 11 countries.',
    explanationHe: 'מדבר סהרה הוא מדבר החול הגדול בעולם והוא משתרע בצפון אפריקה.'
  },
  {
    id: 'gk-8-19',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which Italian city is famous for its leaning medieval bell tower?',
    questionHe: 'אֵיזוֹ עִיר אִיטַלְקִית מְפֻרְסֶמֶת בְּמִגְדַּל הַפַּעֲמוֹנִים הַנָּטוּי שֶׁלָּהּ?',
    optionsEn: ['Rome', 'Venice', 'Pisa', 'Florence'],
    optionsHe: ['רוֹמָא', 'וֵנֵצְיָה', 'פִּיזָה', 'פְלוֹרֶנְץ'],
    answerIndex: 2,
    explanationEn: 'The Leaning Tower of Pisa tilted because the foundation was built on soft, unstable ground.',
    explanationHe: 'מגדל פיזה המפורסם נוטה על צדו בגלל יסודות שנבנו על אדמה בוצית רכה.'
  },
  {
    id: 'gk-8-20',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What sweet substance do bees collect from flowers to turn into honey?',
    questionHe: 'אֵיזֶה נוֹזֵל מָתוֹק אוֹסְפוֹת הַדְּבוֹרִים מִפְּרָחִים כְּדֵי לְהָכִין דְּבַשׁ?',
    optionsEn: ['Water', 'Nectar', 'Pollen', 'Sap'],
    optionsHe: ['מים', 'צוּף (נֶקְטָר)', 'אבקת פרחים', 'שרף'],
    answerIndex: 1,
    explanationEn: 'Bees sip sugary nectar and deposit it back at their hive to make sweet honey.',
    explanationHe: 'הדבורים מוצצות את הצוף המתוק של הפרחים והופכות אותו לדבש בכוורת.'
  },
  {
    id: 'gk-8-21',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the primary official language spoken in Brazil?',
    questionHe: 'מָהִי הַשָּׂפָה הָרִשְׁמִית הָעִקָּרִית הַמְּדֻבֶּרֶת בִּבְרָזִיל?',
    optionsEn: ['Spanish', 'French', 'Portuguese', 'English'],
    optionsHe: ['סְפָּרַדִּית', 'צָרְפַתִית', 'פּוֹרְטוּגֶזִית', 'אַנְגְּלִית'],
    answerIndex: 2,
    explanationEn: 'Unlike most of South America, Brazil was colonized by Portugal, so they speak Portuguese!',
    explanationHe: 'בשונה מרוב מדינות דרום אמריקה הדוברות ספרדית, בברזיל השפה הרשמית היא פורטוגזית.'
  },
  {
    id: 'gk-8-22',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many bones are in a fully developed adult human skeleton?',
    questionHe: 'כַּמָּה עֲצָמוֹת יֵשׁ בְּשֶׁלֶד שֶׁל אָדָם בּוֹגֵר?',
    optionsEn: ['106', '206', '306', '156'],
    optionsHe: ['106', '206', '306', '156'],
    answerIndex: 1,
    explanationEn: 'Babies are born with around 270 soft bones, but they fuse together to form 206 hard bones in adulthood.',
    explanationHe: 'תינוק נולד עם כ-270 עצמות, אך חלקן מתאחות במהלך הגדילה ובגוף בוגר יש 206 עצמות.'
  },
  {
    id: 'gk-8-23',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the name of the official currency used in Japan?',
    questionHe: 'מַהוּ שְׁמָהּ שֶׁל הַמַּטְבֵּעַ הָרִשְׁמִי הַנָּהוּג בְּיַפָּן?',
    optionsEn: ['Dollar', 'Yen', 'Euro', 'Won'],
    optionsHe: ['דּוֹלָר', 'יֶן', 'אִירוֹ', 'ווֹן'],
    answerIndex: 1,
    explanationEn: 'The Yen is the currency of Japan, symbolized by a capital Y with two horizontal strokes (¥).',
    explanationHe: 'המטבע של יפן נקרא ין (Yen), והוא אחד המטבעות הנסחרים ביותר בעולם.'
  },
  {
    id: 'gk-8-24',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which animal is the largest and tallest living bird on Earth?',
    questionHe: 'אֵיזֶה בַּעַל חַיִּים הוּא הַצִּפּוֹר הַגְּדוֹלָה וְהַגְּבוֹהָה בְּיוֹתֵר כַּיּוֹם?',
    optionsEn: ['Eagle', 'Ostrich', 'Albatross', 'Penguin'],
    optionsHe: ['עַיִט', 'יָעֵן (אוֹסְטְרִיץ׳)', 'אַלְבַּטְרוֹס', 'פִּינְגְּוִוין'],
    answerIndex: 1,
    explanationEn: 'The ostrich is a flightless bird that can grow up to 2.8 meters tall and run exceptionally fast!',
    explanationHe: 'היען היא הציפור הגדולה ביותר. היא אינה עפה אך רצה במהירות גבוהה מאוד.'
  },
  {
    id: 'gk-8-25',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which legendary writer wrote the famous play "Romeo and Juliet"?',
    questionHe: 'מִי הַמַּחֲזַאי הָאַנְגְּלִי הַמְּפֻרְסָם שֶׁכָּתַב אֶת הַמַּחֲזֶה "רוֹמֵאוֹ וְגוּלְיֶט"?',
    optionsEn: ['Mark Twain', 'William Shakespeare', 'Charles Dickens', 'J.K. Rowling'],
    optionsHe: ['מַארְק טְוֵוין', 'וִילְיָאם שֵׁקְסְפִּיר', 'צ׳ארְלְס דִּיקֶנְס', 'ג׳יי קיי רולינג'],
    answerIndex: 1,
    explanationEn: 'William Shakespeare was an English playwright and poet who wrote Romeo and Juliet in the late 1500s.',
    explanationHe: 'ויליאם שקספיר כתב את רומיאו ויוליה וכן עשרות מחזות ושירים מפורסמים נוספים.'
  },
  {
    id: 'gk-8-26',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What was the historic ancient name of the Turkish city of Istanbul?',
    questionHe: 'מָה הָיָה שְׁמָהּ הַהִיסְטוֹרִי הָעַתִּיק שֶׁל הָעִיר הַטֻּרְקִית אִיסְטַנְבּוּל?',
    optionsEn: ['Constantinople', 'Rome', 'Alexandria', 'Athens'],
    optionsHe: ['קוֹנְסְטַנְטִינוֹפּוֹל', 'רוֹמָא', 'אלכסנדריה', 'אתונה'],
    answerIndex: 0,
    explanationEn: 'Istanbul was known as Constantinople, named after the Roman emperor Constantine the Great.',
    explanationHe: 'לפני שנקראה איסטנבול, העיר הייתה בירת האימפריה הביזנטית ונקראה קונסטנטינופול.'
  },
  {
    id: 'gk-8-27',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many colors make up a standard natural rainbow?',
    questionHe: 'כַּמָּה צְבָעִים מַרְכִּיבִים אֶת קֶשֶׁת בֶּעָנָן הַטִּבְעִית?',
    optionsEn: ['5', '6', '7', '8'],
    optionsHe: ['5', '6', '7', '8'],
    answerIndex: 2,
    explanationEn: 'The 7 traditional colors are Red, Orange, Yellow, Green, Blue, Indigo, and Violet.',
    explanationHe: 'שבעת צבעי הקשת הם אדום, כתום, צהוב, ירוק, כחול, אינדיגו וסגול.'
  },
  {
    id: 'gk-8-28',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the primary natural raw ingredient used to make paper?',
    questionHe: 'מָה הָרְכִיב הַטִּבְעִי הָרִאשׁוֹנִי הַמְּשַׁמֵּשׁ לְיִצּוּר נְיָר?',
    optionsEn: ['Sand', 'Wood/Trees', 'Oil', 'Cotton'],
    optionsHe: ['חול', 'עֵץ / סִיבֵי תָּאִים', 'נפט', 'כותנה'],
    answerIndex: 1,
    explanationEn: 'Paper is manufactured from wood pulp, which comes from trees.',
    explanationHe: 'נייר מיוצר בדרך כלל מתאית עץ המופקת מגזעי עצמים בתעשיית היערנות.'
  },
  {
    id: 'gk-8-29',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which continent contains the largest number of sovereign countries?',
    questionHe: 'בְּאֵיזוֹ יַבָּשֶׁת יֵשׁ אֶת מִסְפַּר הַמְּדִינוֹת הָעַצְמָאִיּוֹת הַגָּדוֹל בְּיוֹתֵר?',
    optionsEn: ['Asia', 'Europe', 'Africa', 'North America'],
    optionsHe: ['אַסְיָה', 'אֵירוֹפָּה', 'אַפְרִיקָה', 'אמריקה הצפונית'],
    answerIndex: 2,
    explanationEn: 'Africa has 54 fully recognized independent countries, more than any other continent.',
    explanationHe: 'באפריקה יש 54 מדינות ריבוניות, יותר מכל יבשת אחרת.'
  },
  {
    id: 'gk-8-30',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Who painted the legendary "Mona Lisa" portrait in the early 16th century?',
    questionHe: 'מִי צִיֵּר אֶת דְּמוּתָהּ הַמִּסְתּוֹרִית שֶׁל הַ-"מוֹנָה לִיזָה"?',
    optionsEn: ['Vincent van Gogh', 'Michelangelo', 'Leonardo da Vinci', 'Pablo Picasso'],
    optionsHe: ['וִינְסֶנְט וַאן גּוֹךְ', 'מיכלאנג׳לו', 'לֵאוֹנַרְדּוֹ דָּה וִינְצ׳ִי', 'פאבלו פיקאסו'],
    answerIndex: 2,
    explanationEn: 'Leonardo da Vinci painted the Mona Lisa in Florence, Italy, and it now hangs in the Louvre Museum in Paris.',
    explanationHe: 'לאונרדו דה וינצ׳י האיטלקי צייר את המונה ליזה, הציור המפורסם ביותר בעולם.'
  },
  {
    id: 'gk-8-31',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What is the largest physical organ of the entire human body?',
    questionHe: 'מַהוּ הָאֵיבָר הַגָּדוֹל בְּיוֹתֵר בְּגוּף הָאָדָם?',
    optionsEn: ['Liver', 'Brain', 'Skin', 'Lungs'],
    optionsHe: ['כָּבֵד', 'מוח', 'עוֹר', 'ריאות'],
    answerIndex: 2,
    explanationEn: 'The skin is an organ that covers the entire body surface, protecting it from germs and injury.',
    explanationHe: 'העור הוא האיבר הגדול ביותר בגוף האדם, המגן עלינו מפני הסביבה החיצונית.'
  },
  {
    id: 'gk-8-32',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which ancient country is famous for inventing paper, silk, and gunpowder?',
    questionHe: 'אֵיזוֹ מְדִינָה עַתִּיקָה הִמְצִיאָה אֶת הַנְּיָר, הַמֶּשִׁי וַאֲבַק הַשְּׂרֵפָה?',
    optionsEn: ['Egypt', 'Rome', 'China', 'Greece'],
    optionsHe: ['מִצְרַיִם', 'רומא', 'סִין', 'יוון'],
    answerIndex: 2,
    explanationEn: 'Ancient China invented paper-making, the magnetic compass, printing, and gunpowder!',
    explanationHe: 'סין העתיקה היא ערש ההמצאות הגדולות כמו נייר, מצפן, דפוס ואבק שריפה.'
  },
  {
    id: 'gk-8-33',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many seconds are contained within one minute?',
    questionHe: 'כַּמָּה שְׁנִיּוֹת יֵשׁ בְּדַקָּה אַחַת?',
    optionsEn: ['30', '60', '100', '120'],
    optionsHe: ['30', '60', '100', '120'],
    answerIndex: 1,
    explanationEn: 'There are exactly 60 seconds in a minute, and 60 minutes in an hour.',
    explanationHe: 'יש בדיוק 60 שניות בדקה אחת, והיא מבוססת על שיטת ספירה עתיקה מבבל.'
  },
  {
    id: 'gk-8-34',
    category: 'Space',
    ageGroup: '8-13',
    questionEn: 'Which is the smallest planet in our solar system?',
    questionHe: 'מַהוּ כּוֹכַב הַלֶּכֶת הַקָּטָן בְּיוֹתֵר בְּמַעֲרֶכֶת הַשֶּׁמֶשׁ?',
    optionsEn: ['Mars', 'Mercury', 'Venus', 'Neptune'],
    optionsHe: ['מַאֲדִים', 'כּוֹכַב חַמָּה (מֶרְקוּרִי)', 'נוֹגַהּ', 'נֶפְּטוּן'],
    answerIndex: 1,
    explanationEn: 'Mercury is the smallest planet in our solar system and also the closest to the Sun.',
    explanationHe: 'כוכב חמה (מרקורי) הוא כוכב הלכת הקטן ביותר במערכת השמש והקרוב ביותר לשמש.'
  },
  {
    id: 'gk-8-35',
    category: 'Science',
    ageGroup: '8-13',
    questionEn: 'What gas do humans need to breathe to stay alive?',
    questionHe: 'אֵיזֶה גָּז בְּנֵי אָדָם צְרִיכִים לִנְשֹׁם כְּדֵי לִחְיוֹת?',
    optionsEn: ['Carbon Dioxide', 'Nitrogen', 'Oxygen', 'Helium'],
    optionsHe: ['פחמן דו-חמצני', 'חנקן', 'חַמְצָן', 'הליום'],
    answerIndex: 2,
    explanationEn: 'Oxygen is essential for the cells in our body to create energy from food.',
    explanationHe: 'החמצן הוא גז חיוני לנשימה המאפשר לתאים בגופנו להפיק אנרגיה.'
  },
  {
    id: 'gk-8-36',
    category: 'Math',
    ageGroup: '8-13',
    questionEn: 'What is 12 multiplied by 5?',
    questionHe: 'כַּמָּה זֶה 12 כָּפוּל 5?',
    optionsEn: ['50', '55', '60', '65'],
    optionsHe: ['50', '55', '60', '65'],
    answerIndex: 2,
    explanationEn: '12 times 5 equals 60. You can think of it as 10 times 5 (50) plus 2 times 5 (10).',
    explanationHe: '12 כפול 5 הם 60. אפשר לחשב זאת כ-10 כפול 5 ועוד 2 כפול 5.'
  },
  {
    id: 'gk-8-37',
    category: 'Geography',
    ageGroup: '8-13',
    questionEn: 'What is the longest river in the world?',
    questionHe: 'מַהוּ הַנָּהָר הָאָרֹךְ בְּיוֹתֵר בָּעוֹלָם?',
    optionsEn: ['Amazon River', 'Nile River', 'Mississippi River', 'Yangtze River'],
    optionsHe: ['נְהַר הָאָמָזוֹנָס', 'נְהַר הַנִּילוּס', 'נהר המיסיסיפי', 'נהר היאנגצה'],
    answerIndex: 1,
    explanationEn: 'The Nile River in Africa is traditionally considered the longest river, stretching over 6,650 kilometers.',
    explanationHe: 'נהר הנילוס הזורם באפריקה נחשב לנהר הארוך ביותר בעולם, באורך של כ-6,650 ק״מ.'
  },
  {
    id: 'gk-8-38',
    category: 'Animals',
    ageGroup: '8-13',
    questionEn: 'Which mammal is known to be able to fly?',
    questionHe: 'אֵיזֶה יוֹנֵק מְסֻגָּל לָעוּף בַּאֲוִיר?',
    optionsEn: ['Flying Squirrel', 'Bat', 'Eagle', 'Owl'],
    optionsHe: ['סנאי מעופף', 'עֲטַלֵּף', 'עיט', 'ינשוף'],
    answerIndex: 1,
    explanationEn: 'Bats are the only mammals capable of sustained, flapping flight, using modified skin webbing.',
    explanationHe: 'עטלפים הם היונקים היחידים שמסוגלים לעוף באמת באמצעות כנפי עור מיוחדות.'
  },
  {
    id: 'gk-8-39',
    category: 'History',
    ageGroup: '8-13',
    questionEn: 'Who was the first President of the United States?',
    questionHe: 'מִי הָיָה הַנָּשִׂיא הָרִאשׁוֹן שֶׁל אַרְצוֹת הַבְּרִית?',
    optionsEn: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams'],
    optionsHe: ['תומאס ג׳פרסון', 'ג׳וֹרְג׳ ווֹשִׁינְגְטוֹן', 'אברהם לינקולן', 'ג׳ון אדמס'],
    answerIndex: 1,
    explanationEn: 'George Washington served as the first president from 1789 to 1797 after leading the Continental Army.',
    explanationHe: 'ג׳ורג׳ וושינגטון היה נשיאה הראשון של ארצות הברית, והוביל אותה לעצמאות.'
  },
  {
    id: 'gk-8-40',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many colors are in a standard rainbow?',
    questionHe: 'כַּמָּה צְבָעִים יֵשׁ בְּקֶשֶׁת בֶּעָנָן תִּקְנִית?',
    optionsEn: ['5', '6', '7', '8'],
    optionsHe: ['5', '6', '7', '8'],
    answerIndex: 2,
    explanationEn: 'A rainbow has 7 colors: Red, Orange, Yellow, Green, Blue, Indigo, and Violet (ROYGBIV).',
    explanationHe: 'בקשת בענן יש שבעה צבעים: אדום, כתום, צהוב, ירוק, כחול, אינדיגו וסגול.'
  },
  {
    id: 'gk-8-41',
    category: 'Space',
    ageGroup: '8-13',
    questionEn: 'Which planet is famous for its beautiful and large ring system?',
    questionHe: 'אֵיזֶה כּוֹכַב לֶכֶת מְפֻרְסָם בְּמַעֲרֶכֶת הַטַּבָּעוֹת הַגְּדוֹלָה שֶׁלּוֹ?',
    optionsEn: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    optionsHe: ['צדק', 'שַׁבְּתַאי (סָטוּרְן)', 'אורנוס', 'נפטון'],
    answerIndex: 1,
    explanationEn: 'Saturn has spectacular, bright rings made of billions of ice particles, rocky debris, and dust.',
    explanationHe: 'שבתאי ידוע בטבעות המרשימות והמרהיבות שלו, המורכבות בעיקר מגושי קרח ואבק.'
  },
  {
    id: 'gk-8-42',
    category: 'Science',
    ageGroup: '8-13',
    questionEn: 'What force pulls objects down to the ground on Earth?',
    questionHe: 'אֵיזֶה כֹּחַ מוֹשֵׁךְ חֲפָצִים כְּלַפֵּי מַטָּה אֶל הָאֲדָמָה?',
    optionsEn: ['Magnetism', 'Gravity', 'Friction', 'Electricity'],
    optionsHe: ['מגנטיות', 'כֹּחַ הַכְּבִידָה (גרביטציה)', 'חיכוך', 'חשמל'],
    answerIndex: 1,
    explanationEn: 'Gravity is the invisible force that attracts any objects with mass toward each other.',
    explanationHe: 'כוח הכבידה (גרביטציה) הוא הכוח שמושך אותנו ואת כל החפצים לכיוון מרכז כדור הארץ.'
  },
  {
    id: 'gk-8-43',
    category: 'Geography',
    ageGroup: '8-13',
    questionEn: 'Which is the largest hot desert in the world?',
    questionHe: 'מַהוּ הַמִּדְבָּר הַחַם הַגָּדוֹל בְּיוֹתֵר בָּעוֹלָם?',
    optionsEn: ['Gobi Desert', 'Kalahari Desert', 'Sahara Desert', 'Mojave Desert'],
    optionsHe: ['מדבר גובי', 'מדבר קלהארי', 'מִדְבַּר סַהָרָה', 'מדבר מוהאבי'],
    answerIndex: 2,
    explanationEn: 'The Sahara Desert covers over 9 million square kilometers, spanning much of North Africa.',
    explanationHe: 'מדבר סהרה בצפון אפריקה הוא מדבר החול החם הגדול ביותר בעולם.'
  },
  {
    id: 'gk-8-44',
    category: 'Animals',
    ageGroup: '8-13',
    questionEn: 'How many legs does an octopus have?',
    questionHe: 'כַּמָּה זְרוֹעוֹת אוֹ רַגְלַיִם יֵשׁ לִתְמָנוּן?',
    optionsEn: ['6', '8', '10', '12'],
    optionsHe: ['6', '8', '10', '12'],
    answerIndex: 1,
    explanationEn: 'An octopus has 8 limbs (typically called arms or tentacles) which it uses to swim, feel, and grab food.',
    explanationHe: 'לתמנון יש שמונה זרועות המכוסות כפתורי הצמדה המאפשרים לו לזחול ולאחוז דברים.'
  },
  {
    id: 'gk-8-45',
    category: 'Math',
    ageGroup: '8-13',
    questionEn: 'What is the perimeter of a square with a side length of 4 cm?',
    questionHe: 'מַהוּ הֵקֵף רִבּוּעַ שֶׁאֹרֶךְ צַלְעוֹ 4 ס״מ?',
    optionsEn: ['8 cm', '12 cm', '16 cm', '20 cm'],
    optionsHe: ['8 ס״מ', '12 ס״מ', '16 ס״מ', '20 ס״מ'],
    answerIndex: 2,
    explanationEn: 'The perimeter of a square is 4 times the side length: 4 cm x 4 = 16 cm.',
    explanationHe: 'היקף ריבוע מחושב על ידי חיבור ארבעת צלעותיו השוות: 4 כפול 4 שווה ל-16 ס״מ.'
  },
  {
    id: 'gk-8-46',
    category: 'History',
    ageGroup: '8-13',
    questionEn: 'Which ancient civilization built the great pyramids of Giza?',
    questionHe: 'אֵיזֶה עַם עַתִּיק בָּנָה אֶת הַפִּירָמִידוֹת הַגְּדוֹלוֹת שֶׁל גִּיזָה?',
    optionsEn: ['Ancient Romans', 'Ancient Greeks', 'Ancient Egyptians', 'Mayans'],
    optionsHe: ['הרומאים', 'היוונים', 'הַמִּצְרִים הַקַּדְמוֹנִים', 'בני המאיה'],
    answerIndex: 2,
    explanationEn: 'The Ancient Egyptians built the pyramids as monumental tombs for their Pharaohs, aligned with stars.',
    explanationHe: 'המצרים הקדמונים בנו את הפירמידות כקברים אדירים למלכים (פרעונים) שלהם.'
  },
  {
    id: 'gk-8-47',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which is the largest continent on Earth?',
    questionHe: 'מַהִי הַיַּבֶּשֶׁת הַגָּדוֹלָה בְּיוֹתֵר בְּכַדּוּר הָאָרֶץ?',
    optionsEn: ['Africa', 'North America', 'Asia', 'Europe'],
    optionsHe: ['אפריקה', 'צפון אמריקה', 'אַסְיָה', 'אירופה'],
    answerIndex: 2,
    explanationEn: 'Asia is the largest continent in both land area and population, covering 30% of Earth’s land area.',
    explanationHe: 'אסיה היא היבשת הגדולה ביותר בשטחה וגם המאוכלסת ביותר בכדור הארץ.'
  },
  {
    id: 'gk-8-48',
    category: 'Space',
    ageGroup: '8-13',
    questionEn: 'What is the name of our spiral galaxy?',
    questionHe: 'מַהוּ שְׁמָהּ שֶׁל הַגָּלַקְסִיָּה שֶׁלָּנוּ?',
    optionsEn: ['Andromeda', 'Milky Way', 'Sombrero', 'Triangulum'],
    optionsHe: ['אנדרומדה', 'שְׁבִיל הַחָלָב', 'סומבררו', 'משולש'],
    answerIndex: 1,
    explanationEn: 'Our solar system is located in the Milky Way galaxy, which contains billions of stars.',
    explanationHe: 'מערכת השמש שלנו ממוקמת בתוך גלקסיה ספירלית הנקראת שביל החלב.'
  },
  {
    id: 'gk-8-49',
    category: 'Science',
    ageGroup: '8-13',
    questionEn: 'What do we call a scientist who studies rocks and the history of Earth?',
    questionHe: 'אֵיךְ קוֹרְאִים לְמַדָּעָן שֶׁחֹקֵר סְלָעִים וְאֶת הַהִיסְטוֹרְיָה שֶׁל כַּדּוּר הָאָרֶץ?',
    optionsEn: ['Biologist', 'Geologist', 'Chemist', 'Physicist'],
    optionsHe: ['ביולוג', 'גֵּאוֹלוֹג', 'כימאי', 'פיזיקאי'],
    answerIndex: 1,
    explanationEn: 'Geologists study rock formations, earthquakes, and volcanoes to understand how Earth formed and changed.',
    explanationHe: 'גאולוג הוא מדען החוקר את הרכב כדור הארץ, הסלעים, פנים האדמה ורעידות אדמה.'
  },
  {
    id: 'gk-8-50',
    category: 'Geography',
    ageGroup: '8-13',
    questionEn: 'What is the capital city of France?',
    questionHe: 'מָהִי עִיר הַבִּירָה שֶׁל צָרְפַת?',
    optionsEn: ['London', 'Berlin', 'Paris', 'Rome'],
    optionsHe: ['לונדון', 'ברלין', 'פָּרִיז', 'רומא'],
    answerIndex: 2,
    explanationEn: 'Paris, located on the River Seine, is a global center for art, fashion, gastronomy, and culture.',
    explanationHe: 'פריז היא עיר הבירה של צרפת, מפורסמת במגדל אייפל, מוזיאון הלובר ונהר הסיין.'
  },
  {
    id: 'gk-8-51',
    category: 'Animals',
    ageGroup: '8-13',
    questionEn: 'Which bird is famous for being unable to fly but swims exceptionally well?',
    questionHe: 'אֵיזֶה עוֹף מְפֻרְסָם בְּכָךְ שֶׁאֵינוֹ יָכוֹל לָעוּף אֲבָל שׂוֹחֶה מְצֻיָּן?',
    optionsEn: ['Ostrich', 'Penguin', 'Pelican', 'Albatross'],
    optionsHe: ['יענה', 'פִּינְגְּוִין', 'שקנאי', 'אלבטרוס'],
    answerIndex: 1,
    explanationEn: 'Penguins have evolved flippers instead of wings, making them super-fast swimmers in freezing waters.',
    explanationHe: 'פינגווינים הם עופות מים שאינם יכולים לעוף, אך הם שוחים וצוללים במיומנות מדהימה.'
  },
  {
    id: 'gk-8-52',
    category: 'Math',
    ageGroup: '8-13',
    questionEn: 'What is the value of 150 divided by 3?',
    questionHe: 'מַהִי הַתּוֹצָאָה שֶׁל 150 חָלְקֵי 3?',
    optionsEn: ['30', '40', '50', '60'],
    optionsHe: ['30', '40', '50', '60'],
    answerIndex: 2,
    explanationEn: '150 divided by 3 is 50. You can think of it as 15 divided by 3 (which is 5) and then add the zero.',
    explanationHe: '150 חלקי 3 שווה ל-50. קל לחשב זאת על ידי חלוקת 15 ב-3 והוספת אפס בסוף.'
  },
  {
    id: 'gk-8-53',
    category: 'History',
    ageGroup: '8-13',
    questionEn: 'Who invented the telephone in 1876?',
    questionHe: 'מִי הִמְצִיא אֶת הַטֶּלֶפוֹן בִּשְׁנַת 1876?',
    optionsEn: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Albert Einstein'],
    optionsHe: ['תומאס אדיסון', 'אָלֶכְּסַנְדֶּר גְרָאהָם בֶּל', 'ניקולה טסלה', 'אלברט איינשטיין'],
    answerIndex: 1,
    explanationEn: 'Alexander Graham Bell secured the first patent for the electric telephone in 1876, changing global communications.',
    explanationHe: 'אלכסנדר גרהאם בל המציא את הטלפון ורשם עליו פטנט בשנת 1876.'
  },
  {
    id: 'gk-8-54',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'How many teeth does an adult human typically have?',
    questionHe: 'כַּמָּה שִׁנַּיִם יֵשׁ בְּדֶרֶךְ כְּלָל לְאָדָם מְבֻגָּר?',
    optionsEn: ['20', '28', '32', '36'],
    optionsHe: ['20', '28', '32', '36'],
    answerIndex: 2,
    explanationEn: 'An adult typically has 32 permanent teeth, which includes 4 wisdom teeth.',
    explanationHe: 'לאדם מבוגר יש בדרך כלל 32 שיניים קבועות, כולל ארבע שיני בינה.'
  },
  {
    id: 'gk-8-55',
    category: 'Space',
    ageGroup: '8-13',
    questionEn: 'How long does it take for Earth to complete one full orbit around the Sun?',
    questionHe: 'כַּמָּה זְמַן לוֹקֵחַ לְכַדּוּר הָאָרֶץ לְהַשְׁלִים סִבּוּב אֶחָד סְבִיב הַשֶּׁמֶשׁ?',
    optionsEn: ['24 hours', '30 days', '365 days', '100 days'],
    optionsHe: ['24 שעות', '30 ימים', '365 יָמִים', '100 ימים'],
    answerIndex: 2,
    explanationEn: 'It takes 365.25 days for Earth to orbit the Sun, which is why we add a Leap Day every 4 years.',
    explanationHe: 'הקפת כדור הארץ סביב השמש נמשכת כ-365 ימים ורבע, ובגלל זה בכל ארבע שנים יש שנה מעוברת.'
  },
  {
    id: 'gk-8-56',
    category: 'Science',
    ageGroup: '8-13',
    questionEn: 'What is the process of liquid water turning into gas called?',
    questionHe: 'אֵיךְ נִקְרָא הַתַּהֲלִיךְ שֶׁבּוֹ מַיִם נוֹזְלִיִּים הופְכִים לְגָז?',
    optionsEn: ['Condensation', 'Evaporation', 'Freezing', 'Melting'],
    optionsHe: ['התעבות', 'הִתְאַדְּמוּת (אִדּוּי)', 'קיפאון', 'התכה'],
    answerIndex: 1,
    explanationEn: 'Evaporation happens when heat energy turns liquid water into water vapor gas, rising into the sky.',
    explanationHe: 'התאדות (או איוי) היא תהליך פיזיקלי שבו נוזל הופך לגז בגלל חום.'
  },
  {
    id: 'gk-8-57',
    category: 'Geography',
    ageGroup: '8-13',
    questionEn: 'Which country has the largest population in the world?',
    questionHe: 'בְּאֵיזוֹ מְדִינָה יֵשׁ אֶת הָאֻכְלוּסִיָּה הַגְּדוֹלָה בְּיוֹתֵר בָּעוֹלָם?',
    optionsEn: ['United States', 'Russia', 'India', 'Brazil'],
    optionsHe: ['ארצות הברית', 'רוסיה', 'הוֹדּוּ', 'ברזיל'],
    answerIndex: 2,
    explanationEn: 'India surpassed China to become the world’s most populous nation, with over 1.4 billion people.',
    explanationHe: 'הודו היא כיום המדינה בעלת האוכלוסייה הגדולה ביותר בעולם, עם מעל 1.4 מיליארד תושבים.'
  },
  {
    id: 'gk-8-58',
    category: 'Animals',
    ageGroup: '8-13',
    questionEn: 'What is the largest living shark species in the ocean?',
    questionHe: 'מַהוּ מִין הַכָּרִישׁ הַגָּדוֹל בְּיוֹתֵר שֶׁחַי כַּיּוֹם בָּאוֹקְיָנוּס?',
    optionsEn: ['Great White Shark', 'Hammerhead Shark', 'Whale Shark', 'Tiger Shark'],
    optionsHe: ['כריש לבן גדול', 'פטישן', 'כָּרִישׁ לִוְיָתָן', 'כריש טיגריס'],
    answerIndex: 2,
    explanationEn: 'The Whale Shark can grow up to 12 meters long! Despite its size, it is a gentle filter-feeder that eats plankton.',
    explanationHe: 'כריש לווייתן הוא הדג והכריש הגדול ביותר בעולם. הוא ניזון בעיקר מפלנקטון ואינו מסוכן.'
  },
  {
    id: 'gk-8-59',
    category: 'Math',
    ageGroup: '8-13',
    questionEn: 'What is the next number in this sequence: 2, 4, 8, 16, ...?',
    questionHe: 'מַהוּ הַמִּסְפָּר הַבָּא בַּסִּדְרָה: 2, 4, 8, 16, ...?',
    optionsEn: ['20', '24', '30', '32'],
    optionsHe: ['20', '24', '30', '32'],
    answerIndex: 3,
    explanationEn: 'Each number in this sequence is multiplied by 2 to get the next term. 16 x 2 = 32.',
    explanationHe: 'בסדרה זו כל מספר מוכפל ב-2. לכן המספר הבא הוא 16 כפול 2 שזה שווה ל-32.'
  },
  {
    id: 'gk-8-60',
    category: 'History',
    ageGroup: '8-13',
    questionEn: 'Which famous ship sank in 1912 after hitting an iceberg?',
    questionHe: 'אֵיזוֹ אֳנִיָּה מְפֻרְסֶמֶת טָבְעָה בִּשְׁנַת 1912 אַחֲרֵי שֶׁפָּגְעָה בְּקַרְחוֹן?',
    optionsEn: ['Santa Maria', 'Titanic', 'Mayflower', 'Golden Hind'],
    optionsHe: ['סנטה מריה', 'טִיטָאנִיק', 'מייפלאואר', 'גולדן היינד'],
    answerIndex: 1,
    explanationEn: 'The Titanic was deemed "unsinkable" but tragically sank in the North Atlantic on its maiden voyage.',
    explanationHe: 'הטיטאניק הייתה אוניית נוסעים ענקית שטבעה באוקיינוס האטלנטי לאחר שנתקלה בקרחון ב-1912.'
  },
  {
    id: 'gk-8-61',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Which country hosted the ancient Olympic Games?',
    questionHe: 'אֵיזוֹ מְדִינָה אֵרְחָה אֶת הַמִּשְׂחָקִים הָאוֹלִימְפִּיִּים הָעַתִּיקִים?',
    optionsEn: ['Rome', 'Greece', 'Egypt', 'China'],
    optionsHe: ['רומא', 'יָוָן', 'מצרים', 'סין'],
    answerIndex: 1,
    explanationEn: 'The Olympic Games originated in Olympia, Greece, in 776 BC as a festival honoring the god Zeus.',
    explanationHe: 'המשחקים האולימפיים נוסדו ביוון העתיקה לכבודו של האל זאוס.'
  },
  {
    id: 'gk-8-62',
    category: 'Space',
    ageGroup: '8-13',
    questionEn: 'Which planet is closest to the Sun?',
    questionHe: 'אֵיזֶה כּוֹכַב לֶכֶת הוּא הַקָּרוֹב בְּיוֹתֵר לַשֶּׁמֶשׁ?',
    optionsEn: ['Venus', 'Earth', 'Mercury', 'Mars'],
    optionsHe: ['נוגה', 'כדור הארץ', 'חַמָּה (מרקורי)', 'מאדים'],
    answerIndex: 2,
    explanationEn: 'Mercury is the innermost planet, taking only 88 Earth days to orbit the Sun once.',
    explanationHe: 'כוכב חמה (מרקורי) הוא כוכב הלכת הקרוב ביותר לשמש והוא משלים הקפה מהר מאוד.'
  },
  {
    id: 'gk-8-63',
    category: 'Science',
    ageGroup: '8-13',
    questionEn: 'What do we call the green pigment that plants use to capture sunlight?',
    questionHe: 'אֵיךְ נִקְרָא הַצֶּבֶע הַיָּרֹק שֶׁבַּעֲזָרָתוֹ צְמָחִים קוֹלְטִים אוֹר שֶׁמֶשׁ?',
    optionsEn: ['Carotene', 'Chlorophyll', 'Melanin', 'Hemoglobin'],
    optionsHe: ['קרוטן', 'כְלוֹרוֹפִיל', 'מלנין', 'המוגלובין'],
    answerIndex: 1,
    explanationEn: 'Chlorophyll absorbs red and blue light from the Sun, using it for photosynthesis while reflecting green light.',
    explanationHe: 'כלורופיל הוא החומר הירוק בצמחים המאפשר להם להפיק מזון בעזרת אור השמש.'
  },
  {
    id: 'gk-8-64',
    category: 'Geography',
    ageGroup: '8-13',
    questionEn: 'What is the capital city of Japan?',
    questionHe: 'מָהִי עִיר הַבִּירָה שֶׁל יַפָּן?',
    optionsEn: ['Seoul', 'Beijing', 'Kyoto', 'Tokyo'],
    optionsHe: ['סיאול', 'בייג׳ינג', 'קיוטו', 'טוֹקְיוֹ'],
    answerIndex: 3,
    explanationEn: 'Tokyo is the bustling capital of Japan, combining ultramodern skyscrapers with historic shrines.',
    explanationHe: 'טוקיו היא עיר הבירה התוססת והמודרנית של יפן, והיא המטרופולין הגדול בעולם.'
  },
  {
    id: 'gk-8-65',
    category: 'Animals',
    ageGroup: '8-13',
    questionEn: 'Which mammal has the thickest fur of all animals?',
    questionHe: 'לְאֵיזֶה יוֹנֵק יֵשׁ אֶת הַפַּרְוָה הַסְּמִיכָה וְהָעָבָה בְּיוֹתֵר מִכָּל בַּעֲלֵי הַחַיִּים?',
    optionsEn: ['Polar Bear', 'Sea Otter', 'Arctic Fox', 'Grizzly Bear'],
    optionsHe: ['דוב קוטב', 'לוּטְרַת הַיָּם', 'שועל שלג', 'דוב גריזלי'],
    answerIndex: 1,
    explanationEn: 'Sea Otters have up to 1 million hairs per square inch to keep them warm in freezing ocean waters without blubber.',
    explanationHe: 'לוטרת הים זקוקה לפרווה סמיכה במיוחד המכילה עד מיליון שערות לאינץ׳ רבוע כי אין לה שכבת שומן מגינה.'
  },
  {
    id: 'gk-8-66',
    category: 'Math',
    ageGroup: '8-13',
    questionEn: 'If a triangle has a base of 6 cm and a height of 4 cm, what is its area?',
    questionHe: 'מַהוּ שֶׁטַח מְשֻׁלָּשׁ שֶׁבְּסִיסוֹ 6 ס״מ וְגוֹבְהוֹ 4 ס״מ?',
    optionsEn: ['10 sq cm', '12 sq cm', '24 sq cm', '18 sq cm'],
    optionsHe: ['10 סמ״ר', '12 סמ״ר', '24 סמ״ר', '18 סמ״ר'],
    answerIndex: 1,
    explanationEn: 'The area of a triangle is (base x height) / 2. Here: (6 x 4) / 2 = 12.',
    explanationHe: 'שטח משולש מחושב על ידי מכפלת הבסיס בגובה חלקי שתיים: (6 כפול 4) חלקי 2 שווה ל-12 סמ״ר.'
  },
  {
    id: 'gk-8-67',
    category: 'History',
    ageGroup: '8-13',
    questionEn: 'Who was the legendary leader of the Mongols who founded the Mongol Empire?',
    questionHe: 'מִי הָיָה הַמַּנְהִיג הָאַגָּדָתִי שֶׁל הַמּוֹנְגוֹלִים שֶׁהֵקִים אֶת הָאִימְפֶּרְיָה הַמּוֹנְגוֹלִית?',
    optionsEn: ['Kublai Khan', 'Genghis Khan', 'Attila the Hun', 'Alexander the Great'],
    optionsHe: ['קובלאי חאן', 'גֵּ׳נְגִיל חָאן', 'אטילה ההוני', 'אלכסנדר הגדול'],
    answerIndex: 1,
    explanationEn: 'Genghis Khan united nomadic tribes in Northeast Asia, building the largest contiguous empire in history.',
    explanationHe: 'ג׳ינגיס חאן איחד את שבטי המונגולים והקים את האימפריה היבשתית הרציפה הגדולה בהיסטוריה.'
  },
  {
    id: 'gk-8-68',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'What instrument is used to measure air temperature?',
    questionHe: 'בְּאֵיזֶה מַכְשִׁיר מִשְׁתַּמְּשִׁים כְּדֵי לִמְדֹּד אֶת טֶמְפֶּרָטוּרַת הָאֲוִיר?',
    optionsEn: ['Barometer', 'Thermometer', 'Anemometer', 'Compass'],
    optionsHe: ['ברומטר', 'מַדְחוֹם', 'אנמומטר', 'מצפן'],
    answerIndex: 1,
    explanationEn: 'A thermometer measures thermal expansion, usually of liquids like alcohol or using electric sensors.',
    explanationHe: 'מדחום הוא מכשיר המשמש למדידת טמפרטורה, המבוסס לרוב על התפשטות נוזל או חיישן דיגיטלי.'
  },
  {
    id: 'gk-8-visual-pedestrian',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Look at the blue road sign! What does this warning sign tell drivers?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הַכָּחֹל! עַל מָה מַזְהִיר תַּמְרוּר זֶה אֶת הַנְּהָגִים?',
    optionsEn: ['Pedestrian crossing ahead', 'No parking', 'Highway entrance', 'Hospital zone'],
    optionsHe: ['מַעֲבַר חֲצִיָּה לְהוֹלְכֵי רֶגֶל לְפָנֶיךָ', 'אֵין חֲנִיָּה', 'כְּנִיסָה לִכְבִישׁ מָהִיר', 'אֵזוֹר בֵּית חוֹלִים'],
    answerIndex: 0,
    explanationEn: 'The blue square containing a white triangle and walking silhouette indicates a designated pedestrian crosswalk!',
    explanationHe: 'התמרור הריבועי הכחול ובו משולש לבן ודמות הולכת מורה על מעבר חצייה קרוב ומזהיר נהגים להאט!',
    visualType: 'pedestrian-sign'
  },
  {
    id: 'gk-8-visual-puzzle',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Observe the 2x2 grid pattern! Which symbol completes the puzzle logically: Star, Moon, Heart, ...?',
    questionHe: 'הִסְתַּכְּלוּ בְּרֶשֶׁת הַפָּזֶל! אֵיזוֹ צוּרָה מַשְׁלִימָה אֶת הַחֵלֶק הַחָסֵר לְפִי הַהִגָּיוֹן?',
    optionsEn: ['☀️ Yellow Sun', '🌸 Pink Flower', '🚗 Red Car', '🎈 Blue Balloon'],
    optionsHe: ['☀️ שֶׁמֶשׁ צְהֻבָּה', '🌸 פֶּרַח וָרֹד', '🚗 מְכוֹנִית אֲדֻמָּה', '🎈 בַּלּוֹן כָּחֹל'],
    answerIndex: 0,
    explanationEn: 'A yellow sun completes the set of bright, beautiful sky objects (Star, Moon, Sun) alongside the heart!',
    explanationHe: 'השמש הצהובה משלימה את קבוצת גרמי השמיים המאירים (כוכב, ירח ושמש) יחד עם הלב הירוק!',
    visualType: 'puzzle-piece'
  },
  {
    id: 'gk-8-visual-shadow',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Observe the dark silhouette on the canvas. Which animal does this shadow belong to?',
    questionHe: 'הִסְתַּכְּלוּ בַּצַּלָּנִית הַכֵּהָה עַל הַמָּסָךְ. לְאֵיזוֹ חַיָּה שַׁיֶּכֶת צַלִּית זוֹ?',
    optionsEn: ['Rabbit', 'Elephant', 'Cat', 'Squirrel'],
    optionsHe: ['אַרְנָב', 'פִּיל', 'חָתוּל', 'סְנַאי'],
    answerIndex: 0,
    explanationEn: 'Those long upright ears, round fluffy body, and tiny tail belong perfectly to a rabbit!',
    explanationHe: 'האוזניים הארוכות, הגוף העגלגל והזנב הקטן והחמוד שייכים ללא ספק לארנב!',
    visualType: 'shadow-match'
  },
  {
    id: 'gk-8-story-alice',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: "In 'Alice in Wonderland', who has a pocket watch and is always running late?",
    questionHe: "בְּ'עֲלִיסָה בְּאֶרֶץ הַפְּלָאוֹת', לְמִי יֵשׁ שָׁעוֹן כִּיס וְהוּא תָּמִיד מְאַחֵר?",
    optionsEn: ['The White Rabbit', 'The Mad Hatter', 'The Cheshire Cat', 'The Caterpillar'],
    optionsHe: ['הָאַרְנָב הַלָּבָן', 'הַכּוֹבְעָן הַמְטֹרָף', 'חֲתוּל צֶ\'שַׁיְר', 'הַזַּחַל'],
    answerIndex: 0,
    explanationEn: "The White Rabbit is famous for looking at his pocket watch and saying, 'Oh dear! Oh dear! I shall be too late!'",
    explanationHe: "הארנב הלבן מפורסם בכך שהוא מביט בשעון הכיס שלו ואומר 'אבוי, אני מאחר!'"
  },
  {
    id: 'gk-8-story-wizard-of-oz',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: "In 'The Wizard of Oz', what does the Tin Woodman long for?",
    questionHe: "בְּ'הַקּוֹסֵם מֵאֶרֶץ עוֹץ', מָה מִשְׁתּוֹקֵק אִישׁ הַפַּח לְקַבֵּל?",
    optionsEn: ['A heart', 'A brain', 'Courage', 'A pair of shoes'],
    optionsHe: ['לֵב', 'מוֹחַ', 'אֹמֶץ לֵב', 'זוּג נַעֲלַיִם'],
    answerIndex: 0,
    explanationEn: 'The Tin Woodman travels to see the Wizard to ask for a heart so he can feel love.',
    explanationHe: 'איש הפח נוסע לקוסם כדי לבקש לב כדי שיוכל להרגיש אהבה.'
  },
  {
    id: 'gk-8-visual-roundabout',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Look at the blue circle sign with three circular arrows! What does this sign mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הָעָגֹל הַכָּחֹל עִם שְׁלֹשֶׁת הַחִצִּים הַסִּיבּוּבִיִּים! מָה מַשְׁמָעוּת תַּמְרוּר זֶה?',
    optionsEn: ['Roundabout (Traffic circle) ahead', 'No left turn allowed', 'Windy road ahead', 'U-turn is mandatory'],
    optionsHe: ['מַעְגַּל תְּנוּעָה (כִּכָּר) לְפָנֶיךָ', 'אֲסוּרָה הַפְּנִיָּה שְׂמֹאלָה', 'כְּבִישׁ מְפֻתָּל לְפָנֶיךָ', 'פְּנִיַּת פַּרְסָה הִיא חוֹבָה'],
    answerIndex: 0,
    explanationEn: 'The roundabout sign indicates that drivers must enter a traffic circle and travel in the direction of the arrows.',
    explanationHe: 'תמרור מעגל תנועה מורה לנהגים להיכנס לכיכר ולהתקדם בכיוון החצים.',
    visualType: 'roundabout-sign'
  },
  {
    id: 'gk-8-visual-no-parking',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Look at the blue circle sign with a red border and a single diagonal red line! What does it mean?',
    questionHe: 'הַבִּיטוּ בַּתַּמְרוּר הָעָגֹל הַכָּחֹל עִם הַשּׁוּלַיִם הָאֲדֻמִּים וְהַקַּו הָאֲלַכְסוֹנִי הָאָדֹם הַיָּחִיד! מָה מַשְׁמָעוּת תַּמְרוּר זֶה?',
    optionsEn: ['No Parking allowed', 'No vehicles allowed', 'Speed limit area', 'Bicycle path ahead'],
    optionsHe: ['אֲסוּרָה הַחֲנִיָּה', 'אֲסוּרָה כְּנִיסַת כְּלִי רֶכֶב', 'אֵזוֹר הַגְבָּלַת מְהִירוּת', 'נְתִיב אוֹפַנַּיִם לְפָנֶיךָ'],
    answerIndex: 0,
    explanationEn: 'A blue circle with a red diagonal line means No Parking. You are not allowed to park your car here!',
    explanationHe: 'עיגול כחול עם קו אדום אלכסוני הוא תמרור "אין חניה". אסור להחנות את הרכב במקום זה!',
    visualType: 'no-parking-sign'
  },
  {
    id: 'gk-8-visual-odd',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Look at the four faces. Which face is the "odd one out" (different from others)?',
    questionHe: 'הַבִּיטוּ בְּאַרְבַּעַת הַפַּרְצוּפִים. אֵיזֶה פַּרְצוּף הוּא יוֹצֵא הַדֹּפֶן (שׁוֹנֶה מִכֻּלָּם)?',
    optionsEn: ['The sad crying face', 'The first happy face', 'The second happy face', 'The fourth happy face'],
    optionsHe: ['הַפַּרְצוּף הָעָצוּב הַבּוֹכֶה', 'הַפַּרְצוּף הַשָּׂמֵחַ הָרִאשׁוֹן', 'הַפַּרְצוּף הַשָּׂמֵחַ הַשֵּׁנִי', 'הַפַּרְצוּף הַשָּׂמֵחַ הָרְבִיעִי'],
    answerIndex: 0,
    explanationEn: 'Three of the faces are happy smiling faces, while the third one is sad and crying!',
    explanationHe: 'שלושה מהפרצופים שמחים ומחייכים, בעוד הפרצוף השלישי עצוב ובוכה!',
    visualType: 'odd-one-out'
  },
  {
    id: 'gk-8-visual-puzzle',
    category: 'GeneralKnowledge',
    ageGroup: '8-13',
    questionEn: 'Look at the grid of shapes: Star, Moon, Heart, and ?. What shape goes in the "?" slot to complete the sky theme?',
    questionHe: 'הַבִּיטוּ בְּטַבְלַת הַצּוּרוֹת: כּוֹכָב, יָרֵחַ, לֵב, וּ-?. אֵיזוֹ צוּרָה מַשְׁלִימָה אֶת נוֹשֵׂא הַשָּׁמַיִם בַּ- "?"?',
    optionsEn: ['A yellow sun', 'A green tree', 'A red car', 'A pink flower'],
    optionsHe: ['שֶׁמֶשׁ צְהֻבָּה', 'עֵץ יָרֹק', 'מְכוֹנִית אֲדֻמָּה', 'פֶּרַח וָרֹד'],
    answerIndex: 0,
    explanationEn: 'A yellow sun fits the celestial sky theme perfectly alongside the star and the moon!',
    explanationHe: 'שמש צהובה מתאימה באופן מושלם לנושא גרמי השמים לצד הכוכב והירח!',
    visualType: 'puzzle-piece'
  }
];
