import { Question } from './types';

export const STORIES_QUESTIONS: Question[] = [
  // ==================== AGES 5-7 (20 Questions) ====================
  {
    id: 'story-5-1',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What does Cinderella lose on the palace stairs at midnight?',
    questionHe: 'מָה סִינְדֶּרֶלָה מְאַבֶּדֶת עַל מַדְרֵגוֹת הָאַרְמוֹן בַּחֲצוֹת?',
    optionsEn: ['A glass slipper', 'A golden ring', 'A red ribbon', 'A magic wand'],
    optionsHe: ['נַעַל זְכוּכִית', 'טַבַּעַת זָהָב', 'סֶרֶט אָדֹם', 'שַׁרְבִיט קְסָמִים'],
    answerIndex: 0,
    explanationEn: 'Cinderella rushes away before the spell breaks and leaves behind one of her glass slippers!',
    explanationHe: 'סינדרלה ממהרת לברוח לפני שהקסם יפוג ומשאירה מאחור נעל זכוּכית אחת!'
  },
  {
    id: 'story-5-2',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What is Little Red Riding Hood carrying in her basket to her grandmother?',
    questionHe: 'מָה כִּפָּה אֲדֻמָּה מְבִיאָה בַּסַּלָּהּ לְסָבְתָא שֶׁלָּהּ?',
    optionsEn: ['Flowers and toys', 'Cake and butter', 'Books and pencils', 'Gold and silver'],
    optionsHe: ['פְּרָחִים וְצַעֲצוּעִים', 'עוּגָה וְחֶמְאָה', 'סְפָרִים וְעִפָּרוֹנוֹת', 'זָהָב וְכֶסֶף'],
    answerIndex: 1,
    explanationEn: 'She goes to visit her grandmother with delicious cake and butter in her basket!',
    explanationHe: 'היא הולכת לבקר את סבתא שלה עם עוגה טעימה וחמאה בתוך הסל!'
  },
  {
    id: 'story-5-3',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'How does Rapunzel let people climb up into her tall tower?',
    questionHe: 'כֵּיצַד רַפּוּנְזֶל מְאַפְשֶׁרֶת לַאֲנָשִׁים לְטַפֵּס לַמִּגְדָּל הַגָּבוֹהַּ שֶׁלָּהּ?',
    optionsEn: ['With a rope ladder', 'With a magic elevator', 'With her very long hair', 'With giant balloons'],
    optionsHe: ['בְּעֶזְרַת סֻלַּם חֲבָלִים', 'בְּעֶזְרַת מַעֲלִית קְסָמִים', 'בְּעֶזְרַת שַׂעֲרָהּ הָאָרֹךְ מְאֹד', 'בְּעֶזְרַת בַּלוֹנֵי עֲנָק'],
    answerIndex: 2,
    explanationEn: 'Rapunzel lets down her long, golden hair from the window so the prince can climb up!',
    explanationHe: 'רפונזל משלשלת את שיערה המוזהב והארוך מהחלון כדי שהנסיך יוכל לטפס למעלה!'
  },
  {
    id: 'story-5-4',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What kind of animal does Aladdin release from the magic lamp?',
    questionHe: 'אֵיזֶה יְצוּר מְשַׁחְרֵר אַלָּדִין מִתּוֹךְ מְנוֹרַת הַקְּסָמִים?',
    optionsEn: ['A dragon', 'A genie', 'A talking monkey', 'A flying horse'],
    optionsHe: ['דְּרָקוֹן', 'גִ\'ינִי (שֵׁד קְסָמִים)', 'קוֹף מְדַבֵּר', 'סוּס מְעוֹפֵף'],
    answerIndex: 1,
    explanationEn: 'Aladdin rubs the lamp and out comes a friendly Genie who grants him three wishes!',
    explanationHe: 'אלאדין משפשף את המנורה ויוצא מתוכה ג\'יני ידידותי שמעניק לו שלוש משאלות!'
  },
  {
    id: 'story-5-5',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What happens to the Ugly Duckling when he grows up?',
    questionHe: 'מָה קוֹרֶה לַבַּרְוָזוֹן הַמְּכֹעָר כְּשֶׁהוּא גָּדֵל?',
    optionsEn: ['He turns into a swan', 'He becomes a king', 'He flies to the moon', 'He learns to swim faster'],
    optionsHe: ['הוּא הֹפֵךְ לְבַרְבּוּר יְפֵהפֶה', 'הוּא הֹפֵךְ לְמֶלֶך', 'הוּא עָף לַיָּרֵחַ', 'הוּא לוֹמֵד לִשְׂחוֹת מַהֵר יוֹתֵר'],
    answerIndex: 0,
    explanationEn: 'The Ugly Duckling realizes he was never a duck at all—he grows into a beautiful white swan!',
    explanationHe: 'הברווזון המכוער מבין שהוא מעולם לא היה ברווז - הוא גדל להיות ברבור לבן ויפהפה!'
  },
  {
    id: 'story-5-6',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'In the story of the Three Little Pigs, what is the strongest house made of?',
    questionHe: 'בְּסִפּוּר שְׁלֹשֶׁת הַחֲזִירוֹנִים, מִמָּה בָּנוּי הַבַּיִת הֶחָזָק בְּיוֹתֵר?',
    optionsEn: ['Straw', 'Sticks', 'Bricks', 'Ice'],
    optionsHe: ['קַשׁ', 'זְרָדִים (עֲנָפִים)', 'לְבֵנִים (אֲבָנִים)', 'קֶרַח'],
    answerIndex: 2,
    explanationEn: 'The third little pig builds his house out of strong bricks, so the big bad wolf cannot blow it down!',
    explanationHe: 'החזירון השלישי בונה את ביתו מלבנים חזקות, ולכן הזאב הרע לא מצליח להרוס אותו בנשיפותיו!'
  },
  {
    id: 'story-5-7',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'Who wins the race between the slow Tortoise and the fast Hare?',
    questionHe: 'מִי מְנַצֵּחַ בַּמֵּרוֹץ בֵּין הַצָּב הָאִטִּי לַאַרְנָב הַמָּהִיר?',
    optionsEn: ['The Tortoise', 'The Hare', 'A Fox', 'Nobody'],
    optionsHe: ['הַצָּב', 'הָאַרְנָב', 'שׁוּעָל', 'אַף אֶחָד'],
    answerIndex: 0,
    explanationEn: 'The Tortoise wins by moving slowly and steadily, while the Hare takes a nap and loses!',
    explanationHe: 'הצב מנצח בזכות התמדה ונחישות (לאט ובטוח), בעוד הארנב נרדם ומפסיד במרוץ!'
  },
  {
    id: 'story-5-8',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What does Hansel and Gretel leave on the ground to find their way home?',
    questionHe: 'מָה הַנְזֶל וּגְרֶטֶל (עַמִּי וְתַמִּי) מַשְׁאִירִים עַל הָאֲדָמָה כְּדֵי לִמְצֹא אֶת הַדֶּרֶךְ הַבַּיְתָה?',
    optionsEn: ['Breadcrumbs', 'Shiny coins', 'Colorful flowers', 'Green leaves'],
    optionsHe: ['פֵּרוּרֵי לֶחֶם', 'מַטְבְּעוֹת נוֹצְצִים', 'פְּרָחִים צִבְעוֹנִיִּים', 'עָלִים יְרֻקִּים'],
    answerIndex: 0,
    explanationEn: 'They drop breadcrumbs, but unfortunately, birds eat them up and they get lost!',
    explanationHe: 'הם מפזרים פירורי לחם, אך לצערם הציפורים אוכלות אותם והם מאבדים את הדרך!'
  },
  {
    id: 'story-5-9',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'Where does Peter Pan live?',
    questionHe: 'אֵיפֹה גָּר פִּיטֶר פֶּן?',
    optionsEn: ['Neverland', 'Wonderland', 'Oz', 'The Ocean'],
    optionsHe: ['אֶרֶץ לְעוֹלָם לֹא', 'אֶרֶץ הַ(פְ)פְּלָאוֹת', 'אֶרֶץ עוֹץ', 'בָּאוֹקְיָנוּס'],
    answerIndex: 0,
    explanationEn: 'Peter Pan lives in Neverland, the magical island where kids never grow up!',
    explanationHe: 'פיטר פן גר בארץ לעולם לא, האי הקסום שבו ילדים אינם גדלים לעולם!'
  },
  {
    id: 'story-5-10',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What does Jack trade his family cow for in the story of the Beanstalk?',
    questionHe: 'תְּמוּרַת מָה מַחְלִיף גֶ\'ק אֶת הַפָּרָה שֶׁל מִשְׁפַּחְתּוֹ בַּסִּפּוּר עַל אֲפוּנַת הַפֶּלֶא?',
    optionsEn: ['Magic beans', 'A bag of gold', 'A golden egg', 'A talking harp'],
    optionsHe: ['פוֹלֵי קְסָמִים', 'שַׂק זָהָב', 'בֵּיצַת זָהָב', 'נֵבֶל מְדַבֵּר'],
    answerIndex: 0,
    explanationEn: 'Jack trades the cow for five magic beans which grow into a giant beanstalk reaching the sky!',
    explanationHe: 'ג\'ק מחליף את הפרה בחמישה פולי קסמים שצומחים לגבעול שעועית ענקי המגיע עד לשמים!'
  },
  {
    id: 'story-5-11',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'How does a tiny Mouse help a big Lion in the famous fable?',
    questionHe: 'כֵּיצַד עַכְבָּר קָטָן עוֹזֵר לְאַרְיֵה גָּדוֹל בַּמָּשָׁל הַמְפֻרְסָם?',
    optionsEn: ['By chewing the hunter\'s net', 'By bringing him water', 'By roaring loudly', 'By showing him the way'],
    optionsHe: ['עַל יְדֵי כִּרְסוּם רֶשֶׁת הַצַּיָּד', 'עַל יְדֵי הֲבָאַת מַיִם', 'עַל יְדֵי שְׁאָגָה רָמָה', 'עַל יְדֵי הַכְוָנַת הַדֶּרֶך hover'],
    answerIndex: 0,
    explanationEn: 'The mouse uses his sharp teeth to chew through the ropes of a hunter\'s net, freeing the grateful lion!',
    explanationHe: 'העכבר משתמש בשיניו החדות כדי לכרסם את חבלי הרשת של הציידים ולשחרר את האריה!'
  },
  {
    id: 'story-5-12',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What does the fairy godmother turn a pumpkin into for Cinderella?',
    questionHe: 'לְמָה הוֹפֶכֶת הַפֵּאָה הַטּוֹבָה אֶת הַדְּלַעַת עֲבוּר סִינְדֶּרֶלָה?',
    optionsEn: ['A carriage', 'A gown', 'A glass shoe', 'A horse'],
    optionsHe: ['כִּרְכָּרָה', 'שִׂמְלַת נֶשֶׁף', 'נַעַל זְכוּכִית', 'סוּס אָצִיל'],
    answerIndex: 0,
    explanationEn: 'With a wave of her magic wand, the fairy godmother turns a simple pumpkin into a magnificent carriage!',
    explanationHe: 'בהנפת שרביט הקסמים שלה, הפיה הטובה הופכת דלעת פשוטה לכרכרה מפוארת!'
  },
  {
    id: 'story-5-13',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'Who wakes up Sleeping Beauty from her hundred-year sleep?',
    questionHe: 'מִי מֵעִיר אֶת הַיְפֵהפִיָּה הַנִּרְדֶּמֶת מִשְּׁנָתָהּ בַּת מֵאָה הַשָּׁנִים?',
    optionsEn: ['A handsome prince', 'Her parents', 'A friendly dwarf', 'A singing bird'],
    optionsHe: ['נָסִיךְ יְפֵה תֹּאַר', 'הוֹרֶיהָ', 'גַּמָּד יְדִידוּתִי', 'צִפּוֹר שִׁיר'],
    answerIndex: 0,
    explanationEn: 'A prince breaks the spell and wakes Sleeping Beauty with a gentle kiss.',
    explanationHe: 'נסיך אמיץ שובר את הכישוף ומעיר את היפהפייה הנרדמת!'
  },
  {
    id: 'story-5-14',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What color is Snow White\'s poisoned apple?',
    questionHe: 'בְּאֵיזֶה צֶבֶע תַּפּוּחַ הָרַעַל שֶׁל שִׁלְגִּיָּה?',
    optionsEn: ['Bright red', 'Bright green', 'Deep blue', 'Golden yellow'],
    optionsHe: ['אָדֹם בָּהִיר', 'יָרֹק בָּהִיר', 'כָּחֹל כֵּהֶה', 'צָהֹב מוּזְהָב'],
    answerIndex: 0,
    explanationEn: 'The wicked queen offers Snow White a beautiful, shiny red apple that is secretly poisoned!',
    explanationHe: 'המלכה המרשעת מציעה לשלגייה תפוח אדום יפהפה ומבריק שהוא למעשה מורעל!'
  },
  {
    id: 'story-5-15',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'Who built a house out of gingerbread and candy in the forest?',
    questionHe: 'מִי בָּנָה בַּיִת מִלֶּחֶם זַנְגְּבִיל (גִ\'ינְג\'ֶרְבְּרֶד) וּמַמְתַּקִּים בַּיַּעַר?',
    optionsEn: ['An old witch', 'A friendly fairy', 'The seven dwarfs', 'A talking squirrel'],
    optionsHe: ['מְכַשֵּׁפָה זְקֵנָה', 'פֵּאָה טוֹבָה', 'שִׁבְעַת הַגַּמָּדִים', 'סְנַאי מְדַבֵּר'],
    answerIndex: 0,
    explanationEn: 'The wicked witch built the sweet candy house to lure Hansel and Gretel inside.',
    explanationHe: 'המכשפה הזקנה והרעה בנתה את בית הממתקים המתוק כדי למשוך את עמי ותמי פנימה.'
  },
  {
    id: 'story-5-16',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What happens to the Little Gingerbread Man in the end?',
    questionHe: 'מָה קוֹרֶה לְאִישׁ לֶחֶם הַזַּנְגְּבִיל (הַגִּ\'ינְג\'ֶרְבְּרֶד) בַּסּוֹף?',
    optionsEn: ['He is eaten by a fox', 'He wins a gold medal', 'He returns to the oven', 'He flies away'],
    optionsHe: ['הוּא נֶאֱכַל עַל יְדֵי שׁוּעָל', 'הוּא זוֹכֶה בְּמֵדַלְיַת זָהָב', 'הוּא חוֹזֵר לַתַּנּוּר', 'הוּא עָף מִשָּׁם'],
    answerIndex: 0,
    explanationEn: 'The clever fox offers to carry him across the river, but tricks him and eats him up!',
    explanationHe: 'השועל הערמומי מציע לחצות איתו את הנהר, אך לבסוף מפתה אותו ואוכל אותו!'
  },
  {
    id: 'story-5-17',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'How many dwarfs live in the cottage that Snow White finds?',
    questionHe: 'כַּמָּה גַּמָּדִים גָּרִים בַּבִּקְתָּה שֶׁמּוֹצֵאת שִׁלְגִּיָּה?',
    optionsEn: ['Seven', 'Three', 'Five', 'Ten'],
    optionsHe: ['שִׁבְעָה', 'שְׁלוֹשָׁה', 'חֲמִשָּׁה', 'עֲשָׂרָה'],
    answerIndex: 0,
    explanationEn: 'Snow White finds a cottage belonging to Seven Dwarfs who work in the diamond mines.',
    explanationHe: 'שלגייה מוצאת בית קטן השייך לשבעת הגמדים העובדים במכרות.'
  },
  {
    id: 'story-5-18',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'Who helps Pinocchio by giving him good advice?',
    questionHe: 'מִי עוֹזֵר לְפִינוֹקְיוֹ וּמַעֲנִיק לוֹ עָצוֹת טוֹבוֹת?',
    optionsEn: ['Jiminy Cricket', 'A red fox', 'A sneaky cat', 'A giant whale'],
    optionsHe: ['הַצְּרָצַר גִ\'ימִינִי', 'שׁוּעָל אָדֹם', 'חָתוּל עַרְמוּמִי', 'לִוְיָתָן עָנָק'],
    answerIndex: 0,
    explanationEn: 'Jiminy Cricket serves as Pinocchio\'s official conscience, guiding him to do the right thing.',
    explanationHe: 'הצרצר ג\'ימיני משמש כמצפון הרשמי של פינוקיו ומדריך אותו לעשות את הדבר הנכון.'
  },
  {
    id: 'story-5-19',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'What does Goldilocks find on the table that is "just right"?',
    questionHe: 'מָה מוֹצֵאת זַהֲבָה עַל הַשֻּׁלְחָן שֶׁנִּמְצָא כְּ"מַתְאִים בְּדִיּוֹק"?',
    optionsEn: ['Baby Bear\'s porridge', 'Mama Bear\'s soup', 'Papa Bear\'s bread', 'A bowl of fruit'],
    optionsHe: ['הַדַּיְסָה שֶׁל הַדֹּב הַקָּטָן', 'הַמָּרָק שֶׁל הַדֹּבָה הָאֵם', 'הַלֶּחֶם שֶׁל הַדֹּב הָאָב', 'קַעֲרַת פֵּרוֹת'],
    answerIndex: 0,
    explanationEn: 'Baby Bear\'s porridge is not too hot and not too cold—it is just right, and Goldilocks eats it all!',
    explanationHe: 'הדייסה של הדוב הקטן אינה חמה מדי ואינה קרה מדי - היא בדיוק במידה הנכונה, וזהבה אוכלת את כולה!'
  },
  {
    id: 'story-5-20',
    category: 'Stories',
    ageGroup: '5-7',
    questionEn: 'Who did the Boy Who Cried Wolf trick multiple times?',
    questionHe: 'אֶת מִי רִמָּה הַיֶּלֶד שֶׁצָּעַק "זְאֵב" מִסְפַּר פְּעָמִים?',
    optionsEn: ['The villagers', 'The sheep', 'The hunters', 'The wolf'],
    optionsHe: ['הַכַּפְרִיִּים', 'הַכְּבָשִׂים', 'הַצַּיָּדִים', 'הַזְּאֵב'],
    answerIndex: 0,
    explanationEn: 'The boy tricked the villagers by shouting about a wolf until they stopped believing his warnings!',
    explanationHe: 'הילד שיטה בתושבי הכפר שוב ושוב עד שהם הפסיקו להאמין לאזהרותיו!'
  },

  // ==================== AGES 8-13 (20 Questions) ====================
  {
    id: 'story-8-1',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What is the name of Arthur\'s legendary sword, which he pulls from the stone?',
    questionHe: 'מָה שְׁמָהּ שֶׁל חַרְבּוֹ הָאַגָּדִית שֶׁל הַמֶּלֶךְ אַרְתוּר, אוֹתָהּ שָׁלַף מִתּוֹךְ הָאֶבֶן?',
    optionsEn: ['Excalibur', 'Mjolnir', 'Sting', 'Hrunting'],
    optionsHe: ['אֶקְסְקָלִיבּוּר', 'מְיוֹלְנִיר', 'סְטִינְג (עֹקֶץ)', 'הְרוּנְטִינְג'],
    answerIndex: 0,
    explanationEn: 'Excalibur is the legendary sword of King Arthur, proving his rightful sovereignty over Britain.',
    explanationHe: 'אקסקליבור היא חרבו המסתורית והחזקה של המלך ארתור, שמוכיחה את זכותו לשלוט בממלכה.'
  },
  {
    id: 'story-8-2',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What color is the yellow road that Dorothy follows in Oz?',
    questionHe: 'בְּאֵיזֶה צֶבֶע שְׁבִיל הַלְּבֵנִים שֶׁבּוֹ צוֹעֶדֶת דּוֹרוֹתִי בְּאֶרֶץ עוֹץ?',
    optionsEn: ['Yellow', 'Red', 'Blue', 'Gold'],
    optionsHe: ['צָהֹב', 'אָדֹם', 'כָּחֹל', 'זָהָב'],
    answerIndex: 0,
    explanationEn: 'Dorothy and her friends follow the Yellow Brick Road to reach the Emerald City!',
    explanationHe: 'דורותי וחבריה צועדים לאורך שביל הלבנים הצהובות כדי להגיע לעיר האזמרגד!'
  },
  {
    id: 'story-8-3',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'In Alice in Wonderland, what does the bottle say that makes Alice shrink?',
    questionHe: "בְּ'עֲלִיסָה בְּאֶרֶץ הַ(פְ)פְּלָאוֹת', מָה כָּתוּב עַל הַבַּקְבּוּק שֶׁגּוֹרֵם לָהּ לְהִתְכַּוֵּץ?",
    optionsEn: ['Drink Me', 'Eat Me', 'Shrink Me', 'Open Me'],
    optionsHe: ['שְׁתֵה אוֹתִי', 'אֱכֹל אוֹתִי', 'כַּוֵּץ אוֹתִי', 'פְּתַח אוֹתִי'],
    answerIndex: 0,
    explanationEn: 'Alice drinks from a bottle labeled "Drink Me" and shrinks down to just ten inches tall!',
    explanationHe: 'עליסה שותה בקבוק שעליו תווית "שתה אותי" ומתכווצת לגובה של עשרה אינץ\' בלבד!'
  },
  {
    id: 'story-8-4',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What does King Midas touch that turns into solid gold?',
    questionHe: 'מָה קוֹרֶה לְכָל דָּבָר שֶׁבּוֹ נוֹגֵעַ הַמֶּלֶךְ מִידָאס?',
    optionsEn: ['It turns to gold', 'It turns to stone', 'It disappears', 'It melts'],
    optionsHe: ['הוּא הֹפֵךְ לְזָהָב', 'הוּא הֹפֵךְ לְאֶבֶן', 'הוּא נֶעֱלָם', 'הוּא נָמֵס'],
    answerIndex: 0,
    explanationEn: 'King Midas is granted the wish that everything he touches turns to solid gold—even his food and daughter!',
    explanationHe: 'המלך מידאס זוכה במשאלה לפיה כל דבר שהוא נוגע בו הופך לזהב מוצק - כולל האוכל שלו ובתה!'
  },
  {
    id: 'story-8-5',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What does Beauty find in the Beast\'s castle that shows how much time is left?',
    questionHe: 'מָה מוֹצֵאת יָפָה בְּאַרְמוֹן הַחַיָּה שֶׁמַּרְאֶה כַּמָּה זְמַן נִשְׁאַר לַכִּשּׁוּף?',
    optionsEn: ['An enchanted rose', 'An hourglass', 'A grandfather clock', 'A magic mirror'],
    optionsHe: ['וֶרֶד מְכֻשָּׁף', 'שָׁעוֹן חוֹל', 'שָׁעוֹן אוּרְלוֹגִין', 'מַרְאַת קְסָמִים'],
    answerIndex: 0,
    explanationEn: 'The enchanted rose drops petals. If all petals fall before the Beast learns to love, he remains a beast forever!',
    explanationHe: 'הוורד המכושף משיר עלי כותרת. אם כולם יישרו לפני שהחיה ילמד לאהוב, הוא יישאר חיה לנצח!'
  },
  {
    id: 'story-8-6',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'In the story of Rumpelstiltskin, what does the girl spin straw into?',
    questionHe: 'בַּסִּפּוּר עַל עוּץ לִי גּוּץ לִי, לְמָה הַנַּעֲרָה טוֹוָה אֶת הַקַּשׁ?',
    optionsEn: ['Gold thread', 'Silver silk', 'Warm wool', 'Diamond gems'],
    optionsHe: ['חוּטֵי זָהָב', 'מְשִׁי כֶּסֶף', 'צֶמֶר חַם', 'אבני יַהֲלֹם'],
    answerIndex: 0,
    explanationEn: 'Rumpelstiltskin spins straw into valuable gold thread to save the miller\'s daughter.',
    explanationHe: 'עוץ לי גוץ לי עוזר לבת הטוחן וטוהה את הקש הפשוט לחוטי זהב יקרים.'
  },
  {
    id: 'story-8-7',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What does the Pied Piper of Hamelin play to attract rats and children?',
    questionHe: 'בְּאֵיזֶה כְּלִי מְנַגֵּן הַחַלְילָן מֵהָמֶלִין כְּדֵי לִמְשֹׁךְ אֶת הָעַכְבָּרִים וְהַיְּלָדִים?',
    optionsEn: ['A flute/pipe', 'A violin', 'A trumpet', 'A drum'],
    optionsHe: ['חָלִיל', 'כִּנּוֹר', 'חֲצוֹצְרָה', 'תֹּף'],
    answerIndex: 0,
    explanationEn: 'The Pied Piper plays a magical tune on his flute/pipe to charm and lead the rats away.',
    explanationHe: 'החלילן מנגן מנגינה קסומה בחליל שלו כדי להקסים ולהוביל את העכברים מחוץ לעיר.'
  },
  {
    id: 'story-8-8',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What is the secret phrase used to open the thieves\' cave in Ali Baba?',
    questionHe: 'מַהוּ מִשְׁפַּט הַקֶּסֶם הַסּוֹדִי שֶׁפּוֹתֵחַ אֶת מְעָרַת הַשּׁוֹדְדִים בַּסִּפּוּר עַל עָלִי בָּבָא?',
    optionsEn: ['Open Sesame', 'Abracadabra', 'Hocus Pocus', 'Fly away home'],
    optionsHe: ['שֻׁמְשׁוּם הִפָּתַח', 'אַבְרָקָדָבְרָה', 'הוֹקוּס פּוֹקוּס', 'עוּף לַשָּׁמַיִם'],
    answerIndex: 0,
    explanationEn: 'Ali Baba learns that the thieves use the magic words "Open Sesame" to unlock the secret cave.',
    explanationHe: 'עלי באבא מגלה כי השודדים משתמשים במילים "שומשום היפתח" כדי לפתוח את המערה הסודית.'
  },
  {
    id: 'story-8-9',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'In fables, what does the Ant do during summer while the Grasshopper sings?',
    questionHe: 'בַּמְּשָׁלִים, מָה עוֹשָׂה הַנְּמָלָה בַּקַּיִץ בִּזְמַן שֶׁהַצְּרָצַר שָׁר?',
    optionsEn: ['Stores food for winter', 'Builds a swimming pool', 'Takes a long nap', 'Plays games'],
    optionsHe: ['אוֹסֶפֶת מָזוֹן לַחֹרֶף', 'בוֹנָה בְּרֵכַת שְׂחִיָּה', 'יְשֵׁנָה שְׁנַת צָהֳרַיִם', 'מְשַׂחֶקֶת בְּמִשְׂחָקִים'],
    answerIndex: 0,
    explanationEn: 'The Ant works hard gathering and storing food for the cold winter, while the Grasshopper plays and goes hungry.',
    explanationHe: 'הנמלה עומלת קשה ואוספת אוכל שישמש אותה בחורף הקר, בעוד הצרצר שר ונותר רעב.'
  },
  {
    id: 'story-8-10',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'Who is Robin Hood\'s closest friend and second-in-command?',
    questionHe: 'מִי חֲבֵרוֹ הַקָּרוֹב בְּיוֹתֵר וּסְגָנוֹ שֶׁל רוֹבִּין הוּד?',
    optionsEn: ['Little John', 'Friar Tuck', 'Will Scarlet', 'Sheriff of Nottingham'],
    optionsHe: ['ג\'וֹן הַקָּטָן', 'הָאָח טָאק', 'וִיל סְקַארְלֶט', 'הַשָּׁרִיף מִנּוֹטִינְגְהָם'],
    answerIndex: 0,
    explanationEn: 'Little John is Robin Hood\'s legendary giant friend and second-in-command of the Merry Men!',
    explanationHe: 'ג\'ון הקטן הוא חברו הענק והנאמן של רובין הוד, וסגנו בקרב חבורת פורעי החוק ביער שרווד!'
  },
  {
    id: 'story-8-11',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'Which animal helps Puss in Boots win lands and a castle for his master?',
    questionHe: 'אֵיזוֹ חַיָּה עוֹזֶרֶת לַבְּעָלִים שֶׁלָּהּ לִזְכּוֹת בַּאֲדָמוֹת וְאַרְמוֹן בַּסִּפּוּר "הֶחָתוּל בְּמַגָּפַיִם"?',
    optionsEn: ['A clever cat', 'A talking donkey', 'A giant eagle', 'A faithful dog'],
    optionsHe: ['חָתוּל חָכָם', 'חֲמוֹר מְדַבֵּר', 'נֶשֶׁר עֲנָק', 'כֶּלֶב נֶאֱמָן'],
    answerIndex: 0,
    explanationEn: 'The clever cat wears boots and uses tricks to defeat an ogre and win wealth for his master.',
    explanationHe: 'החתול הפיקח נועל מגפיים ומשתמש בתכסיסים שונים כדי להביס ענק ולזכות בארמונו עבור אדונו.'
  },
  {
    id: 'story-8-12',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'In Norse myths, what is the name of Thor\'s mighty hammer?',
    questionHe: 'בַּמִּיתוֹלוֹגְיָה הַנּוֹרְדִית, מָה שְׁמוֹ שֶׁל פַּטִּישׁ הַקְּרָב הַחָזָק שֶׁל תּוֹר?',
    optionsEn: ['Mjolnir', 'Gungnir', 'Excalibur', 'Aegis'],
    optionsHe: ['מְיוֹלְנִיר', 'גוּנְגְנִיר', 'אֶקְסְקָלִיבּוּר', 'אֵיגִיס'],
    answerIndex: 0,
    explanationEn: 'Thor wields the mighty hammer Mjolnir, which returns to his hand like a boomerang when thrown.',
    explanationHe: 'תור משתמש בפטיש הקרב מילניר, אשר חוזר תמיד לידו כמו בומרנג לאחר השלכתו.'
  },
  {
    id: 'story-8-13',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'How does the Princess test if a girl is a real princess in Hans Christian Andersen\'s tale?',
    questionHe: 'כֵּיצַד בּוֹחֶנֶת הַמַּלְכָּה אִם הַנַּעֲרָה הִיא נְסִיכָה אֲמִתִּית בַּסִּפּוּר הַמְפֻרְסָם?',
    optionsEn: ['By placing a pea under her mattress', 'By asking her to spin gold', 'By testing her singing voice', 'By checking her crown'],
    optionsHe: ['עַל יְדֵי הַנָּחַת אֲפוּנָה מִתַּחַת לַמִּזְרָן', 'עַל יְדֵי בְּחִינַת יְכָלְתָּהּ לִטְווֹת זָהָב', 'עַל יְדֵי בְּחִינַת קוֹל הַשִּׁירָה שֶׁלָּהּ', 'עַל יְדֵי בְּדִיקַת הַכֶּתֶר שֶׁלָּהּ'],
    answerIndex: 0,
    explanationEn: 'She places a single small pea under twenty mattresses and twenty featherbeds. Only a real princess is sensitive enough to feel it!',
    explanationHe: 'היא מניחה אפונה קטנה מתחת לעשרים מזרנים ועשרים שמיכות פוך. רק נסיכה אמיתית רגישה מספיק כדי להרגיש בה!'
  },
  {
    id: 'story-8-14',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'Who wrote the original fairy tales like "The Little Mermaid" and "The Ugly Duckling"?',
    questionHe: 'מִי כָּתַב אֶת הָאַגָּדוֹת הַמְּקוֹרִיּוֹת כְּמוֹ "בַּת הַיָּם הַקְּטַנָּה" וּ"הַבַּרְוָזוֹן הַמְּכֹעָר"?',
    optionsEn: ['Hans Christian Andersen', 'The Brothers Grimm', 'Lewis Carroll', 'Walt Disney'],
    optionsHe: ['הַנְס כְּרִיסְטְיָאן אַנְדֶּרְסֶן', 'הָאַחִים גְרִים', 'לוּאִיס קֶרוֹל', 'ווֹלְט דִּיסְנִי'],
    answerIndex: 0,
    explanationEn: 'Danish author Hans Christian Andersen wrote these and many other beloved classic fairy tales.',
    explanationHe: 'הסופר הדני הנס כריסטיאן אנדרסן כתב את האגדות הקלאסיות והאהובות הללו.'
  },
  {
    id: 'story-8-15',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What is the name of Peter Pan\'s fairy companion?',
    questionHe: 'מָה שְׁמָהּ שֶׁל הַפֵּאָה הַקְּטַנָּה, חֲבֵרָתוֹ שֶׁל פִּיטֶר פֶּן?',
    optionsEn: ['Tinker Bell', 'Zarina', 'Rosetta', 'Silvermist'],
    optionsHe: ['טִינְקֶרְבֶּל (פִינְקִי)', 'זָארִינָה', 'רוֹזֵטָה', 'סִילְבֶרְמִיסְט'],
    answerIndex: 0,
    explanationEn: 'Tinker Bell is Peter Pan\'s loyal but sometimes feisty pixie friend who spreads pixie dust!',
    explanationHe: 'טינקרבל היא פיית הקסם הקטנה והנאמנה של פיטר פן שמפזרת אבקת פיות!'
  },
  {
    id: 'story-8-16',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'In the jungle, who raises Mowgli in Rudyard Kipling\'s "The Jungle Book"?',
    questionHe: "בְּ'סֵפֶר הַגּ\'וּנְגֶּל', מִי מְגַדֵּל אֶת מוֹגְלִי הַתִּינוֹק?",
    optionsEn: ['A pack of wolves', 'A group of monkeys', 'A family of bears', 'A black panther'],
    optionsHe: ['לַהֲקַת זְאֵבִים', 'חֲבוּרַת קוֹפִים', 'מִשְׁפַּחַת דֻּבִּים', 'פַּנְתֵּר שָׁחֹר'],
    answerIndex: 0,
    explanationEn: 'Mowgli is adopted and raised by Father Wolf and Mother Wolf in the Seeonee hills.',
    explanationHe: 'מוגלי מאומץ ומגודל בידי להקת זאבים חמים ביערות הודו.'
  },
  {
    id: 'story-8-17',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'What does Pinocchio have to do to become a real boy?',
    questionHe: 'מָה עַל פִּינוֹקְיוֹ לַעֲשׂוֹת כְּדֵי לַהֲפֹךְ לְיֶלֶד אֲמִתִּי מִבָּשָׂר וָדָם?',
    optionsEn: ['Prove himself brave, truthful, and unselfish', 'Learn to read and write', 'Find a bag of gold coins', 'Build a house for Geppetto'],
    optionsHe: ['לְהוֹכִיחַ שֶׁהוּא אַמִּיץ, דּוֹבֵר אֱמֶת וְלֹא אָנוֹכִי', 'לִלְמֹד לִקְרֹא וְלִכְתֹּב', 'לִמְצֹא שַׂק מַטְבְּעוֹת זָהָב', 'לִבְנוֹת בַּיִת לְגֶ\'פֶּטוֹ'],
    answerIndex: 0,
    explanationEn: 'The Blue Fairy promises Pinocchio he will become a real boy if he proves himself brave, truthful, and unselfish.',
    explanationHe: 'הפיה הכחולה מבטיחה לפינוקיו להפוך אותו לילד אמיתי אם יוכיח שהוא אמיץ, ישר וטוב לב.'
  },
  {
    id: 'story-8-18',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'Who is the famous wooden puppet\'s father and creator?',
    questionHe: 'מִי אָבִיו וּבוֹרְאוֹ שֶׁל פִּינוֹקְיוֹ?',
    optionsEn: ['Geppetto', 'Stromboli', 'The Ringmaster', 'Jiminy'],
    optionsHe: ['גֶ\'פֶּטוֹ', 'סְטְרוֹמְבּוֹלִי', 'מְנַהֵל הַקִּרְקָס', 'גִ\'ימִינִי'],
    answerIndex: 0,
    explanationEn: 'Geppetto is the kind toy-maker who carves Pinocchio from a piece of magic wood.',
    explanationHe: 'ג\'פטו הוא חרש העץ ויוצר הצעצועים הטוב שמגלף את פינוקיו מתוך גזיר עץ קסום.'
  },
  {
    id: 'story-8-19',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'In mythology, what did Pandora open that released trouble into the world?',
    questionHe: 'בַּמִּיתוֹלוֹגְיָה, מָה פָּתְחָה פַּנְדּוֹרָה שֶׁשִּׁחרֵר אֶת כָּל הַצָּרוֹת לָעוֹלָם?',
    optionsEn: ['A box/jar', 'A locked door', 'A magic book', 'A golden cage'],
    optionsHe: ['תֵּבָה / כַּד קָדוֹשׁ', 'דֶּלֶת נְעוּלָה', 'סֵפֶר קְסָמִים', 'כְּלוּב זָהָב'],
    answerIndex: 0,
    explanationEn: 'Pandora opened a container (often called a box), releasing all evils into the world, leaving only Hope inside.',
    explanationHe: 'פנדורה פתחה תיבה (או כד במקור) ושחררה את כל חוליי העולם, כשרק התקווה נותרה בתחתית.'
  },
  {
    id: 'story-8-20',
    category: 'Stories',
    ageGroup: '8-13',
    questionEn: 'Which legendary archer split his opponent\'s arrow in a shooting contest?',
    questionHe: 'אֵיזֶה קַשָּׁת אַגָּדִי פִּלַּח אֶת חִצּוֹ שֶׁל יְרִיבוֹ בְּתַחֲרוּת קְלִיעָה לַמַּטָּרָה?',
    optionsEn: ['Robin Hood', 'King Arthur', 'Legolas', 'William Tell'],
    optionsHe: ['רוֹבִּין הוּד', 'הַמֶּלֶךְ אַרְתוּר', 'לֶגוֹלָאס', 'וִילְיַאם טֶל'],
    answerIndex: 0,
    explanationEn: 'Robin Hood disguised himself to win the Sheriff\'s contest, splitting a bullseye arrow in half!',
    explanationHe: 'רובין הוד התחפש כדי להשתתף בתחרות של השריף, וביצע את הירייה המפורסמת שפילחה חץ במרכז המטרה!'
  },

  // ==================== AGES 13+ (10 Questions) ====================
  {
    id: 'story-13-1',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'How long did it take Odysseus to return home to Ithaca after the Trojan War?',
    questionHe: 'כַּמָּה שָׁנִים לָקַח לְאוֹדִיסֵאוּס לַחְזֹר לְבֵיתוֹ בְּאִיתָקָה לְאַחַר מִלְחֶמֶת טְרוֹיָה?',
    optionsEn: ['10 years', '5 years', '20 years', '2 years'],
    optionsHe: ['10 שָׁנִים', '5 שָׁנִים', '20 שָׁנִים', 'שְׁנָתַיִם'],
    answerIndex: 0,
    explanationEn: 'Odysseus wandered for 10 years after the 10-year Trojan War, making it a total of 20 years away from home!',
    explanationHe: 'אודיסאוס נדד במשך 10 שנים לאחר מלחמת טרויה שנמשכה גם היא 10 שנים, סך הכל 20 שנה מחוץ לביתו!'
  },
  {
    id: 'story-13-2',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'What is the street address of the famous fictional detective Sherlock Holmes?',
    questionHe: 'מַהִי כְּתֹבֶת מְגוּרָיו שֶׁל הַבַּלָּשׁ הַמְפֻרְסָם שֶׁרְלוֹק הוֹלְמְס?',
    optionsEn: ['221B Baker Street', '10 Downing Street', '4 Privet Drive', 'Abbey Road'],
    optionsHe: ['רְחוֹב בֵּיְקֶר 221 בִּי', 'רְחוֹב דָּאוּנִינְג 10', 'דֶּרֶךְ פְּרִיבֶט 4', 'דֶּרֶךְ אֶבִּי'],
    answerIndex: 0,
    explanationEn: 'Sherlock Holmes and Dr. Watson share lodgings at 221B Baker Street in London.',
    explanationHe: 'שרלוק הולמס ושותפו דוקטור ווטסון מתגוררים בדירה ברחוב בייקר 221 ב\' בלונדון.'
  },
  {
    id: 'story-13-3',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'Who wrote the famous gothic novel "Frankenstein"?',
    questionHe: 'מִי כָּתְבָה אֶת רוֹמַן הָאֵיมָה הַגּוֹתִי הַמְפֻרְסָם "פְרַנְקֶנְשְׁטַיִן"?',
    optionsEn: ['Mary Shelley', 'Jane Austen', 'Charlotte Bronte', 'Emily Dickinson'],
    optionsHe: ['מֵרִי שֶׁלִי', 'גִ\'יְין אוֹסְטֶן', 'שַׁרְלוֹט בְּרוֹנְטֶה', 'אֵמִילִי דִּיקִינְסוֹן'],
    answerIndex: 0,
    explanationEn: 'Mary Shelley wrote the novel in 1818 when she was only 20 years old!',
    explanationHe: 'מרי שלי כתבה את יצירת המופת הזו בשנת 1818 כשהייתה בת 20 בלבד!'
  },
  {
    id: 'story-13-4',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'Which classic novel features a giant white whale pursued by Ahab?',
    questionHe: 'בְּאֵיזֶה רוֹמַן קְלָאסִי מוֹפִיעַ לִוְיָתָן לָבָן עֲנָקִי שֶׁאַחֲרָיו רוֹדֵף הַקַּפִּיטָן אַחְאָב?',
    optionsEn: ['Moby-Dick', 'Treasure Island', 'Twenty Thousand Leagues Under the Sea', 'Robinson Crusoe'],
    optionsHe: ['מוֹבִּי דִּיק', 'אִי הַמַּטְמוֹן', 'עֶשְׂרִים אֶלֶף מִיל מִתַּחַת לַמַּיִם', 'רוֹבִּינְזוֹן קְרוּזוֹ'],
    answerIndex: 0,
    explanationEn: 'Herman Melville\'s novel Moby-Dick tells the story of Captain Ahab\'s obsessive quest for revenge.',
    explanationHe: 'הרומן של הרמן מלוויל "מובי דיק" מתאר את מסע הנקמה האובססיבי של הקפטן אחאב בלביויתן הלבן.'
  },
  {
    id: 'story-13-5',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'In Dracula, what natural bulb is used to keep vampires away?',
    questionHe: 'בַּסִּפּוּר על דְּרָקוּלָה, בְּאֵיזֶה יָרָק מִשְׁתַּמְּשִׁים כְּדֵי לְהַרְחִיק עַרְפָּדִים?',
    optionsEn: ['Garlic', 'Onion', 'Ginger', 'Potato'],
    optionsHe: ['שׁוּם', 'בָּצָל', 'זַנְגְּבִיל (גִ\'ינְג\'ֶר)', 'תַּפּוּחַ אֲדָמָה'],
    answerIndex: 0,
    explanationEn: 'Garlic is a well-known repellent for vampires in folklore and Bram Stoker\'s novel Dracula.',
    explanationHe: 'שום הוא אמצעי ההגנה הקלאסי והמוכר ביותר נגד ערפדים בספרות ובפולקלור העממי.'
  },
  {
    id: 'story-13-6',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'Which island does Gulliver visit first, where the inhabitants are only six inches tall?',
    questionHe: 'בְּאֵיזֶה אִי מְבַקֵּר גַּאלִיבֶר לָרִאשׁוֹנָה, שָׁם גּוֹבַהּ הַתּוֹשָׁבִים הוּא כְּשִׁשָּׁה אִינְצְ\'ים בִּלְבַד?',
    optionsEn: ['Lilliput', 'Brobdingnag', 'Laputa', 'Houyhnhnmland'],
    optionsHe: ['לִילִיפּוּט', 'בְּרוֹבְּדִינְגְנָאג', 'לָפּוּטָה', 'ארץ הַהוּינְהְנְמִים'],
    answerIndex: 0,
    explanationEn: 'Gulliver is shipwrecked on Lilliput, where the people (Lilliputians) are tiny compared to him.',
    explanationHe: 'גאליבר נקלע לחופי ליליפוט, אי של אנשים זעירים שרואים בו ענק ומחברים אותו בחבלים.'
  },
  {
    id: 'story-13-7',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'What fictional character fought windmills, believing they were giants?',
    questionHe: 'אֵיזוֹ דְּמוּת סִפְרוּתִית נִלְחֲמָה בְּתַחֲנוֹת רוּחַ מִתּוֹךְ מַחְשָׁבָה שֶׁהֵן עֲנָקִים?',
    optionsEn: ['Don Quixote', 'Sancho Panza', 'King Lear', 'Gargantua'],
    optionsHe: ['דּוֹן קִיחוֹטֶה', 'סַנְצ\'וֹ פַּנְסָה', 'הַמֶּלֶךְ לִיר', 'גַּרְגַּנְטוּאָה'],
    answerIndex: 0,
    explanationEn: 'Don Quixote, the famous Spanish noble, charged at windmills in Cervantes\' classic novel.',
    explanationHe: 'דון קישוט, האביר בן דמות היגון בספרו של סרוואנטס, תקף תחנות רוח משום שדימה אותן לענקים רעים.'
  },
  {
    id: 'story-13-8',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'Who is the author of the Christmas classic "A Christmas Carol"?',
    questionHe: 'מִי הַסּוֹפֵר שֶׁכָּתַב אֶת הַקְּלָאסִיקָה "מַזְמוֹר חָג הַמּוֹלָד" (עַל אֶבֶנְזֶר סְקְרוּג\')?',
    optionsEn: ['Charles Dickens', 'Mark Twain', 'Leo Tolstoy', 'Edgar Allan Poe'],
    optionsHe: ['צ\'וֹרְלְז דִּיקֶנְס', 'מַארְק טְוֶוין', 'לֵאוֹ טוֹלְסְטוֹי', 'אֶדְגָאר אָלָן פּוֹ'],
    answerIndex: 0,
    explanationEn: 'Charles Dickens wrote the novella in 1843, popularizing the phrase "Bah! Humbug!".',
    explanationHe: 'צ\'ארלז דיקנס כתב את הסיפור הידוע ב-1843, המציג את סקרוג\' הקמצן שעובר מהפך בחג.'
  },
  {
    id: 'story-13-9',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'In Greek myths, what monster has snakes for hair and turns anyone who looks at her to stone?',
    questionHe: 'בַּמִּיתוֹלוֹגְיָה, אֵיזֶה מִפְלֶצֶת בַּעֲלַת נְחָשִׁים בִּמְקוֹס שֵׂעָר הוֹפֶכֶת אֶת מִי שֶׁמַּבִּיט בָּהּ לְאֶבֶן?',
    optionsEn: ['Medusa the Gorgon', 'The Chimera', 'The Hydra', 'Scylla'],
    optionsHe: ['מֶדוּזָה הַגּוֹרְגּוֹנָה', 'הַכִּימֶרָה', 'הַהִידְרָה', 'סְקִילָה'],
    answerIndex: 0,
    explanationEn: 'Medusa was a Gorgon whose gaze could turn onlookers into stone, until she was defeated by Perseus.',
    explanationHe: 'מדוזה היא הגורגונה שמבטה הופך אנשים לאבן. הגיבור פרסאוס הביס אותה בעזרת מגן מבריק כמראה.'
  },
  {
    id: 'story-13-10',
    category: 'Stories',
    ageGroup: '13+',
    questionEn: 'In J.R.R. Tolkien\'s universe, who created the One Ring?',
    questionHe: "בַּיְּקוּם שֶׁל ג'.ר.ר. טוֹלְקִין (שַׂר הַטַּבָּעוֹת), מִי יָצַר אֶת הַטַּבַּעַת הָאַחַת?",
    optionsEn: ['Sauron', 'Gandalf', 'Elrond', 'Gollum'],
    optionsHe: ['סָאוּרוֹן', 'גַנְדַּאלְף', 'אֶלְרוֹנְד', 'גּוֹלוּם'],
    answerIndex: 0,
    explanationEn: 'Sauron forged the One Ring in the fires of Mount Doom to gain dominion over Middle-earth.',
    explanationHe: 'סאורון חישל את הטבעת האחת בלהבות הר האבדון כדי להשתלט על הארץ התיכונה.'
  }
];
